package com.exonoxic.palimpsest.client.model;

import com.exonoxic.palimpsest.Palimpsest;
import com.exonoxic.palimpsest.entity.BlotlingEntity;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.HierarchicalModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.util.Mth;

/**
 * Generated by tools/gen_models.py from the "blotling" spec. Edit the spec, not this file.
 */
@SuppressWarnings("unused")
public class BlotlingModel<T extends BlotlingEntity> extends HierarchicalModel<T> {
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(Palimpsest.id("blotling"), "main");
    private final ModelPart root;
    protected final ModelPart puddle;
    protected final ModelPart core;
    protected final ModelPart eye0;
    protected final ModelPart eye0Lid;
    protected final ModelPart eye1;
    protected final ModelPart eye1Lid;
    protected final ModelPart eye2;
    protected final ModelPart eye2Lid;
    protected final ModelPart eye3;
    protected final ModelPart eye3Lid;
    protected final ModelPart splash0;
    protected final ModelPart splash1;
    protected final ModelPart splash2;
    protected final ModelPart maw;

    public BlotlingModel(ModelPart root) {
        super(RenderType::entityTranslucent);
        this.root = root;
        this.puddle = root.getChild("puddle");
        this.core = root.getChild("core");
        this.eye0 = this.core.getChild("eye_0");
        this.eye0Lid = this.eye0.getChild("eye_0_lid");
        this.eye1 = this.core.getChild("eye_1");
        this.eye1Lid = this.eye1.getChild("eye_1_lid");
        this.eye2 = this.core.getChild("eye_2");
        this.eye2Lid = this.eye2.getChild("eye_2_lid");
        this.eye3 = this.core.getChild("eye_3");
        this.eye3Lid = this.eye3.getChild("eye_3_lid");
        this.splash0 = this.core.getChild("splash_0");
        this.splash1 = this.core.getChild("splash_1");
        this.splash2 = this.core.getChild("splash_2");
        this.maw = this.core.getChild("maw");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition puddleDef = root.addOrReplaceChild("puddle", CubeListBuilder.create().texOffs(0, 0).addBox(-7.0F, -0.05F, -7.0F, 14.0F, 0.0F, 14.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition coreDef = root.addOrReplaceChild("core", CubeListBuilder.create().texOffs(88, 0).addBox(-5.0F, -2.0F, -5.0F, 10.0F, 2.0F, 10.0F, new CubeDeformation(0.0F)).texOffs(56, 0).addBox(-4.0F, -6.5F, -4.0F, 8.0F, 5.0F, 8.0F, new CubeDeformation(0.0F)).texOffs(0, 14).addBox(-3.5F, -8.5F, -3.0F, 6.0F, 2.0F, 6.0F, new CubeDeformation(0.0F)).texOffs(24, 14).addBox(3.5F, -4.0F, -2.0F, 2.0F, 3.0F, 4.0F, new CubeDeformation(0.0F)).texOffs(40, 14).addBox(-5.5F, -3.5F, 0.0F, 2.0F, 2.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition eye0Def = coreDef.addOrReplaceChild("eye_0", CubeListBuilder.create().texOffs(84, 14).addBox(-1.0F, -1.0F, -0.5F, 2.0F, 2.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-2.0F, -4.2F, -4.3F, 0.0F, 0.0F, 0.0F));
        PartDefinition eye0LidDef = eye0Def.addOrReplaceChild("eye_0_lid", CubeListBuilder.create().texOffs(96, 14).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 2.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -3.0F, -0.55F, 0.0F, 0.0F, 0.0F));
        PartDefinition eye1Def = coreDef.addOrReplaceChild("eye_1", CubeListBuilder.create().texOffs(100, 14).addBox(-0.5F, -0.5F, -0.5F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(1.6F, -5.0F, -4.2F, 0.0F, 0.0F, 0.0F));
        PartDefinition eye1LidDef = eye1Def.addOrReplaceChild("eye_1_lid", CubeListBuilder.create().texOffs(108, 14).addBox(-0.5F, 0.0F, 0.0F, 1.0F, 1.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -1.5F, -0.55F, 0.0F, 0.0F, 0.0F));
        PartDefinition eye2Def = coreDef.addOrReplaceChild("eye_2", CubeListBuilder.create().texOffs(54, 14).addBox(-1.5F, -1.5F, -0.5F, 3.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-0.5F, -6.8F, -4.3F, 0.0F, 0.0F, 0.0F));
        PartDefinition eye2LidDef = eye2Def.addOrReplaceChild("eye_2_lid", CubeListBuilder.create().texOffs(90, 14).addBox(-1.5F, 0.0F, 0.0F, 3.0F, 3.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -4.5F, -0.55F, 0.0F, 0.0F, 0.0F));
        PartDefinition eye3Def = coreDef.addOrReplaceChild("eye_3", CubeListBuilder.create().texOffs(104, 14).addBox(-0.5F, -0.5F, -0.5F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(3.8F, -2.6F, -2.2F, 0.0F, 0.0F, 0.0F));
        PartDefinition eye3LidDef = eye3Def.addOrReplaceChild("eye_3_lid", CubeListBuilder.create().texOffs(110, 14).addBox(-0.5F, 0.0F, 0.0F, 1.0F, 1.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -1.5F, -0.55F, 0.0F, 0.0F, 0.0F));
        PartDefinition splash0Def = coreDef.addOrReplaceChild("splash_0", CubeListBuilder.create().texOffs(50, 14).addBox(-0.5F, -4.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-2.0F, -8.5F, -1.0F, -0.3F, 0.0F, -0.5F));
        PartDefinition splash1Def = coreDef.addOrReplaceChild("splash_1", CubeListBuilder.create().texOffs(36, 14).addBox(-0.5F, -5.0F, -0.5F, 1.0F, 5.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(1.5F, -8.5F, 0.0F, 0.25F, 0.0F, 0.45F));
        PartDefinition splash2Def = coreDef.addOrReplaceChild("splash_2", CubeListBuilder.create().texOffs(62, 14).addBox(-0.5F, -3.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -8.5F, 2.0F, 0.6F, 0.0F, -0.1F));
        PartDefinition mawDef = coreDef.addOrReplaceChild("maw", CubeListBuilder.create().texOffs(66, 14).addBox(-4.0F, 0.0F, -0.2F, 8.0F, 2.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -2.3F, -4.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 128, 64);
    }

    @Override
    public ModelPart root() {
        return root;
    }

    @Override
    public void setupAnim(T entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        root().getAllParts().forEach(ModelPart::resetPose);
        core.y += Mth.sin(ageInTicks * 0.2F) * 0.3F;
        // Each eye wanders on its own; now and then one blinks.
        eye0.x += Mth.sin(ageInTicks * 0.07F) * 0.3F;
        eye1.y += Mth.sin(ageInTicks * 0.09F + 1.0F) * 0.3F;
        eye2.x += Mth.sin(ageInTicks * 0.05F + 2.0F) * 0.4F;
        eye3.y += Mth.sin(ageInTicks * 0.06F + 3.0F) * 0.2F;
        eye0Lid.y += Mth.sin(ageInTicks * 0.13F) > 0.93F ? 2.0F : 0.0F;
        eye1Lid.y += Mth.sin(ageInTicks * 0.11F + 2.0F) > 0.93F ? 1.0F : 0.0F;
        eye2Lid.y += Mth.sin(ageInTicks * 0.09F + 4.0F) > 0.9F ? 3.0F : 0.0F;
        eye3Lid.y += Mth.sin(ageInTicks * 0.15F + 1.0F) > 0.93F ? 1.0F : 0.0F;
        // The mouth works, slowly, all the time.
        maw.y += Math.max(0.0F, Mth.sin(ageInTicks * 0.08F)) * 2.0F;
        splash0.zRot += Mth.sin(ageInTicks * 0.15F) * 0.08F;
        splash1.zRot -= Mth.sin(ageInTicks * 0.13F + 1.0F) * 0.08F;
    }
}
