package com.exonoxic.palimpsest.client.model;

import com.exonoxic.palimpsest.Palimpsest;
import com.exonoxic.palimpsest.entity.boss.BookbinderEntity;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.HierarchicalModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.util.Mth;

/**
 * Generated by tools/gen_models.py from the "bookbinder" spec. Edit the spec, not this file.
 */
@SuppressWarnings("unused")
public class BookbinderModel<T extends BookbinderEntity> extends HierarchicalModel<T> {
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(Palimpsest.id("bookbinder"), "main");
    private final ModelPart root;
    protected final ModelPart heap;
    protected final ModelPart leftLeg0;
    protected final ModelPart leftLeg0Needle;
    protected final ModelPart leftLeg0Thread;
    protected final ModelPart leftLeg1;
    protected final ModelPart leftLeg1Needle;
    protected final ModelPart leftLeg1Thread;
    protected final ModelPart leftLeg2;
    protected final ModelPart leftLeg2Needle;
    protected final ModelPart leftLeg2Thread;
    protected final ModelPart rightLeg0;
    protected final ModelPart rightLeg0Needle;
    protected final ModelPart rightLeg0Thread;
    protected final ModelPart rightLeg1;
    protected final ModelPart rightLeg1Needle;
    protected final ModelPart rightLeg1Thread;
    protected final ModelPart rightLeg2;
    protected final ModelPart rightLeg2Needle;
    protected final ModelPart rightLeg2Thread;
    protected final ModelPart loosePage0;
    protected final ModelPart loosePage1;
    protected final ModelPart loosePage2;
    protected final ModelPart loosePage3;
    protected final ModelPart tome1;
    protected final ModelPart tome2;
    protected final ModelPart tome3;
    protected final ModelPart leftPaperArm;
    protected final ModelPart leftPaperForearm;
    protected final ModelPart leftPaperHand;
    protected final ModelPart rightPaperArm;
    protected final ModelPart rightPaperForearm;
    protected final ModelPart rightPaperHand;
    protected final ModelPart torso;
    protected final ModelPart head;
    protected final ModelPart loupe;
    protected final ModelPart leftArm;
    protected final ModelPart leftForearm;
    protected final ModelPart leftHand;
    protected final ModelPart rightArm;
    protected final ModelPart rightForearm;
    protected final ModelPart rightHand;
    protected final ModelPart heldNeedle;
    protected final ModelPart heldThread;

    public BookbinderModel(ModelPart root) {
        super(RenderType::entityCutoutNoCull);
        this.root = root;
        this.heap = root.getChild("heap");
        this.leftLeg0 = this.heap.getChild("left_leg_0");
        this.leftLeg0Needle = this.leftLeg0.getChild("left_leg_0_needle");
        this.leftLeg0Thread = this.leftLeg0Needle.getChild("left_leg_0_thread");
        this.leftLeg1 = this.heap.getChild("left_leg_1");
        this.leftLeg1Needle = this.leftLeg1.getChild("left_leg_1_needle");
        this.leftLeg1Thread = this.leftLeg1Needle.getChild("left_leg_1_thread");
        this.leftLeg2 = this.heap.getChild("left_leg_2");
        this.leftLeg2Needle = this.leftLeg2.getChild("left_leg_2_needle");
        this.leftLeg2Thread = this.leftLeg2Needle.getChild("left_leg_2_thread");
        this.rightLeg0 = this.heap.getChild("right_leg_0");
        this.rightLeg0Needle = this.rightLeg0.getChild("right_leg_0_needle");
        this.rightLeg0Thread = this.rightLeg0Needle.getChild("right_leg_0_thread");
        this.rightLeg1 = this.heap.getChild("right_leg_1");
        this.rightLeg1Needle = this.rightLeg1.getChild("right_leg_1_needle");
        this.rightLeg1Thread = this.rightLeg1Needle.getChild("right_leg_1_thread");
        this.rightLeg2 = this.heap.getChild("right_leg_2");
        this.rightLeg2Needle = this.rightLeg2.getChild("right_leg_2_needle");
        this.rightLeg2Thread = this.rightLeg2Needle.getChild("right_leg_2_thread");
        this.loosePage0 = this.heap.getChild("loose_page_0");
        this.loosePage1 = this.heap.getChild("loose_page_1");
        this.loosePage2 = this.heap.getChild("loose_page_2");
        this.loosePage3 = this.heap.getChild("loose_page_3");
        this.tome1 = this.heap.getChild("tome_1");
        this.tome2 = this.heap.getChild("tome_2");
        this.tome3 = this.heap.getChild("tome_3");
        this.leftPaperArm = this.heap.getChild("left_paper_arm");
        this.leftPaperForearm = this.leftPaperArm.getChild("left_paper_forearm");
        this.leftPaperHand = this.leftPaperForearm.getChild("left_paper_hand");
        this.rightPaperArm = this.heap.getChild("right_paper_arm");
        this.rightPaperForearm = this.rightPaperArm.getChild("right_paper_forearm");
        this.rightPaperHand = this.rightPaperForearm.getChild("right_paper_hand");
        this.torso = this.heap.getChild("torso");
        this.head = this.torso.getChild("head");
        this.loupe = this.head.getChild("loupe");
        this.leftArm = this.torso.getChild("left_arm");
        this.leftForearm = this.leftArm.getChild("left_forearm");
        this.leftHand = this.leftForearm.getChild("left_hand");
        this.rightArm = this.torso.getChild("right_arm");
        this.rightForearm = this.rightArm.getChild("right_forearm");
        this.rightHand = this.rightForearm.getChild("right_hand");
        this.heldNeedle = this.rightForearm.getChild("held_needle");
        this.heldThread = this.heldNeedle.getChild("held_thread");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition heapDef = root.addOrReplaceChild("heap", CubeListBuilder.create().texOffs(0, 0).addBox(-8.0F, -4.0F, -7.0F, 16.0F, 4.0F, 14.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftLeg0Def = heapDef.addOrReplaceChild("left_leg_0", CubeListBuilder.create().texOffs(0, 51).addBox(0.0F, -1.0F, -1.0F, 12.0F, 2.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(7.0F, -4.0F, -5.0F, 0.0F, -0.35F, -0.7F));
        PartDefinition leftLeg0NeedleDef = leftLeg0Def.addOrReplaceChild("left_leg_0_needle", CubeListBuilder.create().texOffs(0, 59).addBox(0.0F, -0.5F, -0.5F, 26.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(12.0F, 0.0F, 0.0F, 0.0F, 0.0F, 2.0F));
        PartDefinition leftLeg0ThreadDef = leftLeg0NeedleDef.addOrReplaceChild("left_leg_0_thread", CubeListBuilder.create().texOffs(90, 45).addBox(-0.5F, 0.0F, 0.0F, 1.0F, 5.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(1.5F, 0.0F, 0.0F, 0.0F, 0.0F, -0.6F));
        PartDefinition leftLeg1Def = heapDef.addOrReplaceChild("left_leg_1", CubeListBuilder.create().texOffs(28, 51).addBox(0.0F, -1.0F, -1.0F, 12.0F, 2.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(7.0F, -4.0F, 0.0F, 0.0F, 0.0F, -0.7F));
        PartDefinition leftLeg1NeedleDef = leftLeg1Def.addOrReplaceChild("left_leg_1_needle", CubeListBuilder.create().texOffs(54, 59).addBox(0.0F, -0.5F, -0.5F, 26.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(12.0F, 0.0F, 0.0F, 0.0F, 0.0F, 2.0F));
        PartDefinition leftLeg1ThreadDef = leftLeg1NeedleDef.addOrReplaceChild("left_leg_1_thread", CubeListBuilder.create().texOffs(92, 45).addBox(-0.5F, 0.0F, 0.0F, 1.0F, 5.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(1.5F, 0.0F, 0.0F, 0.0F, 0.0F, -0.6F));
        PartDefinition leftLeg2Def = heapDef.addOrReplaceChild("left_leg_2", CubeListBuilder.create().texOffs(56, 51).addBox(0.0F, -1.0F, -1.0F, 12.0F, 2.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(7.0F, -4.0F, 5.0F, 0.0F, 0.35F, -0.7F));
        PartDefinition leftLeg2NeedleDef = leftLeg2Def.addOrReplaceChild("left_leg_2_needle", CubeListBuilder.create().texOffs(0, 61).addBox(0.0F, -0.5F, -0.5F, 26.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(12.0F, 0.0F, 0.0F, 0.0F, 0.0F, 2.0F));
        PartDefinition leftLeg2ThreadDef = leftLeg2NeedleDef.addOrReplaceChild("left_leg_2_thread", CubeListBuilder.create().texOffs(94, 45).addBox(-0.5F, 0.0F, 0.0F, 1.0F, 5.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(1.5F, 0.0F, 0.0F, 0.0F, 0.0F, -0.6F));
        PartDefinition rightLeg0Def = heapDef.addOrReplaceChild("right_leg_0", CubeListBuilder.create().texOffs(84, 51).mirror().addBox(-12.0F, -1.0F, -1.0F, 12.0F, 2.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-7.0F, -4.0F, -5.0F, 0.0F, 0.35F, 0.7F));
        PartDefinition rightLeg0NeedleDef = rightLeg0Def.addOrReplaceChild("right_leg_0_needle", CubeListBuilder.create().texOffs(54, 61).mirror().addBox(-26.0F, -0.5F, -0.5F, 26.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-12.0F, 0.0F, 0.0F, 0.0F, 0.0F, -2.0F));
        PartDefinition rightLeg0ThreadDef = rightLeg0NeedleDef.addOrReplaceChild("right_leg_0_thread", CubeListBuilder.create().texOffs(96, 45).addBox(-0.5F, 0.0F, 0.0F, 1.0F, 5.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-1.5F, 0.0F, 0.0F, 0.0F, 0.0F, 0.6F));
        PartDefinition rightLeg1Def = heapDef.addOrReplaceChild("right_leg_1", CubeListBuilder.create().texOffs(0, 55).mirror().addBox(-12.0F, -1.0F, -1.0F, 12.0F, 2.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-7.0F, -4.0F, 0.0F, 0.0F, 0.0F, 0.7F));
        PartDefinition rightLeg1NeedleDef = rightLeg1Def.addOrReplaceChild("right_leg_1_needle", CubeListBuilder.create().texOffs(0, 63).mirror().addBox(-26.0F, -0.5F, -0.5F, 26.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-12.0F, 0.0F, 0.0F, 0.0F, 0.0F, -2.0F));
        PartDefinition rightLeg1ThreadDef = rightLeg1NeedleDef.addOrReplaceChild("right_leg_1_thread", CubeListBuilder.create().texOffs(98, 45).addBox(-0.5F, 0.0F, 0.0F, 1.0F, 5.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-1.5F, 0.0F, 0.0F, 0.0F, 0.0F, 0.6F));
        PartDefinition rightLeg2Def = heapDef.addOrReplaceChild("right_leg_2", CubeListBuilder.create().texOffs(28, 55).mirror().addBox(-12.0F, -1.0F, -1.0F, 12.0F, 2.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-7.0F, -4.0F, 5.0F, 0.0F, -0.35F, 0.7F));
        PartDefinition rightLeg2NeedleDef = rightLeg2Def.addOrReplaceChild("right_leg_2_needle", CubeListBuilder.create().texOffs(54, 63).mirror().addBox(-26.0F, -0.5F, -0.5F, 26.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-12.0F, 0.0F, 0.0F, 0.0F, 0.0F, -2.0F));
        PartDefinition rightLeg2ThreadDef = rightLeg2NeedleDef.addOrReplaceChild("right_leg_2_thread", CubeListBuilder.create().texOffs(100, 45).addBox(-0.5F, 0.0F, 0.0F, 1.0F, 5.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-1.5F, 0.0F, 0.0F, 0.0F, 0.0F, 0.6F));
        PartDefinition loosePage0Def = heapDef.addOrReplaceChild("loose_page_0", CubeListBuilder.create().texOffs(106, 33).addBox(-2.5F, 0.0F, 0.0F, 5.0F, 0.0F, 6.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-5.0F, -8.0F, -6.0F, -0.3F, 0.5F, 0.0F));
        PartDefinition loosePage1Def = heapDef.addOrReplaceChild("loose_page_1", CubeListBuilder.create().texOffs(0, 45).addBox(-2.5F, 0.0F, 0.0F, 5.0F, 0.0F, 6.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(4.0F, -9.0F, -7.0F, -0.1F, -0.4F, 0.0F));
        PartDefinition loosePage2Def = heapDef.addOrReplaceChild("loose_page_2", CubeListBuilder.create().texOffs(22, 45).addBox(-2.5F, 0.0F, 0.0F, 5.0F, 0.0F, 6.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(6.0F, -10.0F, 3.0F, 0.1F, 1.4F, 0.0F));
        PartDefinition loosePage3Def = heapDef.addOrReplaceChild("loose_page_3", CubeListBuilder.create().texOffs(44, 45).addBox(-2.5F, 0.0F, 0.0F, 5.0F, 0.0F, 6.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-6.0F, -11.0F, 4.0F, 0.3F, 2.2F, 0.0F));
        PartDefinition tome1Def = heapDef.addOrReplaceChild("tome_1", CubeListBuilder.create().texOffs(0, 18).addBox(-6.5F, -4.0F, -6.0F, 13.0F, 4.0F, 11.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -4.0F, 0.0F, 0.0F, 0.28F, 0.0F));
        PartDefinition tome2Def = heapDef.addOrReplaceChild("tome_2", CubeListBuilder.create().texOffs(0, 33).addBox(-5.5F, -3.0F, -5.0F, 11.0F, 3.0F, 9.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.5F, -8.0F, 1.0F, 0.0F, -0.2F, 0.05F));
        PartDefinition tome3Def = heapDef.addOrReplaceChild("tome_3", CubeListBuilder.create().texOffs(72, 18).addBox(-4.0F, -10.0F, -1.5F, 8.0F, 10.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-2.0F, -9.0F, 5.0F, -0.35F, 0.3F, 0.0F));
        PartDefinition leftPaperArmDef = heapDef.addOrReplaceChild("left_paper_arm", CubeListBuilder.create().texOffs(72, 33).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 8.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(6.0F, -6.0F, -5.0F, -0.6F, 0.4F, 0.5F));
        PartDefinition leftPaperForearmDef = leftPaperArmDef.addOrReplaceChild("left_paper_forearm", CubeListBuilder.create().texOffs(90, 33).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 7.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 8.0F, 0.0F, -0.8F, 0.0F, 0.0F));
        PartDefinition leftPaperHandDef = leftPaperForearmDef.addOrReplaceChild("left_paper_hand", CubeListBuilder.create().texOffs(64, 55).addBox(-1.5F, 0.0F, -0.5F, 3.0F, 4.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 7.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition rightPaperArmDef = heapDef.addOrReplaceChild("right_paper_arm", CubeListBuilder.create().texOffs(80, 33).mirror().addBox(-1.0F, 0.0F, -1.0F, 2.0F, 8.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-6.0F, -6.0F, -5.0F, -0.6F, -0.4F, -0.5F));
        PartDefinition rightPaperForearmDef = rightPaperArmDef.addOrReplaceChild("right_paper_forearm", CubeListBuilder.create().texOffs(98, 33).mirror().addBox(-1.0F, 0.0F, -1.0F, 2.0F, 7.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 8.0F, 0.0F, -0.8F, 0.0F, 0.0F));
        PartDefinition rightPaperHandDef = rightPaperForearmDef.addOrReplaceChild("right_paper_hand", CubeListBuilder.create().texOffs(70, 55).addBox(-1.5F, 0.0F, -0.5F, 3.0F, 4.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 7.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition torsoDef = heapDef.addOrReplaceChild("torso", CubeListBuilder.create().texOffs(48, 18).addBox(-4.0F, -11.0F, -2.0F, 8.0F, 11.0F, 4.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -10.0F, -1.5F, 0.35F, 0.0F, 0.0F));
        PartDefinition headDef = torsoDef.addOrReplaceChild("head", CubeListBuilder.create().texOffs(64, 0).addBox(-4.0F, -8.0F, -4.0F, 8.0F, 8.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -11.0F, -0.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition loupeDef = headDef.addOrReplaceChild("loupe", CubeListBuilder.create().texOffs(56, 55).addBox(-1.5F, -1.5F, -1.0F, 3.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(2.0F, -4.0F, -4.2F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftArmDef = torsoDef.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(40, 33).addBox(-1.0F, -1.0F, -1.0F, 2.0F, 10.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(5.0F, -10.0F, 0.0F, -0.4F, 0.0F, -0.2F));
        PartDefinition leftForearmDef = leftArmDef.addOrReplaceChild("left_forearm", CubeListBuilder.create().texOffs(48, 33).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 10.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 9.0F, 0.0F, -0.3F, 0.0F, 0.0F));
        PartDefinition leftHandDef = leftForearmDef.addOrReplaceChild("left_hand", CubeListBuilder.create().texOffs(66, 45).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 3.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 9.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition rightArmDef = torsoDef.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(56, 33).mirror().addBox(-1.0F, -1.0F, -1.0F, 2.0F, 10.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-5.0F, -10.0F, 0.0F, -0.6F, 0.0F, 0.2F));
        PartDefinition rightForearmDef = rightArmDef.addOrReplaceChild("right_forearm", CubeListBuilder.create().texOffs(64, 33).mirror().addBox(-1.0F, 0.0F, -1.0F, 2.0F, 10.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 9.0F, 0.0F, -0.3F, 0.0F, 0.0F));
        PartDefinition rightHandDef = rightForearmDef.addOrReplaceChild("right_hand", CubeListBuilder.create().texOffs(78, 45).mirror().addBox(-1.5F, 0.0F, -1.5F, 3.0F, 3.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 9.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition heldNeedleDef = rightForearmDef.addOrReplaceChild("held_needle", CubeListBuilder.create().texOffs(60, 0).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 16.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 10.0F, 0.0F, 0.6F, 0.0F, 0.0F));
        PartDefinition heldThreadDef = heldNeedleDef.addOrReplaceChild("held_thread", CubeListBuilder.create().texOffs(88, 33).addBox(-0.5F, 0.0F, 0.0F, 1.0F, 10.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 1.0F, 0.0F, -0.5F, 0.0F, 0.3F));
        return LayerDefinition.create(mesh, 128, 128);
    }

    @Override
    public ModelPart root() {
        return root;
    }

    @Override
    public void setupAnim(T entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        root().getAllParts().forEach(ModelPart::resetPose);
        head.yRot += netHeadYaw * Mth.DEG_TO_RAD;
        head.xRot += headPitch * Mth.DEG_TO_RAD;
        // Now and then his head jerks to one side, against the stitches.
        head.zRot += Mth.sin(ageInTicks * 0.05F) > 0.9F ? 0.25F : 0.0F;
        float step = limbSwing * 0.8F;
        leftLeg0.zRot += Mth.sin(step) * 0.22F * limbSwingAmount;
        leftLeg0.yRot += Mth.cos(step) * 0.18F * limbSwingAmount;
        leftLeg0Thread.zRot += Mth.sin(ageInTicks * 0.1F + 0.0F) * 0.2F;
        leftLeg1.zRot += Mth.sin(step + Mth.PI) * 0.22F * limbSwingAmount;
        leftLeg1.yRot += Mth.cos(step + Mth.PI) * 0.18F * limbSwingAmount;
        leftLeg1Thread.zRot += Mth.sin(ageInTicks * 0.1F + 1.0F) * 0.2F;
        leftLeg2.zRot += Mth.sin(step) * 0.22F * limbSwingAmount;
        leftLeg2.yRot += Mth.cos(step) * 0.18F * limbSwingAmount;
        leftLeg2Thread.zRot += Mth.sin(ageInTicks * 0.1F + 2.0F) * 0.2F;
        rightLeg0.zRot += Mth.sin(step + Mth.PI) * 0.22F * limbSwingAmount;
        rightLeg0.yRot += Mth.cos(step + Mth.PI) * 0.18F * limbSwingAmount;
        rightLeg0Thread.zRot += Mth.sin(ageInTicks * 0.1F + 0.0F) * 0.2F;
        rightLeg1.zRot += Mth.sin(step) * 0.22F * limbSwingAmount;
        rightLeg1.yRot += Mth.cos(step) * 0.18F * limbSwingAmount;
        rightLeg1Thread.zRot += Mth.sin(ageInTicks * 0.1F + 1.0F) * 0.2F;
        rightLeg2.zRot += Mth.sin(step + Mth.PI) * 0.22F * limbSwingAmount;
        rightLeg2.yRot += Mth.cos(step + Mth.PI) * 0.18F * limbSwingAmount;
        rightLeg2Thread.zRot += Mth.sin(ageInTicks * 0.1F + 2.0F) * 0.2F;
        loosePage0.xRot += Mth.sin(ageInTicks * 0.3F) * 0.15F;
        loosePage1.xRot += Mth.sin(ageInTicks * 0.27F + 1.0F) * 0.15F;
        loosePage2.xRot += Mth.sin(ageInTicks * 0.33F + 2.0F) * 0.15F;
        loosePage3.xRot += Mth.sin(ageInTicks * 0.25F + 3.0F) * 0.15F;
        // The paper arms grope forward, one after the other.
        leftPaperArm.xRot += Mth.sin(ageInTicks * 0.09F) * 0.3F;
        rightPaperArm.xRot += Mth.sin(ageInTicks * 0.09F + Mth.PI) * 0.3F;
        leftPaperForearm.xRot += Mth.sin(ageInTicks * 0.09F + 0.8F) * 0.25F;
        rightPaperForearm.xRot += Mth.sin(ageInTicks * 0.09F + Mth.PI + 0.8F) * 0.25F;
        heldThread.zRot += Mth.sin(ageInTicks * 0.12F) * 0.2F;
        if (entity.isRebinding()) {
            torso.xRot += 0.5F;
            leftArm.xRot -= 1.6F + Mth.sin(ageInTicks * 0.4F) * 0.2F;
            rightArm.xRot -= 1.6F + Mth.cos(ageInTicks * 0.4F) * 0.2F;
            leftPaperArm.xRot -= 0.8F;
            rightPaperArm.xRot -= 0.8F;
        } else if (entity.isStunned()) {
            torso.xRot += 0.9F;
            head.xRot += 0.6F;
            heap.y += 1.0F;
        } else if (attackTime > 0) {
            float s = Mth.sin(Mth.sqrt(attackTime) * Mth.PI);
            rightArm.xRot -= 1.8F * s;
            torso.xRot -= 0.3F * s;
            leftPaperArm.xRot -= 1.0F * s;
            rightPaperArm.xRot -= 1.0F * s;
        }
        heap.y += Mth.sin(ageInTicks * 0.08F) * 0.4F;
    }
}
