package com.exonoxic.palimpsest.client.model;

import com.exonoxic.palimpsest.Palimpsest;
import com.exonoxic.palimpsest.entity.boss.BookbinderEntity;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.HierarchicalModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.util.Mth;

/**
 * Generated by tools/gen_models.py from the "bookbinder" spec. Edit the spec, not this file.
 */
@SuppressWarnings("unused")
public class BookbinderModel<T extends BookbinderEntity> extends HierarchicalModel<T> {
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(Palimpsest.id("bookbinder"), "main");
    private final ModelPart root;
    protected final ModelPart heap;
    protected final ModelPart leftLeg0;
    protected final ModelPart leftLeg0Needle;
    protected final ModelPart leftLeg1;
    protected final ModelPart leftLeg1Needle;
    protected final ModelPart leftLeg2;
    protected final ModelPart leftLeg2Needle;
    protected final ModelPart rightLeg0;
    protected final ModelPart rightLeg0Needle;
    protected final ModelPart rightLeg1;
    protected final ModelPart rightLeg1Needle;
    protected final ModelPart rightLeg2;
    protected final ModelPart rightLeg2Needle;
    protected final ModelPart torso;
    protected final ModelPart head;
    protected final ModelPart leftArm;
    protected final ModelPart rightArm;
    protected final ModelPart heldNeedle;

    public BookbinderModel(ModelPart root) {
        super(RenderType::entityCutoutNoCull);
        this.root = root;
        this.heap = root.getChild("heap");
        this.leftLeg0 = this.heap.getChild("left_leg_0");
        this.leftLeg0Needle = this.leftLeg0.getChild("left_leg_0_needle");
        this.leftLeg1 = this.heap.getChild("left_leg_1");
        this.leftLeg1Needle = this.leftLeg1.getChild("left_leg_1_needle");
        this.leftLeg2 = this.heap.getChild("left_leg_2");
        this.leftLeg2Needle = this.leftLeg2.getChild("left_leg_2_needle");
        this.rightLeg0 = this.heap.getChild("right_leg_0");
        this.rightLeg0Needle = this.rightLeg0.getChild("right_leg_0_needle");
        this.rightLeg1 = this.heap.getChild("right_leg_1");
        this.rightLeg1Needle = this.rightLeg1.getChild("right_leg_1_needle");
        this.rightLeg2 = this.heap.getChild("right_leg_2");
        this.rightLeg2Needle = this.rightLeg2.getChild("right_leg_2_needle");
        this.torso = this.heap.getChild("torso");
        this.head = this.torso.getChild("head");
        this.leftArm = this.torso.getChild("left_arm");
        this.rightArm = this.torso.getChild("right_arm");
        this.heldNeedle = this.rightArm.getChild("held_needle");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition heapDef = root.addOrReplaceChild("heap", CubeListBuilder.create().texOffs(0, 0).addBox(-7.0F, -8.0F, -7.0F, 14.0F, 10.0F, 14.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 10.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftLeg0Def = heapDef.addOrReplaceChild("left_leg_0", CubeListBuilder.create().texOffs(4, 24).addBox(0.0F, -1.0F, -1.0F, 12.0F, 2.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(7.0F, -4.0F, -5.0F, 0.0F, -0.35F, -0.7F));
        PartDefinition leftLeg0NeedleDef = leftLeg0Def.addOrReplaceChild("left_leg_0_needle", CubeListBuilder.create().texOffs(56, 37).addBox(0.0F, -0.5F, -0.5F, 26.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(12.0F, 0.0F, 0.0F, 0.0F, 0.0F, 2.0F));
        PartDefinition leftLeg1Def = heapDef.addOrReplaceChild("left_leg_1", CubeListBuilder.create().texOffs(32, 24).addBox(0.0F, -1.0F, -1.0F, 12.0F, 2.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(7.0F, -4.0F, 0.0F, 0.0F, 0.0F, -0.7F));
        PartDefinition leftLeg1NeedleDef = leftLeg1Def.addOrReplaceChild("left_leg_1_needle", CubeListBuilder.create().texOffs(0, 41).addBox(0.0F, -0.5F, -0.5F, 26.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(12.0F, 0.0F, 0.0F, 0.0F, 0.0F, 2.0F));
        PartDefinition leftLeg2Def = heapDef.addOrReplaceChild("left_leg_2", CubeListBuilder.create().texOffs(60, 24).addBox(0.0F, -1.0F, -1.0F, 12.0F, 2.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(7.0F, -4.0F, 5.0F, 0.0F, 0.35F, -0.7F));
        PartDefinition leftLeg2NeedleDef = leftLeg2Def.addOrReplaceChild("left_leg_2_needle", CubeListBuilder.create().texOffs(54, 41).addBox(0.0F, -0.5F, -0.5F, 26.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(12.0F, 0.0F, 0.0F, 0.0F, 0.0F, 2.0F));
        PartDefinition rightLeg0Def = heapDef.addOrReplaceChild("right_leg_0", CubeListBuilder.create().texOffs(88, 24).mirror().addBox(-12.0F, -1.0F, -1.0F, 12.0F, 2.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-7.0F, -4.0F, -5.0F, 0.0F, 0.35F, 0.7F));
        PartDefinition rightLeg0NeedleDef = rightLeg0Def.addOrReplaceChild("right_leg_0_needle", CubeListBuilder.create().texOffs(0, 43).mirror().addBox(-26.0F, -0.5F, -0.5F, 26.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-12.0F, 0.0F, 0.0F, 0.0F, 0.0F, -2.0F));
        PartDefinition rightLeg1Def = heapDef.addOrReplaceChild("right_leg_1", CubeListBuilder.create().texOffs(0, 37).mirror().addBox(-12.0F, -1.0F, -1.0F, 12.0F, 2.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-7.0F, -4.0F, 0.0F, 0.0F, 0.0F, 0.7F));
        PartDefinition rightLeg1NeedleDef = rightLeg1Def.addOrReplaceChild("right_leg_1_needle", CubeListBuilder.create().texOffs(54, 43).mirror().addBox(-26.0F, -0.5F, -0.5F, 26.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-12.0F, 0.0F, 0.0F, 0.0F, 0.0F, -2.0F));
        PartDefinition rightLeg2Def = heapDef.addOrReplaceChild("right_leg_2", CubeListBuilder.create().texOffs(28, 37).mirror().addBox(-12.0F, -1.0F, -1.0F, 12.0F, 2.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-7.0F, -4.0F, 5.0F, 0.0F, -0.35F, 0.7F));
        PartDefinition rightLeg2NeedleDef = rightLeg2Def.addOrReplaceChild("right_leg_2_needle", CubeListBuilder.create().texOffs(0, 45).mirror().addBox(-26.0F, -0.5F, -0.5F, 26.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-12.0F, 0.0F, 0.0F, 0.0F, 0.0F, -2.0F));
        PartDefinition torsoDef = heapDef.addOrReplaceChild("torso", CubeListBuilder.create().texOffs(88, 0).addBox(-4.0F, -12.0F, -2.0F, 8.0F, 12.0F, 4.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -8.0F, -2.0F, 0.3F, 0.0F, 0.0F));
        PartDefinition headDef = torsoDef.addOrReplaceChild("head", CubeListBuilder.create().texOffs(56, 0).addBox(-4.0F, -8.0F, -4.0F, 8.0F, 8.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftArmDef = torsoDef.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(112, 0).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 12.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(5.0F, -11.0F, 0.0F, -0.4F, 0.0F, -0.2F));
        PartDefinition rightArmDef = torsoDef.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(120, 0).mirror().addBox(-1.0F, 0.0F, -1.0F, 2.0F, 12.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-5.0F, -11.0F, 0.0F, -0.6F, 0.0F, 0.2F));
        PartDefinition heldNeedleDef = rightArmDef.addOrReplaceChild("held_needle", CubeListBuilder.create().texOffs(0, 24).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 12.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 11.0F, 0.0F, 0.6F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 128, 128);
    }

    @Override
    public ModelPart root() {
        return root;
    }

    @Override
    public void setupAnim(T entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        root().getAllParts().forEach(ModelPart::resetPose);
        head.yRot += netHeadYaw * Mth.DEG_TO_RAD;
        head.xRot += headPitch * Mth.DEG_TO_RAD;
        float step = limbSwing * 0.8F;
        leftLeg0.zRot += Mth.sin(step) * 0.22F * limbSwingAmount;
        leftLeg0.yRot += Mth.cos(step) * 0.18F * limbSwingAmount;
        leftLeg1.zRot += Mth.sin(step + Mth.PI) * 0.22F * limbSwingAmount;
        leftLeg1.yRot += Mth.cos(step + Mth.PI) * 0.18F * limbSwingAmount;
        leftLeg2.zRot += Mth.sin(step) * 0.22F * limbSwingAmount;
        leftLeg2.yRot += Mth.cos(step) * 0.18F * limbSwingAmount;
        rightLeg0.zRot += Mth.sin(step + Mth.PI) * 0.22F * limbSwingAmount;
        rightLeg0.yRot += Mth.cos(step + Mth.PI) * 0.18F * limbSwingAmount;
        rightLeg1.zRot += Mth.sin(step) * 0.22F * limbSwingAmount;
        rightLeg1.yRot += Mth.cos(step) * 0.18F * limbSwingAmount;
        rightLeg2.zRot += Mth.sin(step + Mth.PI) * 0.22F * limbSwingAmount;
        rightLeg2.yRot += Mth.cos(step + Mth.PI) * 0.18F * limbSwingAmount;
        if (entity.isRebinding()) {
            torso.xRot += 0.5F;
            leftArm.xRot -= 1.6F + Mth.sin(ageInTicks * 0.4F) * 0.2F;
            rightArm.xRot -= 1.6F + Mth.cos(ageInTicks * 0.4F) * 0.2F;
        } else if (entity.isStunned()) {
            torso.xRot += 0.9F;
            head.xRot += 0.6F;
            heap.y += 1.0F;
        } else if (attackTime > 0) {
            float s = Mth.sin(Mth.sqrt(attackTime) * Mth.PI);
            rightArm.xRot -= 1.8F * s;
            torso.xRot -= 0.3F * s;
        }
        heap.y += Mth.sin(ageInTicks * 0.08F) * 0.4F;
    }
}
