package com.exonoxic.palimpsest.client.model;

import com.exonoxic.palimpsest.Palimpsest;
import com.exonoxic.palimpsest.entity.CopyistEntity;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.HierarchicalModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.util.Mth;

/**
 * Generated by tools/gen_models.py from the "copyist" spec. Edit the spec, not this file.
 */
@SuppressWarnings("unused")
public class CopyistModel<T extends CopyistEntity> extends HierarchicalModel<T> {
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(Palimpsest.id("copyist"), "main");
    private final ModelPart root;
    protected final ModelPart leftLeg;
    protected final ModelPart rightLeg;
    protected final ModelPart torso;
    protected final ModelPart neck;
    protected final ModelPart head;
    protected final ModelPart leftHorn;
    protected final ModelPart rightHorn;
    protected final ModelPart leftArm;
    protected final ModelPart rightArm;

    public CopyistModel(ModelPart root) {
        super(RenderType::entityCutoutNoCull);
        this.root = root;
        this.leftLeg = root.getChild("left_leg");
        this.rightLeg = root.getChild("right_leg");
        this.torso = root.getChild("torso");
        this.neck = this.torso.getChild("neck");
        this.head = this.neck.getChild("head");
        this.leftHorn = this.head.getChild("left_horn");
        this.rightHorn = this.head.getChild("right_horn");
        this.leftArm = this.torso.getChild("left_arm");
        this.rightArm = this.torso.getChild("right_arm");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition leftLegDef = root.addOrReplaceChild("left_leg", CubeListBuilder.create().texOffs(16, 0).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 18.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(2.0F, 6.0F, 1.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition rightLegDef = root.addOrReplaceChild("right_leg", CubeListBuilder.create().texOffs(28, 0).mirror().addBox(-1.5F, 0.0F, -1.5F, 3.0F, 18.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-2.0F, 6.0F, 1.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition torsoDef = root.addOrReplaceChild("torso", CubeListBuilder.create().texOffs(0, 23).addBox(-4.0F, -14.0F, -3.0F, 8.0F, 14.0F, 6.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 6.0F, 0.0F, 0.5F, 0.0F, 0.0F));
        PartDefinition neckDef = torsoDef.addOrReplaceChild("neck", CubeListBuilder.create().texOffs(0, 43).addBox(-1.5F, -6.0F, -1.5F, 3.0F, 6.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -14.0F, -1.0F, -0.6F, 0.0F, 0.0F));
        PartDefinition headDef = neckDef.addOrReplaceChild("head", CubeListBuilder.create().texOffs(28, 23).addBox(-3.0F, -4.0F, -7.0F, 6.0F, 5.0F, 9.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -6.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftHornDef = headDef.addOrReplaceChild("left_horn", CubeListBuilder.create().texOffs(12, 43).addBox(0.0F, -3.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(3.0F, -3.0F, -2.0F, 0.0F, 0.0F, -0.5F));
        PartDefinition rightHornDef = headDef.addOrReplaceChild("right_horn", CubeListBuilder.create().texOffs(16, 43).addBox(-1.0F, -3.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-3.0F, -3.0F, -2.0F, 0.0F, 0.0F, 0.5F));
        PartDefinition leftArmDef = torsoDef.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(0, 0).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 21.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(4.0F, -13.0F, -1.0F, -0.5F, 0.0F, 0.0F));
        PartDefinition rightArmDef = torsoDef.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(8, 0).mirror().addBox(-1.0F, 0.0F, -1.0F, 2.0F, 21.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-4.0F, -13.0F, -1.0F, -0.5F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    @Override
    public ModelPart root() {
        return root;
    }

    @Override
    public void setupAnim(T entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        root().getAllParts().forEach(ModelPart::resetPose);
        head.yRot += netHeadYaw * Mth.DEG_TO_RAD * 0.7F;
        neck.yRot += netHeadYaw * Mth.DEG_TO_RAD * 0.3F;
        head.zRot += Mth.sin(ageInTicks * 0.9F) * 0.08F;
        leftLeg.xRot += Mth.cos(limbSwing * 0.5F) * 1.3F * limbSwingAmount;
        rightLeg.xRot += Mth.cos(limbSwing * 0.5F + Mth.PI) * 1.3F * limbSwingAmount;
        leftArm.xRot += Mth.cos(limbSwing * 0.5F + Mth.PI) * 1.1F * limbSwingAmount;
        rightArm.xRot += Mth.cos(limbSwing * 0.5F) * 1.1F * limbSwingAmount;
        if (attackTime > 0) {
            float s = Mth.sin(Mth.sqrt(attackTime) * Mth.PI);
            leftArm.xRot -= 1.2F * s;
            rightArm.xRot -= 1.2F * s;
            head.xRot -= 0.5F * s;
        }
    }
}
