package com.exonoxic.palimpsest.client.model;

import com.exonoxic.palimpsest.Palimpsest;
import com.exonoxic.palimpsest.entity.CopyistEntity;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.HierarchicalModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.util.Mth;

/**
 * Generated by tools/gen_models.py from the "copyist" spec. Edit the spec, not this file.
 */
@SuppressWarnings("unused")
public class CopyistModel<T extends CopyistEntity> extends HierarchicalModel<T> {
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(Palimpsest.id("copyist"), "main");
    private final ModelPart root;
    protected final ModelPart pelvis;
    protected final ModelPart leftThigh;
    protected final ModelPart leftShin;
    protected final ModelPart leftHoof;
    protected final ModelPart rightThigh;
    protected final ModelPart rightShin;
    protected final ModelPart rightHoof;
    protected final ModelPart hideRump;
    protected final ModelPart hideLegL;
    protected final ModelPart hideLegR;
    protected final ModelPart hideTail;
    protected final ModelPart belly;
    protected final ModelPart chest;
    protected final ModelPart neck;
    protected final ModelPart head;
    protected final ModelPart mask;
    protected final ModelPart snout;
    protected final ModelPart maskEarL;
    protected final ModelPart maskEarR;
    protected final ModelPart jaw;
    protected final ModelPart hideNeck;
    protected final ModelPart leftUpperArm;
    protected final ModelPart leftForearm;
    protected final ModelPart leftHand;
    protected final ModelPart leftFinger0;
    protected final ModelPart leftFinger1;
    protected final ModelPart leftFinger2;
    protected final ModelPart rightUpperArm;
    protected final ModelPart rightForearm;
    protected final ModelPart rightHand;
    protected final ModelPart rightFinger0;
    protected final ModelPart rightFinger1;
    protected final ModelPart rightFinger2;
    protected final ModelPart hide;
    protected final ModelPart hideShoulder;
    protected final ModelPart hideForelegL;
    protected final ModelPart hideForelegR;

    public CopyistModel(ModelPart root) {
        super(RenderType::entityCutoutNoCull);
        this.root = root;
        this.pelvis = root.getChild("pelvis");
        this.leftThigh = this.pelvis.getChild("left_thigh");
        this.leftShin = this.leftThigh.getChild("left_shin");
        this.leftHoof = this.leftShin.getChild("left_hoof");
        this.rightThigh = this.pelvis.getChild("right_thigh");
        this.rightShin = this.rightThigh.getChild("right_shin");
        this.rightHoof = this.rightShin.getChild("right_hoof");
        this.hideRump = this.pelvis.getChild("hide_rump");
        this.hideLegL = this.hideRump.getChild("hide_leg_l");
        this.hideLegR = this.hideRump.getChild("hide_leg_r");
        this.hideTail = this.hideRump.getChild("hide_tail");
        this.belly = this.pelvis.getChild("belly");
        this.chest = this.belly.getChild("chest");
        this.neck = this.chest.getChild("neck");
        this.head = this.neck.getChild("head");
        this.mask = this.head.getChild("mask");
        this.snout = this.mask.getChild("snout");
        this.maskEarL = this.mask.getChild("mask_ear_l");
        this.maskEarR = this.mask.getChild("mask_ear_r");
        this.jaw = this.head.getChild("jaw");
        this.hideNeck = this.head.getChild("hide_neck");
        this.leftUpperArm = this.chest.getChild("left_upper_arm");
        this.leftForearm = this.leftUpperArm.getChild("left_forearm");
        this.leftHand = this.leftForearm.getChild("left_hand");
        this.leftFinger0 = this.leftHand.getChild("left_finger_0");
        this.leftFinger1 = this.leftHand.getChild("left_finger_1");
        this.leftFinger2 = this.leftHand.getChild("left_finger_2");
        this.rightUpperArm = this.chest.getChild("right_upper_arm");
        this.rightForearm = this.rightUpperArm.getChild("right_forearm");
        this.rightHand = this.rightForearm.getChild("right_hand");
        this.rightFinger0 = this.rightHand.getChild("right_finger_0");
        this.rightFinger1 = this.rightHand.getChild("right_finger_1");
        this.rightFinger2 = this.rightHand.getChild("right_finger_2");
        this.hide = this.chest.getChild("hide");
        this.hideShoulder = this.chest.getChild("hide_shoulder");
        this.hideForelegL = this.hideShoulder.getChild("hide_foreleg_l");
        this.hideForelegR = this.hideShoulder.getChild("hide_foreleg_r");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition pelvisDef = root.addOrReplaceChild("pelvis", CubeListBuilder.create().texOffs(0, 26).addBox(-3.0F, -1.0F, -2.0F, 6.0F, 3.0F, 4.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 8.0F, 1.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftThighDef = pelvisDef.addOrReplaceChild("left_thigh", CubeListBuilder.create().texOffs(21, 14).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 8.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(2.0F, 1.5F, 0.0F, -0.3F, 0.0F, 0.0F));
        PartDefinition leftShinDef = leftThighDef.addOrReplaceChild("left_shin", CubeListBuilder.create().texOffs(20, 26).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 5.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 8.0F, 0.0F, 0.6F, 0.0F, 0.0F));
        PartDefinition leftHoofDef = leftShinDef.addOrReplaceChild("left_hoof", CubeListBuilder.create().texOffs(0, 33).addBox(-1.5F, 0.0F, -2.0F, 3.0F, 2.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 5.0F, 0.0F, -0.3F, 0.0F, 0.0F));
        PartDefinition rightThighDef = pelvisDef.addOrReplaceChild("right_thigh", CubeListBuilder.create().texOffs(33, 14).mirror().addBox(-1.5F, 0.0F, -1.5F, 3.0F, 8.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-2.0F, 1.5F, 0.0F, -0.3F, 0.0F, 0.0F));
        PartDefinition rightShinDef = rightThighDef.addOrReplaceChild("right_shin", CubeListBuilder.create().texOffs(28, 26).mirror().addBox(-1.0F, 0.0F, -1.0F, 2.0F, 5.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 8.0F, 0.0F, 0.6F, 0.0F, 0.0F));
        PartDefinition rightHoofDef = rightShinDef.addOrReplaceChild("right_hoof", CubeListBuilder.create().texOffs(12, 33).mirror().addBox(-1.5F, 0.0F, -2.0F, 3.0F, 2.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 5.0F, 0.0F, -0.3F, 0.0F, 0.0F));
        PartDefinition hideRumpDef = pelvisDef.addOrReplaceChild("hide_rump", CubeListBuilder.create().texOffs(91, 14).addBox(-4.5F, 0.0F, 0.15F, 9.0F, 8.0F, 0.0F, new CubeDeformation(0.0F)).texOffs(109, 14).addBox(-4.5F, 0.0F, 0.0F, 9.0F, 8.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -1.5F, 2.3F, 0.08F, 0.0F, 0.0F));
        PartDefinition hideLegLDef = hideRumpDef.addOrReplaceChild("hide_leg_l", CubeListBuilder.create().texOffs(36, 26).addBox(-1.0F, 0.0F, 0.15F, 2.0F, 7.0F, 0.0F, new CubeDeformation(0.0F)).texOffs(40, 26).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 7.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(3.3F, 7.5F, 0.1F, 0.05F, 0.0F, -0.06F));
        PartDefinition hideLegRDef = hideRumpDef.addOrReplaceChild("hide_leg_r", CubeListBuilder.create().texOffs(44, 26).addBox(-1.0F, 0.0F, 0.15F, 2.0F, 7.0F, 0.0F, new CubeDeformation(0.0F)).texOffs(48, 26).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 7.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-3.3F, 7.5F, 0.1F, 0.05F, 0.0F, 0.06F));
        PartDefinition hideTailDef = hideRumpDef.addOrReplaceChild("hide_tail", CubeListBuilder.create().texOffs(89, 14).addBox(-0.5F, 0.0F, 0.0F, 1.0F, 9.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 1.0F, 0.2F, 0.35F, 0.0F, 0.0F));
        PartDefinition bellyDef = pelvisDef.addOrReplaceChild("belly", CubeListBuilder.create().texOffs(0, 14).addBox(-3.0F, -7.0F, -2.5F, 6.0F, 7.0F, 4.5F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -1.0F, 0.0F, 0.45F, 0.0F, 0.0F));
        PartDefinition chestDef = bellyDef.addOrReplaceChild("chest", CubeListBuilder.create().texOffs(100, 0).addBox(-3.5F, -7.0F, -3.0F, 7.0F, 7.0F, 5.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -7.0F, 0.0F, 0.35F, 0.0F, 0.0F));
        PartDefinition neckDef = chestDef.addOrReplaceChild("neck", CubeListBuilder.create().texOffs(77, 14).addBox(-1.5F, -6.0F, -1.5F, 3.0F, 6.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -6.5F, -1.5F, -0.55F, 0.0F, 0.0F));
        PartDefinition headDef = neckDef.addOrReplaceChild("head", CubeListBuilder.create().texOffs(45, 14).addBox(-2.5F, -5.0F, -3.0F, 5.0F, 5.0F, 5.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -6.0F, 0.0F, 0.25F, 0.0F, 0.0F));
        PartDefinition maskDef = headDef.addOrReplaceChild("mask", CubeListBuilder.create().texOffs(72, 0).addBox(-3.5F, -2.0F, -4.0F, 7.0F, 5.0F, 7.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -4.5F, -0.3F, 0.0F, 0.0F, 0.0F));
        PartDefinition snoutDef = maskDef.addOrReplaceChild("snout", CubeListBuilder.create().texOffs(24, 33).addBox(-2.0F, -1.5F, -2.0F, 4.0F, 3.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 1.2F, -4.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition maskEarLDef = maskDef.addOrReplaceChild("mask_ear_l", CubeListBuilder.create().texOffs(104, 33).addBox(0.0F, -1.0F, -0.5F, 3.0F, 2.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(3.5F, -1.2F, -1.0F, 0.0F, 0.0F, -0.35F));
        PartDefinition maskEarRDef = maskDef.addOrReplaceChild("mask_ear_r", CubeListBuilder.create().texOffs(112, 33).mirror().addBox(-3.0F, -1.0F, -0.5F, 3.0F, 2.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-3.5F, -1.2F, -1.0F, 0.0F, 0.0F, 0.35F));
        PartDefinition jawDef = headDef.addOrReplaceChild("jaw", CubeListBuilder.create().texOffs(112, 26).addBox(-2.0F, 0.0F, -4.5F, 4.0F, 2.0F, 4.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.0F, 1.5F, 0.15F, 0.0F, 0.0F));
        PartDefinition hideNeckDef = headDef.addOrReplaceChild("hide_neck", CubeListBuilder.create().texOffs(60, 33).addBox(-2.5F, 0.0F, -0.15F, 5.0F, 5.0F, 0.0F, new CubeDeformation(0.0F)).texOffs(70, 33).addBox(-2.5F, 0.0F, 0.0F, 5.0F, 5.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 1.6F, -2.6F, 0.12F, 0.0F, 0.0F));
        PartDefinition leftUpperArmDef = chestDef.addOrReplaceChild("left_upper_arm", CubeListBuilder.create().texOffs(0, 0).addBox(-1.0F, -1.0F, -1.0F, 2.0F, 12.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(4.2F, -6.0F, -1.0F, -0.95F, 0.0F, -0.1F));
        PartDefinition leftForearmDef = leftUpperArmDef.addOrReplaceChild("left_forearm", CubeListBuilder.create().texOffs(56, 0).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 11.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 11.0F, 0.0F, 0.15F, 0.0F, 0.0F));
        PartDefinition leftHandDef = leftForearmDef.addOrReplaceChild("left_hand", CubeListBuilder.create().texOffs(36, 33).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 2.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 11.0F, 0.0F, -0.2F, 0.0F, 0.0F));
        PartDefinition leftFinger0Def = leftHandDef.addOrReplaceChild("left_finger_0", CubeListBuilder.create().texOffs(80, 33).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-1.0F, 2.0F, -1.0F, 0.3F, 0.0F, 0.12F));
        PartDefinition leftFinger1Def = leftHandDef.addOrReplaceChild("left_finger_1", CubeListBuilder.create().texOffs(84, 33).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 2.0F, -1.0F, 0.3F, 0.0F, 0.0F));
        PartDefinition leftFinger2Def = leftHandDef.addOrReplaceChild("left_finger_2", CubeListBuilder.create().texOffs(88, 33).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(1.0F, 2.0F, -1.0F, 0.3F, 0.0F, -0.12F));
        PartDefinition rightUpperArmDef = chestDef.addOrReplaceChild("right_upper_arm", CubeListBuilder.create().texOffs(8, 0).mirror().addBox(-1.0F, -1.0F, -1.0F, 2.0F, 12.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-4.2F, -6.0F, -1.0F, -0.95F, 0.0F, 0.1F));
        PartDefinition rightForearmDef = rightUpperArmDef.addOrReplaceChild("right_forearm", CubeListBuilder.create().texOffs(64, 0).mirror().addBox(-1.0F, 0.0F, -1.0F, 2.0F, 11.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 11.0F, 0.0F, 0.15F, 0.0F, 0.0F));
        PartDefinition rightHandDef = rightForearmDef.addOrReplaceChild("right_hand", CubeListBuilder.create().texOffs(48, 33).mirror().addBox(-1.5F, 0.0F, -1.5F, 3.0F, 2.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 11.0F, 0.0F, -0.2F, 0.0F, 0.0F));
        PartDefinition rightFinger0Def = rightHandDef.addOrReplaceChild("right_finger_0", CubeListBuilder.create().texOffs(92, 33).mirror().addBox(-0.5F, 0.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-1.0F, 2.0F, -1.0F, 0.3F, 0.0F, -0.12F));
        PartDefinition rightFinger1Def = rightHandDef.addOrReplaceChild("right_finger_1", CubeListBuilder.create().texOffs(96, 33).mirror().addBox(-0.5F, 0.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 2.0F, -1.0F, 0.3F, 0.0F, 0.0F));
        PartDefinition rightFinger2Def = rightHandDef.addOrReplaceChild("right_finger_2", CubeListBuilder.create().texOffs(100, 33).mirror().addBox(-0.5F, 0.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(1.0F, 2.0F, -1.0F, 0.3F, 0.0F, 0.12F));
        PartDefinition hideDef = chestDef.addOrReplaceChild("hide", CubeListBuilder.create().texOffs(16, 0).addBox(-5.0F, 0.0F, 0.15F, 10.0F, 13.0F, 0.0F, new CubeDeformation(0.0F)).texOffs(36, 0).addBox(-5.0F, 0.0F, 0.0F, 10.0F, 13.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -7.2F, 2.6F, 0.05F, 0.0F, 0.0F));
        PartDefinition hideShoulderDef = chestDef.addOrReplaceChild("hide_shoulder", CubeListBuilder.create().texOffs(52, 26).addBox(-4.5F, -0.15F, -3.4F, 9.0F, 0.0F, 6.0F, new CubeDeformation(0.0F)).texOffs(82, 26).addBox(-4.5F, 0.0F, -3.4F, 9.0F, 0.0F, 6.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -7.05F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition hideForelegLDef = hideShoulderDef.addOrReplaceChild("hide_foreleg_l", CubeListBuilder.create().texOffs(65, 14).addBox(-1.0F, 0.0F, -0.5F, 2.0F, 9.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(2.2F, 0.0F, -3.3F, -0.72F, 0.0F, -0.08F));
        PartDefinition hideForelegRDef = hideShoulderDef.addOrReplaceChild("hide_foreleg_r", CubeListBuilder.create().texOffs(71, 14).mirror().addBox(-1.0F, 0.0F, -0.5F, 2.0F, 9.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-2.2F, 0.0F, -3.3F, -0.72F, 0.0F, 0.08F));
        return LayerDefinition.create(mesh, 128, 64);
    }

    @Override
    public ModelPart root() {
        return root;
    }

    @Override
    public void setupAnim(T entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        root().getAllParts().forEach(ModelPart::resetPose);
        float crawl = entity.squeeze.crawl(ageInTicks - entity.tickCount);
        float stoop = entity.squeeze.stoop(ageInTicks - entity.tickCount);
        float w = limbSwing * 0.55F;
        // Crawling, it claws itself along rather than striding.
        float a = Math.min(1.0F, limbSwingAmount) * (1.0F - 0.45F * crawl);
        head.yRot += netHeadYaw * Mth.DEG_TO_RAD * 0.6F;
        neck.yRot += netHeadYaw * Mth.DEG_TO_RAD * 0.35F;
        head.xRot += headPitch * Mth.DEG_TO_RAD * 0.5F;
        // It copies animals badly: slow curious tilts broken by sudden snaps of the head.
        float snap = Mth.sin(ageInTicks * 0.23F) > 0.93F ? 0.45F : 0.0F;
        head.zRot += Mth.sin(ageInTicks * 0.04F) * 0.22F + snap;
        head.yRot += Mth.sin(ageInTicks * 0.11F) > 0.95F ? -0.5F : 0.0F;
        // Its jaw works in bursts, chewing nothing.
        if (Mth.sin(ageInTicks * 0.05F) > 0.55F) jaw.xRot += Math.max(0.0F, Mth.sin(ageInTicks * 0.9F)) * 0.3F;
        // A four-limbed walk: arms as forelegs, knuckles down.
        leftThigh.xRot += Mth.cos(w) * 0.8F * a;
        rightThigh.xRot += Mth.cos(w + Mth.PI) * 0.8F * a;
        leftShin.xRot += Math.max(0.0F, Mth.sin(w)) * 0.6F * a;
        rightShin.xRot += Math.max(0.0F, -Mth.sin(w)) * 0.6F * a;
        leftUpperArm.xRot += Mth.cos(w + Mth.PI) * 0.7F * a;
        rightUpperArm.xRot += Mth.cos(w) * 0.7F * a;
        leftForearm.xRot -= Math.max(0.0F, Mth.cos(w)) * 0.4F * a;
        rightForearm.xRot -= Math.max(0.0F, -Mth.cos(w)) * 0.4F * a;
        chest.xRot += Mth.sin(ageInTicks * 0.08F) * 0.03F;
        pelvis.y -= Mth.abs(Mth.cos(w)) * 0.6F * a;
        hide.xRot += -Mth.abs(Mth.sin(w)) * 0.12F * a + Mth.sin(ageInTicks * 0.06F) * 0.03F;
        hideRump.xRot += -Mth.abs(Mth.sin(w + 0.4F)) * 0.25F * a;
        hideNeck.xRot += -Mth.abs(Mth.sin(w + 1.0F)) * 0.2F * a + Mth.sin(ageInTicks * 0.07F) * 0.04F;
        hideLegL.xRot += Mth.sin(w + 0.7F) * 0.35F * a + Mth.sin(ageInTicks * 0.1F) * 0.05F;
        hideLegR.xRot += Mth.sin(w + 2.2F) * 0.35F * a - Mth.sin(ageInTicks * 0.1F) * 0.05F;
        hideTail.zRot += Mth.sin(ageInTicks * 0.13F) * 0.2F;
        hideForelegL.xRot += Mth.sin(w + 1.3F) * 0.3F * a + Mth.sin(ageInTicks * 0.09F) * 0.05F;
        hideForelegR.xRot += Mth.sin(w + 2.9F) * 0.3F * a - Mth.sin(ageInTicks * 0.09F + 1.0F) * 0.05F;
        hideForelegL.zRot += Mth.sin(ageInTicks * 0.05F) * 0.04F;
        hideForelegR.zRot -= Mth.sin(ageInTicks * 0.05F + 0.8F) * 0.04F;
        if (attackTime > 0.0F) {
            float s = Mth.sin(Mth.sqrt(attackTime) * Mth.PI);
            leftUpperArm.xRot -= 1.3F * s;
            rightUpperArm.xRot -= 1.1F * s;
            jaw.xRot += 0.7F * s;
            head.xRot -= 0.4F * s;
        }
        if (crawl > 0.0F) {
            pelvis.xRot += crawl * 0.77F;
            pelvis.y += crawl * 11.0F;
            pelvis.z += crawl * 11.0F;
            leftThigh.xRot += crawl * 0.8F;
            leftThigh.zRot += crawl * -0.3F;
            rightThigh.xRot += crawl * 0.8F;
            rightThigh.zRot += crawl * 0.3F;
            leftShin.xRot += crawl * 0.3F;
            rightShin.xRot += crawl * 0.3F;
            leftHoof.xRot += crawl * 0.1F;
            rightHoof.xRot += crawl * 0.1F;
            hideRump.xRot += crawl * 0.3F;
            neck.xRot += crawl * 0.28F;
            head.xRot += crawl * -1.2F;
            leftUpperArm.xRot += crawl * -1.92F;
            leftUpperArm.zRot += crawl * -0.2F;
            rightUpperArm.xRot += crawl * -1.92F;
            rightUpperArm.zRot += crawl * 0.2F;
            leftForearm.xRot += crawl * -0.42F;
            rightForearm.xRot += crawl * -0.42F;
            leftHand.xRot += crawl * 0.37F;
            rightHand.xRot += crawl * 0.37F;
            hideForelegL.xRot += crawl * 0.65F;
            hideForelegR.xRot += crawl * 0.65F;
        }
        if (stoop > 0.0F) {
            pelvis.xRot += stoop * 0.35F;
            pelvis.y += stoop * 2.0F;
            pelvis.z += stoop * 5.0F;
            leftThigh.xRot += stoop * -0.65F;
            rightThigh.xRot += stoop * -0.65F;
            leftShin.xRot += stoop * 0.7F;
            rightShin.xRot += stoop * 0.7F;
            leftHoof.xRot += stoop * -0.35F;
            rightHoof.xRot += stoop * -0.35F;
            neck.xRot += stoop * 0.5F;
            head.xRot += stoop * -0.6F;
            leftUpperArm.xRot += stoop * -0.3F;
            rightUpperArm.xRot += stoop * -0.3F;
            leftForearm.xRot += stoop * 0.6F;
            rightForearm.xRot += stoop * 0.6F;
            leftHand.xRot += stoop * 1.2F;
            rightHand.xRot += stoop * 1.2F;
        }
    }
}
