package com.exonoxic.palimpsest.client.model;

import com.exonoxic.palimpsest.Palimpsest;
import com.exonoxic.palimpsest.entity.ErratumEntity;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.HierarchicalModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.util.Mth;

/**
 * Generated by tools/gen_models.py from the "erratum_eye" spec. Edit the spec, not this file.
 */
@SuppressWarnings("unused")
public class ErratumEyeModel<T extends ErratumEntity> extends HierarchicalModel<T> {
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(Palimpsest.id("erratum_eye"), "main");
    private final ModelPart root;
    protected final ModelPart rim;
    protected final ModelPart sclera;
    protected final ModelPart iris;
    protected final ModelPart glint;

    public ErratumEyeModel(ModelPart root) {
        super(RenderType::entityCutoutNoCull);
        this.root = root;
        this.rim = root.getChild("rim");
        this.sclera = this.rim.getChild("sclera");
        this.iris = this.sclera.getChild("iris");
        this.glint = this.iris.getChild("glint");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition rimDef = root.addOrReplaceChild("rim", CubeListBuilder.create().texOffs(0, 0).addBox(-6.5F, -2.5F, 0.0F, 13.0F, 5.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition scleraDef = rimDef.addOrReplaceChild("sclera", CubeListBuilder.create().texOffs(0, 5).addBox(-5.5F, -1.5F, 0.0F, 11.0F, 3.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.0F, -0.04F, 0.0F, 0.0F, 0.0F));
        PartDefinition irisDef = scleraDef.addOrReplaceChild("iris", CubeListBuilder.create().texOffs(22, 5).addBox(-1.5F, -1.5F, 0.0F, 3.0F, 3.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.0F, -0.04F, 0.0F, 0.0F, 0.0F));
        PartDefinition glintDef = irisDef.addOrReplaceChild("glint", CubeListBuilder.create().texOffs(28, 5).addBox(0.0F, 0.0F, 0.0F, 1.0F, 1.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-1.5F, -1.5F, -0.03F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 32, 16);
    }

    @Override
    public ModelPart root() {
        return root;
    }

    @Override
    public void setupAnim(T entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        root().getAllParts().forEach(ModelPart::resetPose);
        iris.x = entity.irisX();
        iris.y = entity.irisY();
    }
}
