package com.exonoxic.palimpsest.client.model;

import com.exonoxic.palimpsest.Palimpsest;
import com.exonoxic.palimpsest.entity.ErratumEntity;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.HierarchicalModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.util.Mth;

/**
 * Generated by tools/gen_models.py from the "erratum" spec. Edit the spec, not this file.
 */
@SuppressWarnings("unused")
public class ErratumModel<T extends ErratumEntity> extends HierarchicalModel<T> {
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(Palimpsest.id("erratum"), "main");
    private final ModelPart root;
    protected final ModelPart leftLeg0;
    protected final ModelPart leftFemur0;
    protected final ModelPart leftTibia0;
    protected final ModelPart leftTip0;
    protected final ModelPart leftLeg1;
    protected final ModelPart leftFemur1;
    protected final ModelPart leftTibia1;
    protected final ModelPart leftTip1;
    protected final ModelPart leftLeg2;
    protected final ModelPart leftFemur2;
    protected final ModelPart leftTibia2;
    protected final ModelPart leftTip2;
    protected final ModelPart rightLeg0;
    protected final ModelPart rightFemur0;
    protected final ModelPart rightTibia0;
    protected final ModelPart rightTip0;
    protected final ModelPart rightLeg1;
    protected final ModelPart rightFemur1;
    protected final ModelPart rightTibia1;
    protected final ModelPart rightTip1;
    protected final ModelPart rightLeg2;
    protected final ModelPart rightFemur2;
    protected final ModelPart rightTibia2;
    protected final ModelPart rightTip2;
    protected final ModelPart maw;
    protected final ModelPart tooth0;
    protected final ModelPart tooth1;
    protected final ModelPart tooth2;
    protected final ModelPart tooth3;
    protected final ModelPart tooth4;
    protected final ModelPart tooth5;
    protected final ModelPart tooth6;
    protected final ModelPart tooth7;

    public ErratumModel(ModelPart root) {
        super(RenderType::entityCutoutNoCull);
        this.root = root;
        this.leftLeg0 = root.getChild("left_leg_0");
        this.leftFemur0 = this.leftLeg0.getChild("left_femur_0");
        this.leftTibia0 = this.leftFemur0.getChild("left_tibia_0");
        this.leftTip0 = this.leftTibia0.getChild("left_tip_0");
        this.leftLeg1 = root.getChild("left_leg_1");
        this.leftFemur1 = this.leftLeg1.getChild("left_femur_1");
        this.leftTibia1 = this.leftFemur1.getChild("left_tibia_1");
        this.leftTip1 = this.leftTibia1.getChild("left_tip_1");
        this.leftLeg2 = root.getChild("left_leg_2");
        this.leftFemur2 = this.leftLeg2.getChild("left_femur_2");
        this.leftTibia2 = this.leftFemur2.getChild("left_tibia_2");
        this.leftTip2 = this.leftTibia2.getChild("left_tip_2");
        this.rightLeg0 = root.getChild("right_leg_0");
        this.rightFemur0 = this.rightLeg0.getChild("right_femur_0");
        this.rightTibia0 = this.rightFemur0.getChild("right_tibia_0");
        this.rightTip0 = this.rightTibia0.getChild("right_tip_0");
        this.rightLeg1 = root.getChild("right_leg_1");
        this.rightFemur1 = this.rightLeg1.getChild("right_femur_1");
        this.rightTibia1 = this.rightFemur1.getChild("right_tibia_1");
        this.rightTip1 = this.rightTibia1.getChild("right_tip_1");
        this.rightLeg2 = root.getChild("right_leg_2");
        this.rightFemur2 = this.rightLeg2.getChild("right_femur_2");
        this.rightTibia2 = this.rightFemur2.getChild("right_tibia_2");
        this.rightTip2 = this.rightTibia2.getChild("right_tip_2");
        this.maw = root.getChild("maw");
        this.tooth0 = this.maw.getChild("tooth_0");
        this.tooth1 = this.maw.getChild("tooth_1");
        this.tooth2 = this.maw.getChild("tooth_2");
        this.tooth3 = this.maw.getChild("tooth_3");
        this.tooth4 = this.maw.getChild("tooth_4");
        this.tooth5 = this.maw.getChild("tooth_5");
        this.tooth6 = this.maw.getChild("tooth_6");
        this.tooth7 = this.maw.getChild("tooth_7");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition leftLeg0Def = root.addOrReplaceChild("left_leg_0", CubeListBuilder.create().texOffs(32, 27).addBox(0.0F, -0.5F, -0.5F, 2.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(7.0F, 23.5F, -5.0F, 0.0F, 0.45F, 0.0F));
        PartDefinition leftFemur0Def = leftLeg0Def.addOrReplaceChild("left_femur_0", CubeListBuilder.create().texOffs(16, 14).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 9.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(2.0F, 0.0F, 0.0F, 0.0F, 0.0F, -2.52F));
        PartDefinition leftTibia0Def = leftFemur0Def.addOrReplaceChild("left_tibia_0", CubeListBuilder.create().texOffs(56, 0).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 12.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 9.0F, 0.0F, 0.0F, 0.0F, 2.28F));
        PartDefinition leftTip0Def = leftTibia0Def.addOrReplaceChild("left_tip_0", CubeListBuilder.create().texOffs(40, 14).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftLeg1Def = root.addOrReplaceChild("left_leg_1", CubeListBuilder.create().texOffs(38, 27).addBox(0.0F, -0.5F, -0.5F, 2.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(7.0F, 23.5F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftFemur1Def = leftLeg1Def.addOrReplaceChild("left_femur_1", CubeListBuilder.create().texOffs(20, 14).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 9.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(2.0F, 0.0F, 0.0F, 0.0F, 0.0F, -2.52F));
        PartDefinition leftTibia1Def = leftFemur1Def.addOrReplaceChild("left_tibia_1", CubeListBuilder.create().texOffs(60, 0).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 12.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 9.0F, 0.0F, 0.0F, 0.0F, 2.28F));
        PartDefinition leftTip1Def = leftTibia1Def.addOrReplaceChild("left_tip_1", CubeListBuilder.create().texOffs(44, 14).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftLeg2Def = root.addOrReplaceChild("left_leg_2", CubeListBuilder.create().texOffs(44, 27).addBox(0.0F, -0.5F, -0.5F, 2.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(7.0F, 23.5F, 5.0F, 0.0F, -0.45F, 0.0F));
        PartDefinition leftFemur2Def = leftLeg2Def.addOrReplaceChild("left_femur_2", CubeListBuilder.create().texOffs(24, 14).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 9.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(2.0F, 0.0F, 0.0F, 0.0F, 0.0F, -2.52F));
        PartDefinition leftTibia2Def = leftFemur2Def.addOrReplaceChild("left_tibia_2", CubeListBuilder.create().texOffs(0, 14).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 12.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 9.0F, 0.0F, 0.0F, 0.0F, 2.28F));
        PartDefinition leftTip2Def = leftTibia2Def.addOrReplaceChild("left_tip_2", CubeListBuilder.create().texOffs(48, 14).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition rightLeg0Def = root.addOrReplaceChild("right_leg_0", CubeListBuilder.create().texOffs(50, 27).mirror().addBox(-2.0F, -0.5F, -0.5F, 2.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-7.0F, 23.5F, -5.0F, 0.0F, -0.45F, 0.0F));
        PartDefinition rightFemur0Def = rightLeg0Def.addOrReplaceChild("right_femur_0", CubeListBuilder.create().texOffs(28, 14).mirror().addBox(-0.5F, 0.0F, -0.5F, 1.0F, 9.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-2.0F, 0.0F, 0.0F, 0.0F, 0.0F, 2.52F));
        PartDefinition rightTibia0Def = rightFemur0Def.addOrReplaceChild("right_tibia_0", CubeListBuilder.create().texOffs(4, 14).mirror().addBox(-0.5F, 0.0F, -0.5F, 1.0F, 12.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 9.0F, 0.0F, 0.0F, 0.0F, -2.28F));
        PartDefinition rightTip0Def = rightTibia0Def.addOrReplaceChild("right_tip_0", CubeListBuilder.create().texOffs(52, 14).mirror().addBox(-0.5F, 0.0F, -0.5F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition rightLeg1Def = root.addOrReplaceChild("right_leg_1", CubeListBuilder.create().texOffs(56, 27).mirror().addBox(-2.0F, -0.5F, -0.5F, 2.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-7.0F, 23.5F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition rightFemur1Def = rightLeg1Def.addOrReplaceChild("right_femur_1", CubeListBuilder.create().texOffs(32, 14).mirror().addBox(-0.5F, 0.0F, -0.5F, 1.0F, 9.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-2.0F, 0.0F, 0.0F, 0.0F, 0.0F, 2.52F));
        PartDefinition rightTibia1Def = rightFemur1Def.addOrReplaceChild("right_tibia_1", CubeListBuilder.create().texOffs(8, 14).mirror().addBox(-0.5F, 0.0F, -0.5F, 1.0F, 12.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 9.0F, 0.0F, 0.0F, 0.0F, -2.28F));
        PartDefinition rightTip1Def = rightTibia1Def.addOrReplaceChild("right_tip_1", CubeListBuilder.create().texOffs(56, 14).mirror().addBox(-0.5F, 0.0F, -0.5F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition rightLeg2Def = root.addOrReplaceChild("right_leg_2", CubeListBuilder.create().texOffs(0, 30).mirror().addBox(-2.0F, -0.5F, -0.5F, 2.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-7.0F, 23.5F, 5.0F, 0.0F, 0.45F, 0.0F));
        PartDefinition rightFemur2Def = rightLeg2Def.addOrReplaceChild("right_femur_2", CubeListBuilder.create().texOffs(36, 14).mirror().addBox(-0.5F, 0.0F, -0.5F, 1.0F, 9.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-2.0F, 0.0F, 0.0F, 0.0F, 0.0F, 2.52F));
        PartDefinition rightTibia2Def = rightFemur2Def.addOrReplaceChild("right_tibia_2", CubeListBuilder.create().texOffs(12, 14).mirror().addBox(-0.5F, 0.0F, -0.5F, 1.0F, 12.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 9.0F, 0.0F, 0.0F, 0.0F, -2.28F));
        PartDefinition rightTip2Def = rightTibia2Def.addOrReplaceChild("right_tip_2", CubeListBuilder.create().texOffs(60, 14).mirror().addBox(-0.5F, 0.0F, -0.5F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition mawDef = root.addOrReplaceChild("maw", CubeListBuilder.create().texOffs(0, 0).addBox(-7.0F, 0.0F, -7.0F, 14.0F, 0.0F, 14.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 24.05F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition tooth0Def = mawDef.addOrReplaceChild("tooth_0", CubeListBuilder.create().texOffs(0, 27).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(4.6F, 0.0F, 0.0F, 0.0F, 0.0F, 0.5F));
        PartDefinition tooth1Def = mawDef.addOrReplaceChild("tooth_1", CubeListBuilder.create().texOffs(4, 27).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(3.25F, 0.0F, 3.25F, -0.354F, 0.0F, 0.354F));
        PartDefinition tooth2Def = mawDef.addOrReplaceChild("tooth_2", CubeListBuilder.create().texOffs(8, 27).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.0F, 4.6F, -0.5F, 0.0F, 0.0F));
        PartDefinition tooth3Def = mawDef.addOrReplaceChild("tooth_3", CubeListBuilder.create().texOffs(12, 27).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-3.25F, 0.0F, 3.25F, -0.354F, 0.0F, -0.354F));
        PartDefinition tooth4Def = mawDef.addOrReplaceChild("tooth_4", CubeListBuilder.create().texOffs(16, 27).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-4.6F, 0.0F, 0.0F, 0.0F, 0.0F, -0.5F));
        PartDefinition tooth5Def = mawDef.addOrReplaceChild("tooth_5", CubeListBuilder.create().texOffs(20, 27).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-3.25F, 0.0F, -3.25F, 0.354F, 0.0F, -0.354F));
        PartDefinition tooth6Def = mawDef.addOrReplaceChild("tooth_6", CubeListBuilder.create().texOffs(24, 27).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.0F, -4.6F, 0.5F, 0.0F, 0.0F));
        PartDefinition tooth7Def = mawDef.addOrReplaceChild("tooth_7", CubeListBuilder.create().texOffs(28, 27).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(3.25F, 0.0F, -3.25F, 0.354F, 0.0F, 0.354F));
        return LayerDefinition.create(mesh, 64, 32);
    }

    @Override
    public ModelPart root() {
        return root;
    }

    @Override
    public void setupAnim(T entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        root().getAllParts().forEach(ModelPart::resetPose);
        float ext = entity.legExtension();
        float w = limbSwing * 1.3F;
        // Folded flat under the block, the legs swing out and up as it rises.
        float femurOut = Mth.lerp(ext, -0.35F, -2.52F);
        float tibiaOut = Mth.lerp(ext, 2.95F, 2.28F);
        ModelPart[][] legs = {
            {leftLeg0, leftFemur0, leftTibia0}, {leftLeg1, leftFemur1, leftTibia1}, {leftLeg2, leftFemur2, leftTibia2},
            {rightLeg0, rightFemur0, rightTibia0}, {rightLeg1, rightFemur1, rightTibia1}, {rightLeg2, rightFemur2, rightTibia2}};
        for (int i = 0; i < 6; i++) {
            float side = i < 3 ? 1.0F : -1.0F;
            // Tripod gait: legs 0 and 2 on one side step with leg 1 on the other.
            boolean groupA = (i % 2 == 0) == (i < 3);
            float phase = groupA ? 0.0F : Mth.PI;
            float step = Mth.sin(w + phase) * limbSwingAmount * ext;
            legs[i][0].yRot += step * 0.35F * side;
            legs[i][1].zRot = femurOut * side - Math.max(0.0F, Mth.cos(w + phase)) * 0.35F * limbSwingAmount * ext * side;
            legs[i][2].zRot = tibiaOut * side;
            // Twitch while still, like something trying not to move.
            legs[i][1].zRot += Mth.sin(ageInTicks * 0.8F + i * 1.9F) * 0.03F * ext;
        }
        float gnash = Mth.sin(ageInTicks * 0.6F) * 0.2F * ext;
        for (ModelPart t : new ModelPart[]{tooth0, tooth1, tooth2, tooth3, tooth4, tooth5, tooth6, tooth7}) t.xRot += gnash;
    }
}
