package com.exonoxic.palimpsest.client.model;

import com.exonoxic.palimpsest.Palimpsest;
import com.exonoxic.palimpsest.entity.ErratumEntity;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.HierarchicalModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.util.Mth;

/**
 * Generated by tools/gen_models.py from the "erratum_legs" spec. Edit the spec, not this file.
 */
@SuppressWarnings("unused")
public class ErratumLegsModel<T extends ErratumEntity> extends HierarchicalModel<T> {
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(Palimpsest.id("erratum_legs"), "main");
    private final ModelPart root;
    protected final ModelPart leftLeg0;
    protected final ModelPart leftLeg1;
    protected final ModelPart leftLeg2;
    protected final ModelPart rightLeg0;
    protected final ModelPart rightLeg1;
    protected final ModelPart rightLeg2;

    public ErratumLegsModel(ModelPart root) {
        super(RenderType::entityCutoutNoCull);
        this.root = root;
        this.leftLeg0 = root.getChild("left_leg_0");
        this.leftLeg1 = root.getChild("left_leg_1");
        this.leftLeg2 = root.getChild("left_leg_2");
        this.rightLeg0 = root.getChild("right_leg_0");
        this.rightLeg1 = root.getChild("right_leg_1");
        this.rightLeg2 = root.getChild("right_leg_2");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition leftLeg0Def = root.addOrReplaceChild("left_leg_0", CubeListBuilder.create().texOffs(0, 0).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(5.0F, 20.0F, -4.0F, 0.0F, 0.0F, 0.6F));
        PartDefinition leftLeg1Def = root.addOrReplaceChild("left_leg_1", CubeListBuilder.create().texOffs(4, 0).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(5.0F, 20.0F, 0.0F, 0.0F, 0.0F, 0.6F));
        PartDefinition leftLeg2Def = root.addOrReplaceChild("left_leg_2", CubeListBuilder.create().texOffs(8, 0).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(5.0F, 20.0F, 4.0F, 0.0F, 0.0F, 0.6F));
        PartDefinition rightLeg0Def = root.addOrReplaceChild("right_leg_0", CubeListBuilder.create().texOffs(12, 0).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-5.0F, 20.0F, -4.0F, 0.0F, 0.0F, -0.6F));
        PartDefinition rightLeg1Def = root.addOrReplaceChild("right_leg_1", CubeListBuilder.create().texOffs(16, 0).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-5.0F, 20.0F, 0.0F, 0.0F, 0.0F, -0.6F));
        PartDefinition rightLeg2Def = root.addOrReplaceChild("right_leg_2", CubeListBuilder.create().texOffs(20, 0).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-5.0F, 20.0F, 4.0F, 0.0F, 0.0F, -0.6F));
        return LayerDefinition.create(mesh, 32, 32);
    }

    @Override
    public ModelPart root() {
        return root;
    }

    @Override
    public void setupAnim(T entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        root().getAllParts().forEach(ModelPart::resetPose);
        leftLeg0.xRot += Mth.cos(limbSwing * 1.4F) * 0.6F;
        leftLeg1.xRot += Mth.cos(limbSwing * 1.4F + Mth.PI) * 0.6F;
        leftLeg2.xRot += Mth.cos(limbSwing * 1.4F) * 0.6F;
        rightLeg0.xRot += Mth.cos(limbSwing * 1.4F + Mth.PI) * 0.6F;
        rightLeg1.xRot += Mth.cos(limbSwing * 1.4F) * 0.6F;
        rightLeg2.xRot += Mth.cos(limbSwing * 1.4F + Mth.PI) * 0.6F;
    }
}
