package com.exonoxic.palimpsest.client.model;

import com.exonoxic.palimpsest.Palimpsest;
import com.exonoxic.palimpsest.entity.KnockerEntity;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.HierarchicalModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.util.Mth;

/**
 * Generated by tools/gen_models.py from the "knocker" spec. Edit the spec, not this file.
 */
@SuppressWarnings("unused")
public class KnockerModel<T extends KnockerEntity> extends HierarchicalModel<T> {
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(Palimpsest.id("knocker"), "main");
    private final ModelPart root;
    protected final ModelPart leftLeg;
    protected final ModelPart rightLeg;
    protected final ModelPart torso;
    protected final ModelPart head;
    protected final ModelPart leftArm;
    protected final ModelPart leftHand;
    protected final ModelPart rightArm;
    protected final ModelPart rightHand;

    public KnockerModel(ModelPart root) {
        super(RenderType::entityCutoutNoCull);
        this.root = root;
        this.leftLeg = root.getChild("left_leg");
        this.rightLeg = root.getChild("right_leg");
        this.torso = root.getChild("torso");
        this.head = this.torso.getChild("head");
        this.leftArm = this.torso.getChild("left_arm");
        this.leftHand = this.leftArm.getChild("left_hand");
        this.rightArm = this.torso.getChild("right_arm");
        this.rightHand = this.rightArm.getChild("right_hand");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition leftLegDef = root.addOrReplaceChild("left_leg", CubeListBuilder.create().texOffs(16, 0).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 20.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(2.0F, 4.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition rightLegDef = root.addOrReplaceChild("right_leg", CubeListBuilder.create().texOffs(24, 0).mirror().addBox(-1.0F, 0.0F, -1.0F, 2.0F, 20.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-2.0F, 4.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition torsoDef = root.addOrReplaceChild("torso", CubeListBuilder.create().texOffs(32, 0).addBox(-3.5F, -14.0F, -2.0F, 7.0F, 14.0F, 4.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 4.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition headDef = torsoDef.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 24).addBox(-3.0F, -8.0F, -3.0F, 6.0F, 8.0F, 6.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -14.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftArmDef = torsoDef.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(0, 0).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 22.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(4.5F, -13.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftHandDef = leftArmDef.addOrReplaceChild("left_hand", CubeListBuilder.create().texOffs(24, 24).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 4.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 22.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition rightArmDef = torsoDef.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(8, 0).mirror().addBox(-1.0F, 0.0F, -1.0F, 2.0F, 22.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-4.5F, -13.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition rightHandDef = rightArmDef.addOrReplaceChild("right_hand", CubeListBuilder.create().texOffs(36, 24).mirror().addBox(-1.5F, 0.0F, -1.5F, 3.0F, 4.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 22.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    @Override
    public ModelPart root() {
        return root;
    }

    @Override
    public void setupAnim(T entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        root().getAllParts().forEach(ModelPart::resetPose);
        head.yRot += netHeadYaw * Mth.DEG_TO_RAD;
        head.xRot += headPitch * Mth.DEG_TO_RAD;
        leftLeg.xRot += Mth.cos(limbSwing * 0.6662F) * 0.9F * limbSwingAmount;
        rightLeg.xRot += Mth.cos(limbSwing * 0.6662F + Mth.PI) * 0.9F * limbSwingAmount;
        head.zRot += 0.32F;
        torso.xRot += 0.12F;
        int knock = entity.getKnockAnim();
        if (knock > 0) {
            rightArm.xRot += -2.1F + Mth.sin(knock * 0.62F) * 0.4F;
            rightArm.zRot += 0.15F;
        } else if (entity.getState() == com.exonoxic.palimpsest.entity.KnockerEntity.LUNGE) {
            rightArm.xRot += -1.35F + Mth.cos(ageInTicks * 0.9F) * 0.1F;
            leftArm.xRot += -1.35F - Mth.cos(ageInTicks * 0.9F) * 0.1F;
        } else {
            rightArm.xRot += Mth.cos(limbSwing * 0.6662F + Mth.PI) * 0.5F * limbSwingAmount;
            leftArm.xRot += Mth.cos(limbSwing * 0.6662F) * 0.5F * limbSwingAmount;
            rightArm.zRot += 0.06F + Mth.sin(ageInTicks * 0.04F) * 0.03F;
            leftArm.zRot -= 0.06F + Mth.sin(ageInTicks * 0.04F) * 0.03F;
        }
    }
}
