package com.exonoxic.palimpsest.client.model;

import com.exonoxic.palimpsest.Palimpsest;
import com.exonoxic.palimpsest.entity.KnockerEntity;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.HierarchicalModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.util.Mth;

/**
 * Generated by tools/gen_models.py from the "knocker" spec. Edit the spec, not this file.
 */
@SuppressWarnings("unused")
public class KnockerModel<T extends KnockerEntity> extends HierarchicalModel<T> {
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(Palimpsest.id("knocker"), "main");
    private final ModelPart root;
    protected final ModelPart hips;
    protected final ModelPart leftThigh;
    protected final ModelPart leftShin;
    protected final ModelPart leftFoot;
    protected final ModelPart rightThigh;
    protected final ModelPart rightShin;
    protected final ModelPart rightFoot;
    protected final ModelPart waist;
    protected final ModelPart chest;
    protected final ModelPart neck;
    protected final ModelPart head;
    protected final ModelPart jaw;
    protected final ModelPart ring;
    protected final ModelPart leftEar;
    protected final ModelPart rightEar;
    protected final ModelPart bindingKnot;
    protected final ModelPart bindingEnd;
    protected final ModelPart wisp0;
    protected final ModelPart wisp1;
    protected final ModelPart leftUpperArm;
    protected final ModelPart leftForearm;
    protected final ModelPart leftHand;
    protected final ModelPart leftFinger0;
    protected final ModelPart leftFinger1;
    protected final ModelPart leftFinger2;
    protected final ModelPart leftThumb;
    protected final ModelPart rightUpperArm;
    protected final ModelPart rightForearm;
    protected final ModelPart rightHand;
    protected final ModelPart rightFinger0;
    protected final ModelPart rightFinger1;
    protected final ModelPart rightFinger2;
    protected final ModelPart rightThumb;
    protected final ModelPart shroudBack;
    protected final ModelPart shroudBackLower;
    protected final ModelPart shroudFlap;
    protected final ModelPart shroudStrip;

    public KnockerModel(ModelPart root) {
        super(RenderType::entityCutoutNoCull);
        this.root = root;
        this.hips = root.getChild("hips");
        this.leftThigh = this.hips.getChild("left_thigh");
        this.leftShin = this.leftThigh.getChild("left_shin");
        this.leftFoot = this.leftShin.getChild("left_foot");
        this.rightThigh = this.hips.getChild("right_thigh");
        this.rightShin = this.rightThigh.getChild("right_shin");
        this.rightFoot = this.rightShin.getChild("right_foot");
        this.waist = this.hips.getChild("waist");
        this.chest = this.waist.getChild("chest");
        this.neck = this.chest.getChild("neck");
        this.head = this.neck.getChild("head");
        this.jaw = this.head.getChild("jaw");
        this.ring = this.jaw.getChild("ring");
        this.leftEar = this.head.getChild("left_ear");
        this.rightEar = this.head.getChild("right_ear");
        this.bindingKnot = this.head.getChild("binding_knot");
        this.bindingEnd = this.head.getChild("binding_end");
        this.wisp0 = this.head.getChild("wisp_0");
        this.wisp1 = this.head.getChild("wisp_1");
        this.leftUpperArm = this.chest.getChild("left_upper_arm");
        this.leftForearm = this.leftUpperArm.getChild("left_forearm");
        this.leftHand = this.leftForearm.getChild("left_hand");
        this.leftFinger0 = this.leftHand.getChild("left_finger_0");
        this.leftFinger1 = this.leftHand.getChild("left_finger_1");
        this.leftFinger2 = this.leftHand.getChild("left_finger_2");
        this.leftThumb = this.leftHand.getChild("left_thumb");
        this.rightUpperArm = this.chest.getChild("right_upper_arm");
        this.rightForearm = this.rightUpperArm.getChild("right_forearm");
        this.rightHand = this.rightForearm.getChild("right_hand");
        this.rightFinger0 = this.rightHand.getChild("right_finger_0");
        this.rightFinger1 = this.rightHand.getChild("right_finger_1");
        this.rightFinger2 = this.rightHand.getChild("right_finger_2");
        this.rightThumb = this.rightHand.getChild("right_thumb");
        this.shroudBack = this.chest.getChild("shroud_back");
        this.shroudBackLower = this.shroudBack.getChild("shroud_back_lower");
        this.shroudFlap = this.chest.getChild("shroud_flap");
        this.shroudStrip = this.chest.getChild("shroud_strip");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition hipsDef = root.addOrReplaceChild("hips", CubeListBuilder.create().texOffs(100, 22).addBox(-2.5F, -1.0F, -1.5F, 5.0F, 3.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 2.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftThighDef = hipsDef.addOrReplaceChild("left_thigh", CubeListBuilder.create().texOffs(82, 0).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 11.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(1.6F, 1.0F, 0.0F, -0.16F, 0.0F, 0.02F));
        PartDefinition leftShinDef = leftThighDef.addOrReplaceChild("left_shin", CubeListBuilder.create().texOffs(0, 22).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 9.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 11.0F, 0.0F, 0.34F, 0.0F, 0.0F));
        PartDefinition leftFootDef = leftShinDef.addOrReplaceChild("left_foot", CubeListBuilder.create().texOffs(0, 33).addBox(-1.2F, 0.0F, -4.2F, 2.4F, 1.0F, 5.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 9.0F, 0.0F, -0.18F, 0.0F, 0.0F));
        PartDefinition rightThighDef = hipsDef.addOrReplaceChild("right_thigh", CubeListBuilder.create().texOffs(90, 0).mirror().addBox(-1.0F, 0.0F, -1.0F, 2.0F, 11.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-1.6F, 1.0F, 0.0F, -0.16F, 0.0F, -0.02F));
        PartDefinition rightShinDef = rightThighDef.addOrReplaceChild("right_shin", CubeListBuilder.create().texOffs(8, 22).mirror().addBox(-1.0F, 0.0F, -1.0F, 2.0F, 9.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 11.0F, 0.0F, 0.34F, 0.0F, 0.0F));
        PartDefinition rightFootDef = rightShinDef.addOrReplaceChild("right_foot", CubeListBuilder.create().texOffs(15, 33).mirror().addBox(-1.2F, 0.0F, -4.2F, 2.4F, 1.0F, 5.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 9.0F, 0.0F, -0.18F, 0.0F, 0.0F));
        PartDefinition waistDef = hipsDef.addOrReplaceChild("waist", CubeListBuilder.create().texOffs(34, 22).addBox(-2.0F, -6.0F, -1.5F, 4.0F, 6.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -1.0F, 0.0F, 0.16F, 0.0F, 0.0F));
        PartDefinition chestDef = waistDef.addOrReplaceChild("chest", CubeListBuilder.create().texOffs(102, 0).addBox(-3.5F, -8.0F, -2.0F, 7.0F, 8.0F, 4.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -6.0F, 0.0F, 0.24F, 0.0F, 0.0F));
        PartDefinition neckDef = chestDef.addOrReplaceChild("neck", CubeListBuilder.create().texOffs(30, 33).addBox(-1.0F, -4.0F, -1.0F, 2.0F, 4.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -8.0F, -0.6F, 0.66F, 0.0F, 0.0F));
        PartDefinition headDef = neckDef.addOrReplaceChild("head", CubeListBuilder.create().texOffs(58, 0).addBox(-3.0F, -9.0F, -3.0F, 6.0F, 7.0F, 6.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -4.0F, 0.0F, -0.52F, 0.0F, 0.26F));
        PartDefinition jawDef = headDef.addOrReplaceChild("jaw", CubeListBuilder.create().texOffs(54, 22).addBox(-2.5F, 0.0F, -5.0F, 5.0F, 2.0F, 5.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -2.0F, 2.0F, 0.06F, 0.0F, 0.0F));
        PartDefinition ringDef = jawDef.addOrReplaceChild("ring", CubeListBuilder.create().texOffs(94, 33).addBox(-1.0F, 0.0F, -0.5F, 2.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)).texOffs(86, 33).addBox(-2.0F, 1.0F, -0.5F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F)).texOffs(90, 33).addBox(1.0F, 1.0F, -0.5F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F)).texOffs(100, 33).addBox(-1.0F, 3.0F, -0.5F, 2.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 2.0F, -4.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftEarDef = headDef.addOrReplaceChild("left_ear", CubeListBuilder.create().texOffs(58, 33).addBox(0.0F, -1.5F, -1.0F, 1.0F, 3.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(3.0F, -5.5F, 0.5F, 0.0F, -0.35F, 0.1F));
        PartDefinition rightEarDef = headDef.addOrReplaceChild("right_ear", CubeListBuilder.create().texOffs(64, 33).mirror().addBox(-1.0F, -1.5F, -1.0F, 1.0F, 3.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-3.0F, -5.5F, 0.5F, 0.0F, 0.35F, -0.1F));
        PartDefinition bindingKnotDef = headDef.addOrReplaceChild("binding_knot", CubeListBuilder.create().texOffs(78, 33).addBox(-1.0F, -1.0F, -1.0F, 2.0F, 1.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(2.2F, -9.0F, 0.0F, 0.0F, 0.3F, 0.2F));
        PartDefinition bindingEndDef = headDef.addOrReplaceChild("binding_end", CubeListBuilder.create().texOffs(48, 22).addBox(0.0F, 0.0F, -1.0F, 0.0F, 7.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-3.02F, -6.0F, 0.2F, 0.15F, 0.0F, 0.1F));
        PartDefinition wisp0Def = headDef.addOrReplaceChild("wisp_0", CubeListBuilder.create().texOffs(98, 22).addBox(-0.5F, 0.0F, 0.0F, 1.0F, 7.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-1.5F, -8.8F, 2.9F, 0.25F, 0.0F, 0.1F));
        PartDefinition wisp1Def = headDef.addOrReplaceChild("wisp_1", CubeListBuilder.create().texOffs(52, 22).addBox(-0.5F, 0.0F, 0.0F, 1.0F, 9.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(1.8F, -8.6F, 2.8F, 0.18F, 0.0F, -0.14F));
        PartDefinition leftUpperArmDef = chestDef.addOrReplaceChild("left_upper_arm", CubeListBuilder.create().texOffs(26, 0).addBox(-1.0F, -1.0F, -1.0F, 2.0F, 13.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(4.3F, -7.2F, 0.0F, -0.34F, 0.0F, -0.07F));
        PartDefinition leftForearmDef = leftUpperArmDef.addOrReplaceChild("left_forearm", CubeListBuilder.create().texOffs(42, 0).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 12.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 12.0F, 0.0F, -0.28F, 0.0F, 0.0F));
        PartDefinition leftHandDef = leftForearmDef.addOrReplaceChild("left_hand", CubeListBuilder.create().texOffs(38, 33).addBox(-1.5F, 0.0F, -1.0F, 3.0F, 3.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 12.0F, 0.0F, 0.1F, 0.0F, 0.0F));
        PartDefinition leftFinger0Def = leftHandDef.addOrReplaceChild("left_finger_0", CubeListBuilder.create().texOffs(74, 22).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-1.0F, 3.0F, -0.3F, 0.0F, 0.0F, 0.06F));
        PartDefinition leftFinger1Def = leftHandDef.addOrReplaceChild("left_finger_1", CubeListBuilder.create().texOffs(78, 22).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 3.0F, -0.3F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftFinger2Def = leftHandDef.addOrReplaceChild("left_finger_2", CubeListBuilder.create().texOffs(82, 22).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(1.0F, 3.0F, -0.3F, 0.0F, 0.0F, -0.06F));
        PartDefinition leftThumbDef = leftHandDef.addOrReplaceChild("left_thumb", CubeListBuilder.create().texOffs(70, 33).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-1.8F, 1.0F, -0.6F, -0.3F, 0.0F, 0.5F));
        PartDefinition rightUpperArmDef = chestDef.addOrReplaceChild("right_upper_arm", CubeListBuilder.create().texOffs(34, 0).mirror().addBox(-1.0F, -1.0F, -1.0F, 2.0F, 13.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-4.3F, -7.2F, 0.0F, -0.34F, 0.0F, 0.07F));
        PartDefinition rightForearmDef = rightUpperArmDef.addOrReplaceChild("right_forearm", CubeListBuilder.create().texOffs(50, 0).mirror().addBox(-1.0F, 0.0F, -1.0F, 2.0F, 12.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 12.0F, 0.0F, -0.28F, 0.0F, 0.0F));
        PartDefinition rightHandDef = rightForearmDef.addOrReplaceChild("right_hand", CubeListBuilder.create().texOffs(48, 33).mirror().addBox(-1.5F, 0.0F, -1.0F, 3.0F, 3.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 12.0F, 0.0F, 0.1F, 0.0F, 0.0F));
        PartDefinition rightFinger0Def = rightHandDef.addOrReplaceChild("right_finger_0", CubeListBuilder.create().texOffs(86, 22).mirror().addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-1.0F, 3.0F, -0.3F, 0.0F, 0.0F, -0.06F));
        PartDefinition rightFinger1Def = rightHandDef.addOrReplaceChild("right_finger_1", CubeListBuilder.create().texOffs(90, 22).mirror().addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 3.0F, -0.3F, 0.0F, 0.0F, 0.0F));
        PartDefinition rightFinger2Def = rightHandDef.addOrReplaceChild("right_finger_2", CubeListBuilder.create().texOffs(94, 22).mirror().addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(1.0F, 3.0F, -0.3F, 0.0F, 0.0F, 0.06F));
        PartDefinition rightThumbDef = rightHandDef.addOrReplaceChild("right_thumb", CubeListBuilder.create().texOffs(74, 33).mirror().addBox(-0.5F, 0.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(1.8F, 1.0F, -0.6F, -0.3F, 0.0F, -0.5F));
        PartDefinition shroudBackDef = chestDef.addOrReplaceChild("shroud_back", CubeListBuilder.create().texOffs(16, 22).addBox(-4.5F, 0.0F, 0.0F, 9.0F, 9.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -8.0F, 2.25F, -0.03F, 0.0F, 0.0F));
        PartDefinition shroudBackLowerDef = shroudBackDef.addOrReplaceChild("shroud_back_lower", CubeListBuilder.create().texOffs(8, 0).addBox(-4.5F, 0.0F, 0.0F, 9.0F, 16.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 9.0F, 0.0F, -0.36F, 0.0F, 0.0F));
        PartDefinition shroudFlapDef = chestDef.addOrReplaceChild("shroud_flap", CubeListBuilder.create().texOffs(0, 0).addBox(-4.0F, 0.0F, 0.0F, 4.0F, 22.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-0.5F, -8.0F, -2.3F, -0.34F, 0.0F, 0.04F));
        PartDefinition shroudStripDef = chestDef.addOrReplaceChild("shroud_strip", CubeListBuilder.create().texOffs(98, 0).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 13.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(3.2F, -7.5F, -2.25F, -0.3F, 0.0F, -0.05F));
        return LayerDefinition.create(mesh, 128, 64);
    }

    @Override
    public ModelPart root() {
        return root;
    }

    @Override
    public void setupAnim(T entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        root().getAllParts().forEach(ModelPart::resetPose);
        float crawl = entity.squeeze.crawl(ageInTicks - entity.tickCount);
        float stoop = entity.squeeze.stoop(ageInTicks - entity.tickCount);
        float breath = Mth.sin(ageInTicks * 0.07F);
        float pt = ageInTicks - entity.tickCount;
        int state = entity.getState();
        // Every state eases in and out rather than snapping.
        float knocking = Anim.ease(entity, 0, state == com.exonoxic.palimpsest.entity.KnockerEntity.KNOCKING, ageInTicks, 0.18F);
        float lunging = Anim.ease(entity, 1, state == com.exonoxic.palimpsest.entity.KnockerEntity.LUNGE, ageInTicks, 0.3F);
        float searching = Anim.ease(entity, 2, state == com.exonoxic.palimpsest.entity.KnockerEntity.SEARCHING, ageInTicks, 0.1F);
        float leaving = Anim.ease(entity, 3, state == com.exonoxic.palimpsest.entity.KnockerEntity.LEAVING, ageInTicks, 0.1F);
        float idle = Math.max(0.0F, 1.0F - knocking - lunging - searching - leaving);
        // Bent double or crawling, its body keeps that shape; only the jaw and hands still act.
        float upright = 1.0F - Math.max(crawl, stoop);

        // ---- gestures: each starts a few ticks before its sound (KnockerEntity.GESTURE_LEAD), so the
        // arm is drawn back in time for the blows to land on the hits in the recording
        final float[] COCK = {0.264F, -0.106F, 0.242F, -2.120F, -2.469F};
        final float[] HIT = {0.084F, -0.182F, 0.301F, -1.578F, -1.242F};
        final float[] SCRATCH_TOP = {-0.736F, 1.014F, 0.637F, -0.830F, -2.270F};
        final float[] SCRATCH_END = {-0.032F, -0.204F, 0.766F, -0.452F, -2.464F};
        final float[] S_COCK = {0.126F, 0.705F, -0.306F, -3.751F, -0.609F};
        final float[] S_HIT = {0.207F, 0.689F, 0.164F, -3.154F, -0.686F};
        final float[] S_SCRATCH_TOP = {-0.370F, 0.719F, -0.230F, -3.584F, 0.002F};
        final float[] S_SCRATCH_END = {0.516F, 0.475F, 0.494F, -3.699F, 0.623F};
        int kind = entity.gestureKind();
        float gt = entity.gestureTime(pt);
        float reach = 0.0F;   // how far the right arm is taken over by a gesture (0..1)
        float hit = 0.0F;     // 0 cocked back, 1 knuckles on the wood (or 0 top, 1 bottom of a scratch)
        boolean scratching = false;
        if (kind == com.exonoxic.palimpsest.entity.KnockerEntity.GESTURE_KNOCK || kind == com.exonoxic.palimpsest.entity.KnockerEntity.GESTURE_POUND) {
            // event.knock holds three knocks 17 ticks apart (further apart at a lower pitch).
            float gap = kind == com.exonoxic.palimpsest.entity.KnockerEntity.GESTURE_POUND ? 17.0F / com.exonoxic.palimpsest.entity.KnockerEntity.POUND_PITCH : 17.0F;
            float t = gt - com.exonoxic.palimpsest.entity.KnockerEntity.GESTURE_LEAD;
            reach = Anim.keys(gt, 0.0F, 0.0F, 3.0F, 1.0F, gap * 2.0F + 12.0F, 1.0F, gap * 2.0F + 22.0F, 0.0F);
            hit = 0.3F + Anim.knock(t) + Anim.knock(t - gap) + Anim.knock(t - gap * 2.0F);
        } else if (kind == com.exonoxic.palimpsest.entity.KnockerEntity.GESTURE_TAP) {
            // Quick raps of the knuckles, 6 and 11 ticks after the first.
            float t = gt - com.exonoxic.palimpsest.entity.KnockerEntity.GESTURE_LEAD;
            reach = Anim.keys(gt, 0.0F, 0.0F, 3.0F, 1.0F, 18.0F, 1.0F, 28.0F, 0.0F);
            hit = 0.3F + 0.6F * (Anim.knock(t) + Anim.knock(t - 6.0F) + Anim.knock(t - 11.0F));
        } else if (kind == com.exonoxic.palimpsest.entity.KnockerEntity.GESTURE_GLASS_TAP) {
            // Slow taps on the glass, 18 and 38 ticks after the first.
            float t = gt - com.exonoxic.palimpsest.entity.KnockerEntity.GESTURE_LEAD;
            reach = Anim.keys(gt, 0.0F, 0.0F, 3.0F, 1.0F, 48.0F, 1.0F, 60.0F, 0.0F);
            hit = 0.35F + 0.55F * (Anim.knock(t) + Anim.knock(t - 18.0F) + Anim.knock(t - 38.0F));
        } else if (kind == com.exonoxic.palimpsest.entity.KnockerEntity.GESTURE_SCRATCH) {
            // Up to the glass or the boards, then the nails dragged all the way down, slowly.
            scratching = true;
            reach = Anim.keys(gt, 0.0F, 0.0F, 4.0F, 1.0F, 86.0F, 1.0F, 98.0F, 0.0F);
            hit = Anim.keys(gt, 4.0F, 0.0F, 84.0F, 1.0F) + Mth.sin(gt * 2.1F) * 0.012F * reach;
        }
        // While it knocks the hand stays up at the door between rounds.
        if (!scratching && knocking > reach) {
            if (reach <= 0.0F) hit = 0.3F + Mth.sin(ageInTicks * 0.05F) * 0.04F;
            reach = knocking;
        }
        reach *= 1.0F - crawl;
        float armFree = 1.0F - reach;

        // ---- walking, crawling
        float a = Math.min(1.0F, limbSwingAmount) * (1.0F - crawl);
        float w = limbSwing * 0.42F;
        chest.xRot += breath * 0.03F;
        neck.xRot += breath * 0.025F;
        head.yRot += netHeadYaw * Mth.DEG_TO_RAD * 0.65F;
        neck.yRot += netHeadYaw * Mth.DEG_TO_RAD * 0.3F;
        head.xRot += headPitch * Mth.DEG_TO_RAD * 0.6F;
        // It is always listening: the head drifts, tilting an ear towards whatever it heard.
        head.zRot += Mth.sin(ageInTicks * 0.021F) * 0.14F;
        leftEar.yRot += Mth.sin(ageInTicks * 0.13F) * 0.08F;
        rightEar.yRot -= Mth.sin(ageInTicks * 0.13F + 1.3F) * 0.08F;
        // Long, slow strides; knees fold on the back swing; the whole body bobs and rolls.
        leftThigh.xRot += Mth.cos(w) * 0.85F * a;
        rightThigh.xRot += Mth.cos(w + Mth.PI) * 0.85F * a;
        leftShin.xRot += Math.max(0.0F, Mth.sin(w)) * 1.1F * a;
        rightShin.xRot += Math.max(0.0F, -Mth.sin(w)) * 1.1F * a;
        hips.y -= Mth.abs(Mth.cos(w)) * 0.9F * a;
        hips.zRot += Mth.cos(w) * 0.05F * a;
        chest.zRot -= Mth.cos(w) * 0.04F * a;
        leftUpperArm.xRot += Mth.cos(w + Mth.PI) * 0.45F * a;
        rightUpperArm.xRot += Mth.cos(w) * 0.45F * a * armFree;
        leftForearm.xRot -= Math.max(0.0F, Mth.cos(w)) * 0.35F * a;
        rightForearm.xRot -= Math.max(0.0F, -Mth.cos(w)) * 0.35F * a * armFree;
        if (crawl > 0.0F) {
            // Flat on its belly it hauls itself along hand over hand: reach, plant, drag the body up
            // to the hand with the elbow high, lift, reach again; the legs shove on the other beat.
            float p = limbSwing * 0.11F;
            float q = p + 0.5F;
            rightUpperArm.xRot += crawl * Anim.loop(p, 0.0F, -0.121F, 0.2F, -0.540F, 0.4F, -0.847F, 0.6F, -0.993F, 0.8F, -0.997F, 1.0F, -0.121F);
            rightUpperArm.yRot += crawl * Anim.loop(p, 0.0F, -0.980F, 0.2F, -0.771F, 0.4F, -0.537F, 0.6F, -0.445F, 0.8F, -0.773F, 1.0F, -0.980F);
            rightUpperArm.zRot += crawl * Anim.loop(p, 0.0F, -0.707F, 0.2F, -0.726F, 0.4F, -0.836F, 0.6F, -1.222F, 0.8F, -0.406F, 1.0F, -0.707F);
            rightForearm.xRot += crawl * Anim.loop(p, 0.0F, 1.174F, 0.2F, 1.878F, 0.4F, 2.439F, 0.6F, 2.833F, 0.8F, 2.026F, 1.0F, 1.174F);
            rightHand.xRot += crawl * Anim.loop(p, 0.0F, -1.322F, 0.2F, -1.174F, 0.4F, -0.935F, 0.6F, -0.750F, 0.8F, -1.870F, 1.0F, -1.322F);
            leftUpperArm.xRot += crawl * Anim.loop(q, 0.0F, -0.121F, 0.2F, -0.540F, 0.4F, -0.847F, 0.6F, -0.993F, 0.8F, -0.997F, 1.0F, -0.121F);
            leftUpperArm.yRot += crawl * Anim.loop(q, 0.0F, 0.980F, 0.2F, 0.771F, 0.4F, 0.537F, 0.6F, 0.445F, 0.8F, 0.773F, 1.0F, 0.980F);
            leftUpperArm.zRot += crawl * Anim.loop(q, 0.0F, 0.707F, 0.2F, 0.726F, 0.4F, 0.836F, 0.6F, 1.222F, 0.8F, 0.406F, 1.0F, 0.707F);
            leftForearm.xRot += crawl * Anim.loop(q, 0.0F, 1.174F, 0.2F, 1.878F, 0.4F, 2.439F, 0.6F, 2.833F, 0.8F, 2.026F, 1.0F, 1.174F);
            leftHand.xRot += crawl * Anim.loop(q, 0.0F, -1.322F, 0.2F, -1.174F, 0.4F, -0.935F, 0.6F, -0.750F, 0.8F, -1.870F, 1.0F, -1.322F);
            float pr = Mth.sin(p * (Mth.PI * 2.0F));
            float kickR = 0.5F + 0.5F * Mth.cos(q * (Mth.PI * 2.0F));
            float kickL = 0.5F + 0.5F * Mth.cos(p * (Mth.PI * 2.0F));
            rightThigh.zRot -= crawl * 0.45F * kickR;
            rightThigh.xRot -= crawl * 0.35F * kickR;
            rightShin.xRot += crawl * 0.8F * kickR;
            leftThigh.zRot += crawl * 0.45F * kickL;
            leftThigh.xRot -= crawl * 0.35F * kickL;
            leftShin.xRot += crawl * 0.8F * kickL;
            hips.zRot += crawl * pr * 0.12F;
            chest.yRot += crawl * pr * 0.1F;
            neck.yRot -= crawl * pr * 0.12F;
            head.zRot -= crawl * pr * 0.1F;
            hips.y += crawl * Mth.abs(Mth.cos(p * (Mth.PI * 2.0F))) * 0.6F;
            // Fingers dig in while the hand is planted and trail while it reaches.
            float digR = Anim.loop(p, 0.0F, 0.9F, 0.6F, 0.9F, 0.75F, -0.2F, 0.95F, -0.2F, 1.0F, 0.9F);
            float digL = Anim.loop(q, 0.0F, 0.9F, 0.6F, 0.9F, 0.75F, -0.2F, 0.95F, -0.2F, 1.0F, 0.9F);
            rightFinger0.xRot += crawl * digR;
            rightFinger1.xRot += crawl * digR;
            rightFinger2.xRot += crawl * digR;
            leftFinger0.xRot += crawl * digL;
            leftFinger1.xRot += crawl * digL;
            leftFinger2.xRot += crawl * digL;
        }

        // ---- the right arm, given over to a gesture
        if (reach > 0.0F) {
            float[] from = scratching ? SCRATCH_TOP : COCK;
            float[] to = scratching ? SCRATCH_END : HIT;
            float[] sFrom = scratching ? S_SCRATCH_TOP : S_COCK;
            float[] sTo = scratching ? S_SCRATCH_END : S_HIT;
            float s = stoop;
            rightUpperArm.xRot += reach * Mth.lerp(s, Mth.lerp(hit, from[0], to[0]), Mth.lerp(hit, sFrom[0], sTo[0]));
            rightUpperArm.yRot += reach * Mth.lerp(s, Mth.lerp(hit, from[1], to[1]), Mth.lerp(hit, sFrom[1], sTo[1]));
            rightUpperArm.zRot += reach * Mth.lerp(s, Mth.lerp(hit, from[2], to[2]), Mth.lerp(hit, sFrom[2], sTo[2]));
            rightForearm.xRot += reach * Mth.lerp(s, Mth.lerp(hit, from[3], to[3]), Mth.lerp(hit, sFrom[3], sTo[3]));
            rightHand.xRot += reach * Mth.lerp(s, Mth.lerp(hit, from[4], to[4]), Mth.lerp(hit, sFrom[4], sTo[4]));
            // A fist to knock with, fingers crooked like hooks to scratch with.
            float curl = scratching ? 0.35F : 1.4F;
            rightFinger0.xRot += reach * curl;
            rightFinger1.xRot += reach * curl;
            rightFinger2.xRot += reach * curl;
            rightThumb.xRot += reach * (scratching ? 0.2F : 0.6F);
            // Its head goes close to the door, an ear to the wood; each blow runs through its body.
            float jolt = scratching ? 0.0F : Math.max(0.0F, hit - 0.6F) * (kind == com.exonoxic.palimpsest.entity.KnockerEntity.GESTURE_POUND ? 0.5F : 0.25F);
            head.zRot += reach * 0.38F * upright;
            neck.xRot += reach * (0.18F + jolt * 0.3F) * upright;
            chest.xRot += reach * jolt * 0.3F;
            head.xRot -= reach * jolt * 0.2F;
            jaw.xRot += reach * (scratching ? 0.25F + hit * 0.15F : 0.06F);
        }
        if (knocking > 0.0F && reach < knocking) jaw.xRot += 0.08F * knocking;

        // ---- cloth and iron move a beat behind the body
        shroudBack.xRot += -Mth.abs(Mth.sin(w)) * 0.1F * a + breath * 0.02F;
        shroudBackLower.xRot += -Mth.abs(Mth.sin(w + 0.4F)) * 0.25F * a + breath * 0.02F;
        shroudFlap.xRot += -Mth.abs(Mth.sin(w + 0.6F)) * 0.18F * a;
        shroudStrip.xRot += -Mth.abs(Mth.sin(w + 1.1F)) * 0.25F * a;
        shroudStrip.zRot += Mth.sin(ageInTicks * 0.05F) * 0.05F;
        ring.xRot += -Mth.sin(w * 2.0F) * 0.3F * a + Mth.sin(ageInTicks * 0.06F) * 0.1F;
        float flex = Mth.sin(ageInTicks * 0.09F) * (1.0F - reach);
        leftFinger0.xRot += Mth.sin(ageInTicks * 0.09F) * 0.12F;
        leftFinger1.xRot += Mth.sin(ageInTicks * 0.09F + 0.8F) * 0.12F;
        leftFinger2.xRot += Mth.sin(ageInTicks * 0.09F + 1.6F) * 0.12F;
        rightFinger0.xRot -= flex * 0.1F;
        rightFinger2.xRot -= Mth.sin(ageInTicks * 0.09F + 1.2F) * 0.1F * (1.0F - reach);

        // ---- states
        if (lunging > 0.0F) {
            float shake = Mth.sin(ageInTicks * 1.7F) * 0.05F;
            jaw.xRot += (0.95F + shake) * lunging;
            ring.xRot += 0.6F * lunging;
            float u = lunging * upright;
            chest.xRot += 0.18F * u;
            neck.xRot -= 0.25F * u;
            head.xRot -= 0.25F * u;
            leftUpperArm.xRot += (-1.35F + shake) * u;
            rightUpperArm.xRot += (-1.35F - shake) * u * armFree;
            leftUpperArm.zRot -= 0.18F * u;
            rightUpperArm.zRot += 0.18F * u * armFree;
            leftForearm.xRot += 0.15F * u;
            rightForearm.xRot += 0.15F * u * armFree;
            leftFinger0.zRot += 0.35F * lunging;
            leftFinger2.zRot -= 0.35F * lunging;
            rightFinger0.zRot -= 0.35F * lunging;
            rightFinger2.zRot += 0.35F * lunging;
        }
        // Going round the house: hunched, head cocked, listening at the walls.
        neck.xRot += 0.28F * searching * upright;
        head.zRot += (0.4F + Mth.sin(ageInTicks * 0.05F) * 0.08F) * searching * (1.0F - reach);
        jaw.xRot += 0.12F * searching;
        neck.xRot += 0.4F * leaving * upright;
        head.xRot += 0.25F * leaving * upright;
        chest.xRot += 0.1F * leaving * upright;
        jaw.xRot += (0.05F + Math.max(0.0F, Mth.sin(ageInTicks * 0.031F)) * 0.12F) * idle;
        if (attackTime > 0.0F) {
            float s = Mth.sin(Mth.sqrt(attackTime) * Mth.PI);
            rightUpperArm.xRot -= 1.1F * s;
            rightForearm.xRot -= 0.6F * s;
            jaw.xRot += 0.4F * s;
        }
        if (crawl > 0.0F) {
            hips.xRot += crawl * 1.17F;
            hips.y += crawl * 18.5F;
            hips.z += crawl * 12.0F;
            leftThigh.xRot += crawl * 0.36F;
            leftThigh.zRot += crawl * -0.25F;
            rightThigh.xRot += crawl * 0.36F;
            rightThigh.zRot += crawl * 0.25F;
            leftShin.xRot += crawl * 0.6F;
            rightShin.xRot += crawl * 0.6F;
            leftFoot.xRot += crawl * -0.9F;
            rightFoot.xRot += crawl * -0.9F;
            neck.xRot += crawl * -1.03F;
            head.xRot += crawl * -0.12F;
            leftUpperArm.xRot += crawl * -2.45F;
            leftUpperArm.zRot += crawl * -0.12F;
            rightUpperArm.xRot += crawl * -2.68F;
            rightUpperArm.zRot += crawl * 0.2F;
            leftForearm.xRot += crawl * -0.35F;
            rightForearm.xRot += crawl * 0.06F;
            leftHand.xRot += crawl * 0.2F;
            rightHand.xRot += crawl * -0.1F;
            shroudBackLower.xRot += crawl * 0.39F;
            shroudFlap.xRot += crawl * 0.34F;
            shroudStrip.xRot += crawl * 0.3F;
        }
        if (stoop > 0.0F) {
            hips.xRot += stoop * 0.8F;
            hips.y += stoop * 7.0F;
            hips.z += stoop * 9.0F;
            leftThigh.xRot += stoop * -1.62F;
            leftThigh.zRot += stoop * -0.08F;
            rightThigh.xRot += stoop * -1.62F;
            rightThigh.zRot += stoop * 0.08F;
            leftShin.xRot += stoop * 1.3F;
            rightShin.xRot += stoop * 1.3F;
            leftFoot.xRot += stoop * -0.62F;
            rightFoot.xRot += stoop * -0.62F;
            neck.xRot += stoop * -0.4F;
            head.xRot += stoop * -0.25F;
            leftUpperArm.xRot += stoop * -1.5F;
            leftUpperArm.zRot += stoop * -0.1F;
            rightUpperArm.xRot += stoop * -1.5F;
            rightUpperArm.zRot += stoop * 0.1F;
            leftForearm.xRot += stoop * 1.45F;
            rightForearm.xRot += stoop * 1.45F;
            leftHand.xRot += stoop * 1.1F;
            rightHand.xRot += stoop * 1.1F;
            shroudBackLower.xRot += stoop * -0.51F;
            shroudFlap.xRot += stoop * -0.35F;
            shroudStrip.xRot += stoop * -0.6F;
        }
    }
}
