package com.exonoxic.palimpsest.client.model;

import com.exonoxic.palimpsest.Palimpsest;
import com.exonoxic.palimpsest.entity.LonghandEntity;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.HierarchicalModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.util.Mth;

/**
 * Generated by tools/gen_models.py from the "longhand" spec. Edit the spec, not this file.
 */
@SuppressWarnings("unused")
public class LonghandModel<T extends LonghandEntity> extends HierarchicalModel<T> {
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(Palimpsest.id("longhand"), "main");
    private final ModelPart root;
    protected final ModelPart pelvis;
    protected final ModelPart leftThigh;
    protected final ModelPart leftShin;
    protected final ModelPart leftPoint;
    protected final ModelPart rightThigh;
    protected final ModelPart rightShin;
    protected final ModelPart rightPoint;
    protected final ModelPart abdomen;
    protected final ModelPart ribcage;
    protected final ModelPart tail0;
    protected final ModelPart tail1;
    protected final ModelPart tail2;
    protected final ModelPart neck;
    protected final ModelPart head;
    protected final ModelPart nibMid;
    protected final ModelPart nibUpper;
    protected final ModelPart nibTip;
    protected final ModelPart feed;
    protected final ModelPart chinDrip;
    protected final ModelPart leftUpperArm;
    protected final ModelPart leftForearm;
    protected final ModelPart leftHand;
    protected final ModelPart leftFinger0;
    protected final ModelPart leftFinger1;
    protected final ModelPart leftFinger2;
    protected final ModelPart leftDrip2;
    protected final ModelPart leftFinger3;
    protected final ModelPart rightUpperArm;
    protected final ModelPart rightForearm;
    protected final ModelPart rightHand;
    protected final ModelPart rightFinger0;
    protected final ModelPart rightFinger1;
    protected final ModelPart rightFinger2;
    protected final ModelPart rightDrip2;
    protected final ModelPart rightFinger3;
    protected final ModelPart ribDrip;

    public LonghandModel(ModelPart root) {
        super(RenderType::entityCutoutNoCull);
        this.root = root;
        this.pelvis = root.getChild("pelvis");
        this.leftThigh = this.pelvis.getChild("left_thigh");
        this.leftShin = this.leftThigh.getChild("left_shin");
        this.leftPoint = this.leftShin.getChild("left_point");
        this.rightThigh = this.pelvis.getChild("right_thigh");
        this.rightShin = this.rightThigh.getChild("right_shin");
        this.rightPoint = this.rightShin.getChild("right_point");
        this.abdomen = this.pelvis.getChild("abdomen");
        this.ribcage = this.abdomen.getChild("ribcage");
        this.tail0 = this.ribcage.getChild("tail_0");
        this.tail1 = this.tail0.getChild("tail_1");
        this.tail2 = this.tail1.getChild("tail_2");
        this.neck = this.ribcage.getChild("neck");
        this.head = this.neck.getChild("head");
        this.nibMid = this.head.getChild("nib_mid");
        this.nibUpper = this.head.getChild("nib_upper");
        this.nibTip = this.head.getChild("nib_tip");
        this.feed = this.head.getChild("feed");
        this.chinDrip = this.head.getChild("chin_drip");
        this.leftUpperArm = this.ribcage.getChild("left_upper_arm");
        this.leftForearm = this.leftUpperArm.getChild("left_forearm");
        this.leftHand = this.leftForearm.getChild("left_hand");
        this.leftFinger0 = this.leftHand.getChild("left_finger_0");
        this.leftFinger1 = this.leftHand.getChild("left_finger_1");
        this.leftFinger2 = this.leftHand.getChild("left_finger_2");
        this.leftDrip2 = this.leftFinger2.getChild("left_drip_2");
        this.leftFinger3 = this.leftHand.getChild("left_finger_3");
        this.rightUpperArm = this.ribcage.getChild("right_upper_arm");
        this.rightForearm = this.rightUpperArm.getChild("right_forearm");
        this.rightHand = this.rightForearm.getChild("right_hand");
        this.rightFinger0 = this.rightHand.getChild("right_finger_0");
        this.rightFinger1 = this.rightHand.getChild("right_finger_1");
        this.rightFinger2 = this.rightHand.getChild("right_finger_2");
        this.rightDrip2 = this.rightFinger2.getChild("right_drip_2");
        this.rightFinger3 = this.rightHand.getChild("right_finger_3");
        this.ribDrip = this.ribcage.getChild("rib_drip");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition pelvisDef = root.addOrReplaceChild("pelvis", CubeListBuilder.create().texOffs(40, 26).addBox(-1.5F, -1.0F, -1.0F, 3.0F, 2.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -1.5F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftThighDef = pelvisDef.addOrReplaceChild("left_thigh", CubeListBuilder.create().texOffs(0, 0).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 13.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(1.1F, 0.5F, 0.0F, -0.04F, 0.0F, 0.03F));
        PartDefinition leftShinDef = leftThighDef.addOrReplaceChild("left_shin", CubeListBuilder.create().texOffs(16, 15).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 10.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 13.0F, 0.0F, 0.1F, 0.0F, 0.0F));
        PartDefinition leftPointDef = leftShinDef.addOrReplaceChild("left_point", CubeListBuilder.create().texOffs(58, 26).addBox(-0.5F, 0.0F, -1.0F, 1.0F, 2.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 10.0F, 0.0F, -0.06F, 0.0F, 0.0F));
        PartDefinition rightThighDef = pelvisDef.addOrReplaceChild("right_thigh", CubeListBuilder.create().texOffs(8, 0).mirror().addBox(-1.0F, 0.0F, -1.0F, 2.0F, 13.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-1.1F, 0.5F, 0.0F, -0.04F, 0.0F, -0.03F));
        PartDefinition rightShinDef = rightThighDef.addOrReplaceChild("right_shin", CubeListBuilder.create().texOffs(20, 15).mirror().addBox(-0.5F, 0.0F, -0.5F, 1.0F, 10.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 13.0F, 0.0F, 0.1F, 0.0F, 0.0F));
        PartDefinition rightPointDef = rightShinDef.addOrReplaceChild("right_point", CubeListBuilder.create().texOffs(0, 34).mirror().addBox(-0.5F, 0.0F, -1.0F, 1.0F, 2.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 10.0F, 0.0F, -0.06F, 0.0F, 0.0F));
        PartDefinition abdomenDef = pelvisDef.addOrReplaceChild("abdomen", CubeListBuilder.create().texOffs(28, 15).addBox(-1.0F, -7.0F, -1.0F, 2.0F, 7.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -1.0F, 0.0F, 0.02F, 0.0F, -0.07F));
        PartDefinition ribcageDef = abdomenDef.addOrReplaceChild("ribcage", CubeListBuilder.create().texOffs(0, 15).addBox(-2.5F, -8.0F, -1.5F, 5.0F, 8.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -7.0F, 0.0F, 0.08F, 0.0F, 0.1F));
        PartDefinition tail0Def = ribcageDef.addOrReplaceChild("tail_0", CubeListBuilder.create().texOffs(32, 0).addBox(-4.0F, 0.0F, 0.0F, 8.0F, 12.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -7.8F, 1.6F, 0.14F, 0.0F, 0.0F));
        PartDefinition tail1Def = tail0Def.addOrReplaceChild("tail_1", CubeListBuilder.create().texOffs(48, 0).addBox(-2.5F, 0.0F, 0.0F, 5.0F, 12.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 12.0F, 0.0F, 0.02F, 0.0F, 0.0F));
        PartDefinition tail2Def = tail1Def.addOrReplaceChild("tail_2", CubeListBuilder.create().texOffs(24, 15).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 11.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 12.0F, 0.0F, -0.04F, 0.0F, 0.0F));
        PartDefinition neckDef = ribcageDef.addOrReplaceChild("neck", CubeListBuilder.create().texOffs(26, 26).addBox(-0.5F, -5.0F, -0.5F, 1.0F, 5.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -8.0F, 0.0F, 0.12F, 0.0F, -0.04F));
        PartDefinition headDef = neckDef.addOrReplaceChild("head", CubeListBuilder.create().texOffs(4, 26).addBox(-2.5F, -3.0F, -1.5F, 5.0F, 3.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -5.0F, 0.0F, -0.08F, 0.0F, 0.18F));
        PartDefinition nibMidDef = headDef.addOrReplaceChild("nib_mid", CubeListBuilder.create().texOffs(30, 26).addBox(-1.5F, -3.0F, -1.0F, 3.0F, 3.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -3.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition nibUpperDef = headDef.addOrReplaceChild("nib_upper", CubeListBuilder.create().texOffs(50, 26).addBox(-1.5F, -3.0F, -0.5F, 3.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -6.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition nibTipDef = headDef.addOrReplaceChild("nib_tip", CubeListBuilder.create().texOffs(6, 34).addBox(-0.5F, -3.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -9.0F, 0.0F, 0.05F, 0.0F, 0.0F));
        PartDefinition feedDef = headDef.addOrReplaceChild("feed", CubeListBuilder.create().texOffs(20, 26).addBox(-1.0F, -5.0F, 0.0F, 2.0F, 5.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -2.0F, 1.0F, -0.06F, 0.0F, 0.0F));
        PartDefinition chinDripDef = headDef.addOrReplaceChild("chin_drip", CubeListBuilder.create().texOffs(22, 34).addBox(-0.5F, 0.0F, 0.0F, 1.0F, 3.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.8F, 0.0F, -1.2F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftUpperArmDef = ribcageDef.addOrReplaceChild("left_upper_arm", CubeListBuilder.create().texOffs(16, 0).addBox(-0.5F, -0.5F, -0.5F, 1.0F, 13.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(2.8F, -7.6F, 0.0F, 0.02F, 0.0F, -0.06F));
        PartDefinition leftForearmDef = leftUpperArmDef.addOrReplaceChild("left_forearm", CubeListBuilder.create().texOffs(20, 0).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 13.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 12.5F, 0.0F, -0.08F, 0.0F, 0.03F));
        PartDefinition leftHandDef = leftForearmDef.addOrReplaceChild("left_hand", CubeListBuilder.create().texOffs(10, 34).addBox(-1.0F, 0.0F, -0.5F, 2.0F, 2.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 13.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftFinger0Def = leftHandDef.addOrReplaceChild("left_finger_0", CubeListBuilder.create().texOffs(52, 15).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 7.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-0.8F, 2.0F, 0.0F, 0.18F, 0.0F, 0.22F));
        PartDefinition leftFinger1Def = leftHandDef.addOrReplaceChild("left_finger_1", CubeListBuilder.create().texOffs(36, 15).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 8.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-0.28F, 2.0F, 0.0F, 0.18F, 0.0F, 0.07F));
        PartDefinition leftFinger2Def = leftHandDef.addOrReplaceChild("left_finger_2", CubeListBuilder.create().texOffs(40, 15).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 8.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.28F, 2.0F, 0.0F, 0.18F, 0.0F, -0.07F));
        PartDefinition leftDrip2Def = leftFinger2Def.addOrReplaceChild("left_drip_2", CubeListBuilder.create().texOffs(26, 34).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 2.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 8.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftFinger3Def = leftHandDef.addOrReplaceChild("left_finger_3", CubeListBuilder.create().texOffs(56, 15).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 7.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.8F, 2.0F, 0.0F, 0.18F, 0.0F, -0.22F));
        PartDefinition rightUpperArmDef = ribcageDef.addOrReplaceChild("right_upper_arm", CubeListBuilder.create().texOffs(24, 0).mirror().addBox(-0.5F, -0.5F, -0.5F, 1.0F, 13.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-2.8F, -7.6F, 0.0F, 0.02F, 0.0F, 0.06F));
        PartDefinition rightForearmDef = rightUpperArmDef.addOrReplaceChild("right_forearm", CubeListBuilder.create().texOffs(28, 0).mirror().addBox(-0.5F, 0.0F, -0.5F, 1.0F, 13.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 12.5F, 0.0F, -0.08F, 0.0F, -0.03F));
        PartDefinition rightHandDef = rightForearmDef.addOrReplaceChild("right_hand", CubeListBuilder.create().texOffs(16, 34).mirror().addBox(-1.0F, 0.0F, -0.5F, 2.0F, 2.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 13.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition rightFinger0Def = rightHandDef.addOrReplaceChild("right_finger_0", CubeListBuilder.create().texOffs(60, 15).mirror().addBox(-0.5F, 0.0F, -0.5F, 1.0F, 7.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-0.8F, 2.0F, 0.0F, 0.18F, 0.0F, -0.22F));
        PartDefinition rightFinger1Def = rightHandDef.addOrReplaceChild("right_finger_1", CubeListBuilder.create().texOffs(44, 15).mirror().addBox(-0.5F, 0.0F, -0.5F, 1.0F, 8.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-0.28F, 2.0F, 0.0F, 0.18F, 0.0F, -0.07F));
        PartDefinition rightFinger2Def = rightHandDef.addOrReplaceChild("right_finger_2", CubeListBuilder.create().texOffs(48, 15).mirror().addBox(-0.5F, 0.0F, -0.5F, 1.0F, 8.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.28F, 2.0F, 0.0F, 0.18F, 0.0F, 0.07F));
        PartDefinition rightDrip2Def = rightFinger2Def.addOrReplaceChild("right_drip_2", CubeListBuilder.create().texOffs(28, 34).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 2.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 8.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition rightFinger3Def = rightHandDef.addOrReplaceChild("right_finger_3", CubeListBuilder.create().texOffs(0, 26).mirror().addBox(-0.5F, 0.0F, -0.5F, 1.0F, 7.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.8F, 2.0F, 0.0F, 0.18F, 0.0F, 0.22F));
        PartDefinition ribDripDef = ribcageDef.addOrReplaceChild("rib_drip", CubeListBuilder.create().texOffs(24, 34).addBox(-0.5F, 0.0F, 0.0F, 1.0F, 3.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-1.5F, 0.0F, -1.6F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    @Override
    public ModelPart root() {
        return root;
    }

    @Override
    public void setupAnim(T entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        root().getAllParts().forEach(ModelPart::resetPose);
        float crawl = entity.squeeze.crawl(ageInTicks - entity.tickCount);
        float stoop = entity.squeeze.stoop(ageInTicks - entity.tickCount);
        if (entity.isFrozen()) {
            // Caught. Every time you look back it is holding a different, wrong pose (or, caught
            // squeezing through something, exactly the shape it was squeezing in).
            if (crawl < 0.05F && stoop < 0.05F) switch (entity.getPoseIndex()) {
                case 0 -> {
                    leftUpperArm.xRot -= 1.35F; rightUpperArm.xRot -= 1.2F;
                    leftForearm.xRot -= 0.25F; rightForearm.xRot -= 0.35F;
                    leftFinger0.zRot += 0.5F; leftFinger3.zRot -= 0.5F; rightFinger0.zRot -= 0.5F; rightFinger3.zRot += 0.5F;
                    head.zRot += 0.45F; neck.xRot -= 0.2F;
                }
                case 1 -> {
                    leftThigh.xRot -= 0.75F; leftShin.xRot += 0.9F; rightThigh.xRot += 0.35F; rightShin.xRot += 0.25F;
                    ribcage.xRot += 0.28F; leftUpperArm.xRot += 0.55F; rightUpperArm.xRot -= 0.85F; rightForearm.xRot -= 0.4F;
                    head.yRot += 0.45F;
                }
                case 2 -> {
                    // The neck snapped sideways; the eye still on you.
                    neck.zRot += 0.55F; head.zRot += 1.3F; head.xRot -= 0.15F;
                    leftUpperArm.zRot -= 0.05F; rightUpperArm.zRot += 0.05F;
                    rightForearm.xRot -= 0.25F;
                }
                case 3 -> {
                    pelvis.y += 9.0F;
                    leftThigh.xRot -= 1.25F; rightThigh.xRot -= 1.1F; leftShin.xRot += 2.1F; rightShin.xRot += 1.95F;
                    leftPoint.xRot -= 0.9F; rightPoint.xRot -= 0.85F;
                    abdomen.xRot += 0.45F; ribcage.xRot += 0.5F; neck.xRot -= 0.6F; head.xRot -= 0.55F;
                    leftUpperArm.xRot -= 0.75F; rightUpperArm.xRot -= 0.7F; leftForearm.xRot += 0.3F; rightForearm.xRot += 0.25F;
                }
                default -> {
                    leftUpperArm.xRot -= 2.85F; rightUpperArm.xRot -= 2.75F;
                    leftUpperArm.zRot -= 0.25F; rightUpperArm.zRot += 0.25F;
                    leftForearm.xRot -= 0.7F; rightForearm.xRot -= 0.75F;
                    leftFinger1.xRot += 0.9F; leftFinger2.xRot += 0.8F; rightFinger1.xRot += 0.85F; rightFinger2.xRot += 0.9F;
                    head.xRot += 0.55F;
                }
            }
        } else {
        head.yRot += netHeadYaw * Mth.DEG_TO_RAD;
        head.xRot += headPitch * Mth.DEG_TO_RAD;
        limbSwingAmount *= 1.0F - crawl;
        // Unwatched, it moves in fast, broken strokes.
        float jerk = Mth.sin(ageInTicks * 2.3F) * 0.06F;
        float w = limbSwing * 0.5F;
        leftThigh.xRot += Mth.cos(w) * 1.0F * limbSwingAmount;
        rightThigh.xRot += Mth.cos(w + Mth.PI) * 1.0F * limbSwingAmount;
        leftShin.xRot += Math.max(0.0F, Mth.sin(w)) * 1.2F * limbSwingAmount;
        rightShin.xRot += Math.max(0.0F, -Mth.sin(w)) * 1.2F * limbSwingAmount;
        leftUpperArm.xRot += Mth.cos(w + Mth.PI) * 0.7F * limbSwingAmount + jerk;
        rightUpperArm.xRot += Mth.cos(w) * 0.7F * limbSwingAmount - jerk;
        leftForearm.xRot -= Math.max(0.0F, Mth.cos(w)) * 0.5F * limbSwingAmount;
        rightForearm.xRot -= Math.max(0.0F, -Mth.cos(w)) * 0.5F * limbSwingAmount;
        ribcage.zRot += jerk * 0.5F;
        head.zRot += Mth.sin(ageInTicks * 0.9F) * 0.05F;
        tail0.xRot += -Mth.abs(Mth.sin(w)) * 0.35F * limbSwingAmount;
        tail1.xRot += Mth.abs(Mth.sin(w + 0.5F)) * 0.25F * limbSwingAmount;
        tail2.xRot += Mth.sin(ageInTicks * 0.2F) * 0.08F;
        for (ModelPart f : new ModelPart[]{leftFinger0, leftFinger1, leftFinger2, leftFinger3}) f.xRot += Mth.sin(ageInTicks * 0.3F) * 0.2F;
        for (ModelPart f : new ModelPart[]{rightFinger0, rightFinger1, rightFinger2, rightFinger3}) f.xRot += Mth.cos(ageInTicks * 0.3F) * 0.2F;
        }
        if (crawl > 0.0F) {
            // Flat out it walks on its hands like something with too many joints: a hand planted far
            // ahead, the elbow rising high over it as the body is dragged up, then the other.
            float p = limbSwing * 0.09F;
            float q = p + 0.5F;
            rightUpperArm.xRot += crawl * Anim.loop(p, 0.0F, -0.156F, 0.2F, -0.384F, 0.4F, -0.539F, 0.6F, -0.562F, 0.8F, -0.840F, 1.0F, -0.156F);
            rightUpperArm.yRot += crawl * Anim.loop(p, 0.0F, -0.573F, 0.2F, -0.538F, 0.4F, -0.515F, 0.6F, -0.262F, 0.8F, -0.625F, 1.0F, -0.573F);
            rightUpperArm.zRot += crawl * Anim.loop(p, 0.0F, -0.559F, 0.2F, -0.651F, 0.4F, -0.845F, 0.6F, -1.410F, 0.8F, -0.344F, 1.0F, -0.559F);
            rightForearm.xRot += crawl * Anim.loop(p, 0.0F, -1.643F, 0.2F, -1.126F, 0.4F, -0.696F, 0.6F, -0.334F, 0.8F, -1.071F, 1.0F, -1.643F);
            rightHand.xRot += crawl * Anim.loop(p, 0.0F, -1.107F, 0.2F, -1.386F, 0.4F, -1.654F, 0.6F, -1.839F, 0.8F, -0.739F, 1.0F, -1.107F);
            leftUpperArm.xRot += crawl * Anim.loop(q, 0.0F, -0.156F, 0.2F, -0.384F, 0.4F, -0.539F, 0.6F, -0.562F, 0.8F, -0.840F, 1.0F, -0.156F);
            leftUpperArm.yRot += crawl * Anim.loop(q, 0.0F, 0.573F, 0.2F, 0.538F, 0.4F, 0.515F, 0.6F, 0.262F, 0.8F, 0.625F, 1.0F, 0.573F);
            leftUpperArm.zRot += crawl * Anim.loop(q, 0.0F, 0.559F, 0.2F, 0.651F, 0.4F, 0.845F, 0.6F, 1.410F, 0.8F, 0.344F, 1.0F, 0.559F);
            leftForearm.xRot += crawl * Anim.loop(q, 0.0F, -1.643F, 0.2F, -1.126F, 0.4F, -0.696F, 0.6F, -0.334F, 0.8F, -1.071F, 1.0F, -1.643F);
            leftHand.xRot += crawl * Anim.loop(q, 0.0F, -1.107F, 0.2F, -1.386F, 0.4F, -1.654F, 0.6F, -1.839F, 0.8F, -0.739F, 1.0F, -1.107F);
            float roll = Mth.sin(p * (Mth.PI * 2.0F));
            float kickR = 0.5F + 0.5F * Mth.cos(q * (Mth.PI * 2.0F));
            float kickL = 0.5F + 0.5F * Mth.cos(p * (Mth.PI * 2.0F));
            rightThigh.zRot -= crawl * 0.35F * kickR;
            rightShin.xRot += crawl * 0.5F * kickR;
            leftThigh.zRot += crawl * 0.35F * kickL;
            leftShin.xRot += crawl * 0.5F * kickL;
            pelvis.zRot += crawl * roll * 0.1F;
            neck.yRot -= crawl * roll * 0.12F;
        }
        if (crawl > 0.0F) {
            pelvis.xRot += crawl * 1.47F;
            pelvis.y += crawl * 22.5F;
            pelvis.z += crawl * 2.0F;
            leftThigh.zRot += crawl * -0.12F;
            rightThigh.zRot += crawl * 0.12F;
            leftShin.xRot += crawl * 0.1F;
            rightShin.xRot += crawl * 0.1F;
            neck.xRot += crawl * -0.34F;
            head.xRot += crawl * -0.52F;
            leftUpperArm.xRot += crawl * -3.64F;
            leftUpperArm.zRot += crawl * -0.25F;
            rightUpperArm.xRot += crawl * -3.5F;
            rightUpperArm.zRot += crawl * 0.25F;
            leftForearm.xRot += crawl * 3.1F;
            rightForearm.xRot += crawl * 3.01F;
            leftHand.xRot += crawl * -3.0F;
            rightHand.xRot += crawl * -3.0F;
            tail0.xRot += crawl * -0.3F;
            tail1.xRot += crawl * 0.15F;
            tail2.xRot += crawl * 0.1F;
        }
        if (stoop > 0.0F) {
            pelvis.xRot += stoop * 2.35F;
            pelvis.z += stoop * 12.0F;
            leftThigh.xRot += stoop * -2.35F;
            rightThigh.xRot += stoop * -2.35F;
            neck.xRot += stoop * 0.23F;
            head.xRot += stoop * -2.42F;
            leftUpperArm.xRot += stoop * -2.47F;
            leftUpperArm.zRot += stoop * -0.15F;
            rightUpperArm.xRot += stoop * -2.47F;
            rightUpperArm.zRot += stoop * 0.15F;
            leftForearm.xRot += stoop * -1.49F;
            rightForearm.xRot += stoop * -1.49F;
            leftHand.xRot += stoop * -0.2F;
            rightHand.xRot += stoop * -0.2F;
            tail0.xRot += stoop * -2.59F;
            tail1.xRot += stoop * -1.6F;
            tail2.xRot += stoop * 0.3F;
        }
    }
}
