package com.exonoxic.palimpsest.client.model;

import com.exonoxic.palimpsest.Palimpsest;
import com.exonoxic.palimpsest.entity.LonghandEntity;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.HierarchicalModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.util.Mth;

/**
 * Generated by tools/gen_models.py from the "longhand" spec. Edit the spec, not this file.
 */
@SuppressWarnings("unused")
public class LonghandModel<T extends LonghandEntity> extends HierarchicalModel<T> {
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(Palimpsest.id("longhand"), "main");
    private final ModelPart root;
    protected final ModelPart leftLeg;
    protected final ModelPart rightLeg;
    protected final ModelPart torso;
    protected final ModelPart head;
    protected final ModelPart leftArm;
    protected final ModelPart leftFingers;
    protected final ModelPart rightArm;
    protected final ModelPart rightFingers;

    public LonghandModel(ModelPart root) {
        super(RenderType::entityCutoutNoCull);
        this.root = root;
        this.leftLeg = root.getChild("left_leg");
        this.rightLeg = root.getChild("right_leg");
        this.torso = root.getChild("torso");
        this.head = this.torso.getChild("head");
        this.leftArm = this.torso.getChild("left_arm");
        this.leftFingers = this.leftArm.getChild("left_fingers");
        this.rightArm = this.torso.getChild("right_arm");
        this.rightFingers = this.rightArm.getChild("right_fingers");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition leftLegDef = root.addOrReplaceChild("left_leg", CubeListBuilder.create().texOffs(8, 0).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 30.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(1.5F, -6.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition rightLegDef = root.addOrReplaceChild("right_leg", CubeListBuilder.create().texOffs(16, 0).mirror().addBox(-1.0F, 0.0F, -1.0F, 2.0F, 30.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-1.5F, -6.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition torsoDef = root.addOrReplaceChild("torso", CubeListBuilder.create().texOffs(24, 0).addBox(-2.5F, -16.0F, -1.5F, 5.0F, 16.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -6.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition headDef = torsoDef.addOrReplaceChild("head", CubeListBuilder.create().texOffs(40, 0).addBox(-2.0F, -10.0F, -2.0F, 4.0F, 10.0F, 4.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -16.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftArmDef = torsoDef.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(0, 0).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 32.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(3.0F, -15.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftFingersDef = leftArmDef.addOrReplaceChild("left_fingers", CubeListBuilder.create().texOffs(56, 0).addBox(-1.0F, 0.0F, -0.5F, 2.0F, 7.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 32.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition rightArmDef = torsoDef.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(4, 0).mirror().addBox(-0.5F, 0.0F, -0.5F, 1.0F, 32.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-3.0F, -15.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition rightFingersDef = rightArmDef.addOrReplaceChild("right_fingers", CubeListBuilder.create().texOffs(0, 33).mirror().addBox(-1.0F, 0.0F, -0.5F, 2.0F, 7.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 32.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    @Override
    public ModelPart root() {
        return root;
    }

    @Override
    public void setupAnim(T entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        root().getAllParts().forEach(ModelPart::resetPose);
        if (entity.isFrozen()) {
            switch (entity.getPoseIndex()) {
                case 0 -> { leftArm.xRot = -1.45F; rightArm.xRot = -1.35F; head.zRot = 0.5F; }
                case 1 -> { head.xRot = -0.8F; leftArm.zRot = -0.9F; rightArm.zRot = 0.9F; }
                case 2 -> { rightArm.xRot = -1.6F; rightArm.yRot = 0.2F; head.yRot = 0.35F; head.zRot = -0.25F; }
                case 3 -> { torso.xRot = 0.65F; head.xRot = -0.9F; leftArm.xRot = -0.5F; rightArm.xRot = -0.45F; }
                default -> { head.yRot = 1.45F; leftArm.zRot = -0.12F; rightArm.zRot = 0.12F; }
            }
            return;
        }
        head.yRot += netHeadYaw * Mth.DEG_TO_RAD;
        head.xRot += headPitch * Mth.DEG_TO_RAD;
        float jerk = Mth.sin(ageInTicks * 2.3F) * 0.06F;
        leftLeg.xRot += Mth.cos(limbSwing * 0.5F) * 1.1F * limbSwingAmount;
        rightLeg.xRot += Mth.cos(limbSwing * 0.5F + Mth.PI) * 1.1F * limbSwingAmount;
        leftArm.xRot += Mth.cos(limbSwing * 0.5F + Mth.PI) * 0.7F * limbSwingAmount + jerk;
        rightArm.xRot += Mth.cos(limbSwing * 0.5F) * 0.7F * limbSwingAmount - jerk;
        torso.zRot += jerk * 0.5F;
        leftFingers.xRot += Mth.sin(ageInTicks * 0.3F) * 0.2F;
        rightFingers.xRot += Mth.cos(ageInTicks * 0.3F) * 0.2F;
    }
}
