package com.exonoxic.palimpsest.client.model;

import com.exonoxic.palimpsest.Palimpsest;
import com.exonoxic.palimpsest.entity.MarginCrawlerEntity;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.HierarchicalModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.util.Mth;

/**
 * Generated by tools/gen_models.py from the "margin_crawler" spec. Edit the spec, not this file.
 */
@SuppressWarnings("unused")
public class MarginCrawlerModel<T extends MarginCrawlerEntity> extends HierarchicalModel<T> {
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(Palimpsest.id("margin_crawler"), "main");
    private final ModelPart root;
    protected final ModelPart slime;
    protected final ModelPart foot;
    protected final ModelPart leftHand0;
    protected final ModelPart leftHand1;
    protected final ModelPart leftHand2;
    protected final ModelPart leftHand3;
    protected final ModelPart rightHand0;
    protected final ModelPart rightHand1;
    protected final ModelPart rightHand2;
    protected final ModelPart rightHand3;
    protected final ModelPart shell;
    protected final ModelPart neck;
    protected final ModelPart head;
    protected final ModelPart visor;
    protected final ModelPart leftStalk;
    protected final ModelPart leftEyeball;
    protected final ModelPart rightStalk;
    protected final ModelPart rightEyeball;
    protected final ModelPart lance;
    protected final ModelPart lanceTip;
    protected final ModelPart pennant;

    public MarginCrawlerModel(ModelPart root) {
        super(RenderType::entityCutoutNoCull);
        this.root = root;
        this.slime = root.getChild("slime");
        this.foot = root.getChild("foot");
        this.leftHand0 = this.foot.getChild("left_hand_0");
        this.leftHand1 = this.foot.getChild("left_hand_1");
        this.leftHand2 = this.foot.getChild("left_hand_2");
        this.leftHand3 = this.foot.getChild("left_hand_3");
        this.rightHand0 = this.foot.getChild("right_hand_0");
        this.rightHand1 = this.foot.getChild("right_hand_1");
        this.rightHand2 = this.foot.getChild("right_hand_2");
        this.rightHand3 = this.foot.getChild("right_hand_3");
        this.shell = this.foot.getChild("shell");
        this.neck = this.foot.getChild("neck");
        this.head = this.neck.getChild("head");
        this.visor = this.head.getChild("visor");
        this.leftStalk = this.head.getChild("left_stalk");
        this.leftEyeball = this.leftStalk.getChild("left_eyeball");
        this.rightStalk = this.head.getChild("right_stalk");
        this.rightEyeball = this.rightStalk.getChild("right_eyeball");
        this.lance = this.head.getChild("lance");
        this.lanceTip = this.lance.getChild("lance_tip");
        this.pennant = this.lance.getChild("pennant");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition slimeDef = root.addOrReplaceChild("slime", CubeListBuilder.create().texOffs(12, 26).addBox(-1.5F, -0.03F, 4.0F, 3.0F, 0.0F, 7.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition footDef = root.addOrReplaceChild("foot", CubeListBuilder.create().texOffs(0, 14).addBox(-2.0F, -2.0F, -5.0F, 4.0F, 2.0F, 10.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftHand0Def = footDef.addOrReplaceChild("left_hand_0", CubeListBuilder.create().texOffs(34, 34).addBox(0.0F, -0.5F, -0.5F, 2.0F, 0.5F, 1.5F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(2.0F, 0.0F, -3.5F, 0.0F, -0.375F, 0.0F));
        PartDefinition leftHand1Def = footDef.addOrReplaceChild("left_hand_1", CubeListBuilder.create().texOffs(41, 34).addBox(0.0F, -0.5F, -0.5F, 2.0F, 0.5F, 1.5F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(2.0F, 0.0F, -1.0F, 0.0F, -0.125F, 0.0F));
        PartDefinition leftHand2Def = footDef.addOrReplaceChild("left_hand_2", CubeListBuilder.create().texOffs(48, 34).addBox(0.0F, -0.5F, -0.5F, 2.0F, 0.5F, 1.5F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(2.0F, 0.0F, 1.5F, 0.0F, 0.125F, 0.0F));
        PartDefinition leftHand3Def = footDef.addOrReplaceChild("left_hand_3", CubeListBuilder.create().texOffs(55, 34).addBox(0.0F, -0.5F, -0.5F, 2.0F, 0.5F, 1.5F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(2.0F, 0.0F, 4.0F, 0.0F, 0.375F, 0.0F));
        PartDefinition rightHand0Def = footDef.addOrReplaceChild("right_hand_0", CubeListBuilder.create().texOffs(0, 38).mirror().addBox(-2.0F, -0.5F, -0.5F, 2.0F, 0.5F, 1.5F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-2.0F, 0.0F, -3.5F, 0.0F, 0.375F, 0.0F));
        PartDefinition rightHand1Def = footDef.addOrReplaceChild("right_hand_1", CubeListBuilder.create().texOffs(7, 38).mirror().addBox(-2.0F, -0.5F, -0.5F, 2.0F, 0.5F, 1.5F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-2.0F, 0.0F, -1.0F, 0.0F, 0.125F, 0.0F));
        PartDefinition rightHand2Def = footDef.addOrReplaceChild("right_hand_2", CubeListBuilder.create().texOffs(14, 38).mirror().addBox(-2.0F, -0.5F, -0.5F, 2.0F, 0.5F, 1.5F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-2.0F, 0.0F, 1.5F, 0.0F, -0.125F, 0.0F));
        PartDefinition rightHand3Def = footDef.addOrReplaceChild("right_hand_3", CubeListBuilder.create().texOffs(21, 38).mirror().addBox(-2.0F, -0.5F, -0.5F, 2.0F, 0.5F, 1.5F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-2.0F, 0.0F, 4.0F, 0.0F, -0.375F, 0.0F));
        PartDefinition shellDef = footDef.addOrReplaceChild("shell", CubeListBuilder.create().texOffs(28, 0).addBox(-3.0F, -7.0F, -3.5F, 6.0F, 7.0F, 7.0F, new CubeDeformation(0.0F)).texOffs(32, 26).addBox(-2.0F, -9.0F, -2.0F, 4.0F, 2.0F, 4.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -2.0F, 1.5F, -0.1F, 0.0F, 0.0F));
        PartDefinition neckDef = footDef.addOrReplaceChild("neck", CubeListBuilder.create().texOffs(0, 26).addBox(-1.5F, -5.0F, -1.5F, 3.0F, 5.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -1.5F, -4.0F, 0.25F, 0.0F, 0.0F));
        PartDefinition headDef = neckDef.addOrReplaceChild("head", CubeListBuilder.create().texOffs(47, 14).addBox(-2.0F, -4.0F, -2.5F, 4.0F, 4.0F, 4.0F, new CubeDeformation(0.0F)).texOffs(28, 14).addBox(-2.5F, -4.5F, -2.0F, 5.0F, 4.5F, 4.5F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -5.0F, -0.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition visorDef = headDef.addOrReplaceChild("visor", CubeListBuilder.create().texOffs(0, 34).addBox(-2.5F, 0.0F, -0.5F, 5.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -4.4F, -2.6F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftStalkDef = headDef.addOrReplaceChild("left_stalk", CubeListBuilder.create().texOffs(54, 26).addBox(-0.5F, -4.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(1.0F, -4.3F, -0.5F, -0.25F, 0.0F, 0.3F));
        PartDefinition leftEyeballDef = leftStalkDef.addOrReplaceChild("left_eyeball", CubeListBuilder.create().texOffs(12, 34).addBox(-1.0F, -2.0F, -1.0F, 2.0F, 2.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -4.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition rightStalkDef = headDef.addOrReplaceChild("right_stalk", CubeListBuilder.create().texOffs(58, 26).addBox(-0.5F, -4.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-1.0F, -4.3F, -0.5F, -0.3F, 0.0F, -0.35F));
        PartDefinition rightEyeballDef = rightStalkDef.addOrReplaceChild("right_eyeball", CubeListBuilder.create().texOffs(20, 34).addBox(-1.0F, -2.0F, -1.0F, 2.0F, 2.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -4.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition lanceDef = headDef.addOrReplaceChild("lance", CubeListBuilder.create().texOffs(0, 0).addBox(-0.5F, -0.5F, -13.0F, 1.0F, 1.0F, 13.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(2.6F, -1.0F, -1.0F, 0.12F, -0.08F, 0.0F));
        PartDefinition lanceTipDef = lanceDef.addOrReplaceChild("lance_tip", CubeListBuilder.create().texOffs(28, 34).addBox(-0.5F, -0.5F, -2.0F, 1.0F, 1.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.0F, -13.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition pennantDef = lanceDef.addOrReplaceChild("pennant", CubeListBuilder.create().texOffs(48, 26).addBox(0.0F, -3.0F, 0.0F, 0.0F, 3.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.0F, -10.5F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    @Override
    public ModelPart root() {
        return root;
    }

    @Override
    public void setupAnim(T entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        root().getAllParts().forEach(ModelPart::resetPose);
        float a = Math.min(1.0F, limbSwingAmount);
        float w = limbSwing * 1.4F;
        neck.xRot += Mth.sin(w) * 0.1F * a;
        head.yRot += netHeadYaw * Mth.DEG_TO_RAD * 0.6F;
        head.xRot += headPitch * Mth.DEG_TO_RAD * 0.5F;
        // It goes along on its little hands, a ripple running down each side.
        leftHand0.yRot += Mth.sin(w) * 0.6F * a;
        leftHand1.yRot += Mth.sin(w - 0.8F) * 0.6F * a;
        leftHand2.yRot += Mth.sin(w - 1.6F) * 0.6F * a;
        leftHand3.yRot += Mth.sin(w - 2.4F) * 0.6F * a;
        rightHand0.yRot -= Mth.sin(w + 0.5F) * 0.6F * a;
        rightHand1.yRot -= Mth.sin(w - 0.3F) * 0.6F * a;
        rightHand2.yRot -= Mth.sin(w - 1.1F) * 0.6F * a;
        rightHand3.yRot -= Mth.sin(w - 1.9F) * 0.6F * a;
        shell.zRot += Mth.sin(w) * 0.05F * a;
        leftStalk.zRot += Mth.sin(ageInTicks * 0.1F) * 0.15F;
        rightStalk.zRot += Mth.sin(ageInTicks * 0.08F + 1.5F) * 0.15F;
        leftStalk.xRot += Mth.sin(ageInTicks * 0.07F) * 0.1F;
        pennant.yRot += Mth.sin(ageInTicks * 0.3F) * 0.3F;
        // The visor lifts when it means to fight, and the face grins out.
        float fighting = Anim.ease(entity, 0, entity.isAggressive(), ageInTicks, 0.2F);
        visor.xRot -= Mth.lerp(fighting, Math.max(0.0F, Mth.sin(ageInTicks * 0.03F) - 0.8F) * 5.0F, 1.3F);
        lance.xRot += Mth.cos(w) * 0.12F * a + 0.1F * fighting;
        if (attackTime > 0.0F) lance.z -= Mth.sin(Mth.sqrt(attackTime) * Mth.PI) * 3.0F;
    }
}
