package com.exonoxic.palimpsest.client.model;

import com.exonoxic.palimpsest.Palimpsest;
import com.exonoxic.palimpsest.entity.MarginCrawlerEntity;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.HierarchicalModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.util.Mth;

/**
 * Generated by tools/gen_models.py from the "margin_crawler" spec. Edit the spec, not this file.
 */
@SuppressWarnings("unused")
public class MarginCrawlerModel<T extends MarginCrawlerEntity> extends HierarchicalModel<T> {
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(Palimpsest.id("margin_crawler"), "main");
    private final ModelPart root;
    protected final ModelPart foot;
    protected final ModelPart shell;
    protected final ModelPart head;
    protected final ModelPart helmet;
    protected final ModelPart lance;

    public MarginCrawlerModel(ModelPart root) {
        super(RenderType::entityCutoutNoCull);
        this.root = root;
        this.foot = root.getChild("foot");
        this.shell = root.getChild("shell");
        this.head = root.getChild("head");
        this.helmet = this.head.getChild("helmet");
        this.lance = this.head.getChild("lance");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition footDef = root.addOrReplaceChild("foot", CubeListBuilder.create().texOffs(0, 0).addBox(-2.0F, -2.0F, -5.0F, 4.0F, 2.0F, 10.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition shellDef = root.addOrReplaceChild("shell", CubeListBuilder.create().texOffs(28, 0).addBox(-3.0F, -6.0F, -3.0F, 6.0F, 6.0F, 6.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 22.0F, 1.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition headDef = root.addOrReplaceChild("head", CubeListBuilder.create().texOffs(38, 12).addBox(-1.5F, -3.0F, -2.0F, 3.0F, 3.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 22.0F, -5.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition helmetDef = headDef.addOrReplaceChild("helmet", CubeListBuilder.create().texOffs(22, 12).addBox(-2.0F, -4.0F, -2.5F, 4.0F, 3.0F, 4.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition lanceDef = headDef.addOrReplaceChild("lance", CubeListBuilder.create().texOffs(0, 12).addBox(0.0F, -0.5F, -10.0F, 1.0F, 1.0F, 10.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(1.5F, -1.0F, -1.0F, 0.15F, -0.1F, 0.0F));
        return LayerDefinition.create(mesh, 64, 32);
    }

    @Override
    public ModelPart root() {
        return root;
    }

    @Override
    public void setupAnim(T entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        root().getAllParts().forEach(ModelPart::resetPose);
        float crawl = Mth.sin(limbSwing * 0.9F) * limbSwingAmount;
        shell.y += crawl * 0.6F;
        head.xRot += headPitch * Mth.DEG_TO_RAD * 0.5F;
        head.yRot += netHeadYaw * Mth.DEG_TO_RAD * 0.5F;
        lance.xRot += Mth.cos(limbSwing * 0.9F) * 0.2F * limbSwingAmount;
        if (attackTime > 0) lance.z -= Mth.sin(Mth.sqrt(attackTime) * Mth.PI) * 3.0F;
    }
}
