package com.exonoxic.palimpsest.client.model;

import net.minecraftforge.client.event.EntityRenderersEvent;

/** Generated by tools/gen_models.py. */
public final class ModModelLayers {
    public static void register(EntityRenderersEvent.RegisterLayerDefinitions event) {
        event.registerLayerDefinition(KnockerModel.LAYER, KnockerModel::createBodyLayer);
        event.registerLayerDefinition(LonghandModel.LAYER, LonghandModel::createBodyLayer);
        event.registerLayerDefinition(SmudgeModel.LAYER, SmudgeModel::createBodyLayer);
        event.registerLayerDefinition(RedactedModel.LAYER, RedactedModel::createBodyLayer);
        event.registerLayerDefinition(RubricatorModel.LAYER, RubricatorModel::createBodyLayer);
        event.registerLayerDefinition(CopyistModel.LAYER, CopyistModel::createBodyLayer);
        event.registerLayerDefinition(InkhoundModel.LAYER, InkhoundModel::createBodyLayer);
        event.registerLayerDefinition(PaleStagModel.LAYER, PaleStagModel::createBodyLayer);
        event.registerLayerDefinition(QuillcrowModel.LAYER, QuillcrowModel::createBodyLayer);
        event.registerLayerDefinition(FoxingMothModel.LAYER, FoxingMothModel::createBodyLayer);
        event.registerLayerDefinition(BlotlingModel.LAYER, BlotlingModel::createBodyLayer);
        event.registerLayerDefinition(MarginCrawlerModel.LAYER, MarginCrawlerModel::createBodyLayer);
        event.registerLayerDefinition(ErratumLegsModel.LAYER, ErratumLegsModel::createBodyLayer);
        event.registerLayerDefinition(PalehandModel.LAYER, PalehandModel::createBodyLayer);
        event.registerLayerDefinition(BookbinderModel.LAYER, BookbinderModel::createBodyLayer);
        event.registerLayerDefinition(RasureModel.LAYER, RasureModel::createBodyLayer);
    }

    private ModModelLayers() {}
}
