package com.exonoxic.palimpsest.client.model;

import com.exonoxic.palimpsest.Palimpsest;
import com.exonoxic.palimpsest.entity.PalehandEntity;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.HierarchicalModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.util.Mth;

/**
 * Generated by tools/gen_models.py from the "palehand" spec. Edit the spec, not this file.
 */
@SuppressWarnings("unused")
public class PalehandModel<T extends PalehandEntity> extends HierarchicalModel<T> {
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(Palimpsest.id("palehand"), "main");
    private final ModelPart root;
    protected final ModelPart wrist;
    protected final ModelPart palm;
    protected final ModelPart finger0;
    protected final ModelPart finger01;
    protected final ModelPart finger02;
    protected final ModelPart finger03;
    protected final ModelPart finger1;
    protected final ModelPart finger11;
    protected final ModelPart finger12;
    protected final ModelPart finger13;
    protected final ModelPart finger2;
    protected final ModelPart finger21;
    protected final ModelPart finger22;
    protected final ModelPart finger23;
    protected final ModelPart finger3;
    protected final ModelPart finger31;
    protected final ModelPart finger32;
    protected final ModelPart finger33;
    protected final ModelPart finger4;
    protected final ModelPart finger41;
    protected final ModelPart finger42;
    protected final ModelPart finger43;
    protected final ModelPart thumb;
    protected final ModelPart thumb1;
    protected final ModelPart thumb2;

    public PalehandModel(ModelPart root) {
        super(RenderType::entityCutoutNoCull);
        this.root = root;
        this.wrist = root.getChild("wrist");
        this.palm = this.wrist.getChild("palm");
        this.finger0 = this.palm.getChild("finger_0");
        this.finger01 = this.finger0.getChild("finger_0_1");
        this.finger02 = this.finger01.getChild("finger_0_2");
        this.finger03 = this.finger02.getChild("finger_0_3");
        this.finger1 = this.palm.getChild("finger_1");
        this.finger11 = this.finger1.getChild("finger_1_1");
        this.finger12 = this.finger11.getChild("finger_1_2");
        this.finger13 = this.finger12.getChild("finger_1_3");
        this.finger2 = this.palm.getChild("finger_2");
        this.finger21 = this.finger2.getChild("finger_2_1");
        this.finger22 = this.finger21.getChild("finger_2_2");
        this.finger23 = this.finger22.getChild("finger_2_3");
        this.finger3 = this.palm.getChild("finger_3");
        this.finger31 = this.finger3.getChild("finger_3_1");
        this.finger32 = this.finger31.getChild("finger_3_2");
        this.finger33 = this.finger32.getChild("finger_3_3");
        this.finger4 = this.palm.getChild("finger_4");
        this.finger41 = this.finger4.getChild("finger_4_1");
        this.finger42 = this.finger41.getChild("finger_4_2");
        this.finger43 = this.finger42.getChild("finger_4_3");
        this.thumb = this.palm.getChild("thumb");
        this.thumb1 = this.thumb.getChild("thumb_1");
        this.thumb2 = this.thumb1.getChild("thumb_2");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition wristDef = root.addOrReplaceChild("wrist", CubeListBuilder.create().texOffs(0, 0).addBox(-3.5F, -12.0F, -2.5F, 7.0F, 16.0F, 5.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition palmDef = wristDef.addOrReplaceChild("palm", CubeListBuilder.create().texOffs(24, 0).addBox(-5.0F, -9.0F, -2.0F, 10.0F, 9.0F, 4.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition finger0Def = palmDef.addOrReplaceChild("finger_0", CubeListBuilder.create().texOffs(24, 21).addBox(-1.0F, -5.0F, -1.0F, 2.0F, 5.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-4.0F, -9.0F, 0.0F, 0.12F, 0.0F, -0.3F));
        PartDefinition finger01Def = finger0Def.addOrReplaceChild("finger_0_1", CubeListBuilder.create().texOffs(8, 29).addBox(-1.0F, -4.0F, -1.0F, 2.0F, 4.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -5.0F, 0.0F, 0.18F, 0.0F, 0.0F));
        PartDefinition finger02Def = finger01Def.addOrReplaceChild("finger_0_2", CubeListBuilder.create().texOffs(16, 29).addBox(-1.0F, -4.0F, -1.0F, 2.0F, 4.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -4.0F, 0.0F, 0.24F, 0.0F, 0.0F));
        PartDefinition finger03Def = finger02Def.addOrReplaceChild("finger_0_3", CubeListBuilder.create().texOffs(0, 36).addBox(-1.0F, -3.0F, -1.0F, 2.0F, 3.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -4.0F, 0.0F, 0.3F, 0.0F, 0.0F));
        PartDefinition finger1Def = palmDef.addOrReplaceChild("finger_1", CubeListBuilder.create().texOffs(52, 0).addBox(-1.0F, -6.0F, -1.0F, 2.0F, 6.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-2.0F, -9.0F, 0.0F, 0.12F, 0.0F, -0.12F));
        PartDefinition finger11Def = finger1Def.addOrReplaceChild("finger_1_1", CubeListBuilder.create().texOffs(32, 21).addBox(-1.0F, -5.0F, -1.0F, 2.0F, 5.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -6.0F, 0.0F, 0.18F, 0.0F, 0.0F));
        PartDefinition finger12Def = finger11Def.addOrReplaceChild("finger_1_2", CubeListBuilder.create().texOffs(24, 29).addBox(-1.0F, -4.0F, -1.0F, 2.0F, 4.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -5.0F, 0.0F, 0.24F, 0.0F, 0.0F));
        PartDefinition finger13Def = finger12Def.addOrReplaceChild("finger_1_3", CubeListBuilder.create().texOffs(8, 36).addBox(-1.0F, -3.0F, -1.0F, 2.0F, 3.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -4.0F, 0.0F, 0.3F, 0.0F, 0.0F));
        PartDefinition finger2Def = palmDef.addOrReplaceChild("finger_2", CubeListBuilder.create().texOffs(0, 21).addBox(-1.0F, -6.0F, -1.0F, 2.0F, 6.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -9.0F, 0.0F, 0.12F, 0.0F, 0.02F));
        PartDefinition finger21Def = finger2Def.addOrReplaceChild("finger_2_1", CubeListBuilder.create().texOffs(40, 21).addBox(-1.0F, -5.0F, -1.0F, 2.0F, 5.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -6.0F, 0.0F, 0.18F, 0.0F, 0.0F));
        PartDefinition finger22Def = finger21Def.addOrReplaceChild("finger_2_2", CubeListBuilder.create().texOffs(48, 21).addBox(-1.0F, -5.0F, -1.0F, 2.0F, 5.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -5.0F, 0.0F, 0.24F, 0.0F, 0.0F));
        PartDefinition finger23Def = finger22Def.addOrReplaceChild("finger_2_3", CubeListBuilder.create().texOffs(32, 29).addBox(-1.0F, -4.0F, -1.0F, 2.0F, 4.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -5.0F, 0.0F, 0.3F, 0.0F, 0.0F));
        PartDefinition finger3Def = palmDef.addOrReplaceChild("finger_3", CubeListBuilder.create().texOffs(8, 21).addBox(-1.0F, -6.0F, -1.0F, 2.0F, 6.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(2.0F, -9.0F, 0.0F, 0.12F, 0.0F, 0.14F));
        PartDefinition finger31Def = finger3Def.addOrReplaceChild("finger_3_1", CubeListBuilder.create().texOffs(56, 21).addBox(-1.0F, -5.0F, -1.0F, 2.0F, 5.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -6.0F, 0.0F, 0.18F, 0.0F, 0.0F));
        PartDefinition finger32Def = finger31Def.addOrReplaceChild("finger_3_2", CubeListBuilder.create().texOffs(40, 29).addBox(-1.0F, -4.0F, -1.0F, 2.0F, 4.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -5.0F, 0.0F, 0.24F, 0.0F, 0.0F));
        PartDefinition finger33Def = finger32Def.addOrReplaceChild("finger_3_3", CubeListBuilder.create().texOffs(16, 36).addBox(-1.0F, -3.0F, -1.0F, 2.0F, 3.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -4.0F, 0.0F, 0.3F, 0.0F, 0.0F));
        PartDefinition finger4Def = palmDef.addOrReplaceChild("finger_4", CubeListBuilder.create().texOffs(0, 29).addBox(-1.0F, -5.0F, -1.0F, 2.0F, 5.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(4.0F, -9.0F, 0.0F, 0.12F, 0.0F, 0.32F));
        PartDefinition finger41Def = finger4Def.addOrReplaceChild("finger_4_1", CubeListBuilder.create().texOffs(48, 29).addBox(-1.0F, -4.0F, -1.0F, 2.0F, 4.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -5.0F, 0.0F, 0.18F, 0.0F, 0.0F));
        PartDefinition finger42Def = finger41Def.addOrReplaceChild("finger_4_2", CubeListBuilder.create().texOffs(24, 36).addBox(-1.0F, -3.0F, -1.0F, 2.0F, 3.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -4.0F, 0.0F, 0.24F, 0.0F, 0.0F));
        PartDefinition finger43Def = finger42Def.addOrReplaceChild("finger_4_3", CubeListBuilder.create().texOffs(32, 36).addBox(-1.0F, -3.0F, -1.0F, 2.0F, 3.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -3.0F, 0.0F, 0.3F, 0.0F, 0.0F));
        PartDefinition thumbDef = palmDef.addOrReplaceChild("thumb", CubeListBuilder.create().texOffs(16, 21).addBox(-1.0F, -6.0F, -1.0F, 2.0F, 6.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-5.0F, -2.0F, 0.0F, -0.3F, 0.0F, -0.95F));
        PartDefinition thumb1Def = thumbDef.addOrReplaceChild("thumb_1", CubeListBuilder.create().texOffs(56, 29).addBox(-1.0F, -4.0F, -1.0F, 2.0F, 4.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -6.0F, 0.0F, 0.0F, 0.0F, 0.25F));
        PartDefinition thumb2Def = thumb1Def.addOrReplaceChild("thumb_2", CubeListBuilder.create().texOffs(40, 36).addBox(-1.0F, -3.0F, -1.0F, 2.0F, 3.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -4.0F, 0.0F, 0.0F, 0.0F, 0.2F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    @Override
    public ModelPart root() {
        return root;
    }

    @Override
    public void setupAnim(T entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        root().getAllParts().forEach(ModelPart::resetPose);
        float t = ageInTicks * 0.045F;
        float c0 = Mth.sin(t + 0.0F);
        finger0.xRot += 0.12F + c0 * 0.3F;
        finger01.xRot += 0.2F + c0 * 0.34F;
        finger02.xRot += 0.2F + c0 * 0.40F;
        finger03.xRot += 0.2F + c0 * 0.46F;
        float c1 = Mth.sin(t + 0.7F);
        finger1.xRot += 0.12F + c1 * 0.3F;
        finger11.xRot += 0.2F + c1 * 0.34F;
        finger12.xRot += 0.2F + c1 * 0.40F;
        finger13.xRot += 0.2F + c1 * 0.46F;
        float c2 = Mth.sin(t + 1.4F);
        finger2.xRot += 0.12F + c2 * 0.3F;
        finger21.xRot += 0.2F + c2 * 0.34F;
        finger22.xRot += 0.2F + c2 * 0.40F;
        finger23.xRot += 0.2F + c2 * 0.46F;
        float c3 = Mth.sin(t + 2.1F);
        finger3.xRot += 0.12F + c3 * 0.3F;
        finger31.xRot += 0.2F + c3 * 0.34F;
        finger32.xRot += 0.2F + c3 * 0.40F;
        finger33.xRot += 0.2F + c3 * 0.46F;
        float c4 = Mth.sin(t + 2.8F);
        finger4.xRot += 0.12F + c4 * 0.3F;
        finger41.xRot += 0.2F + c4 * 0.34F;
        finger42.xRot += 0.2F + c4 * 0.40F;
        finger43.xRot += 0.2F + c4 * 0.46F;
        thumb.zRot += Mth.sin(t * 0.7F) * 0.15F;
        thumb1.zRot += Mth.sin(t * 0.7F + 0.5F) * 0.2F;
        palm.xRot += Mth.sin(t * 0.5F) * 0.08F;
        wrist.zRot += Mth.sin(ageInTicks * 0.02F) * 0.06F;
    }
}
