package com.exonoxic.palimpsest.client.model;

import com.exonoxic.palimpsest.Palimpsest;
import com.exonoxic.palimpsest.entity.PaleStagEntity;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.HierarchicalModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.util.Mth;

/**
 * Generated by tools/gen_models.py from the "pale_stag" spec. Edit the spec, not this file.
 */
@SuppressWarnings("unused")
public class PaleStagModel<T extends PaleStagEntity> extends HierarchicalModel<T> {
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(Palimpsest.id("pale_stag"), "main");
    private final ModelPart root;
    protected final ModelPart torso;
    protected final ModelPart neck;
    protected final ModelPart head;
    protected final ModelPart leftAntler;
    protected final ModelPart leftAntlerBrow;
    protected final ModelPart leftAntlerTineA;
    protected final ModelPart leftAntlerDripA;
    protected final ModelPart leftAntlerBeam;
    protected final ModelPart leftAntlerTineB;
    protected final ModelPart leftAntlerTineC;
    protected final ModelPart leftAntlerTineD;
    protected final ModelPart leftAntlerTineE;
    protected final ModelPart rightAntler;
    protected final ModelPart rightAntlerBrow;
    protected final ModelPart rightAntlerTineA;
    protected final ModelPart rightAntlerDripA;
    protected final ModelPart rightAntlerBeam;
    protected final ModelPart rightAntlerTineB;
    protected final ModelPart rightAntlerTineC;
    protected final ModelPart rightAntlerTineD;
    protected final ModelPart rightAntlerTineE;
    protected final ModelPart frontLeftLeg;
    protected final ModelPart frontLeftCannon;
    protected final ModelPart frontLeftHoof;
    protected final ModelPart frontRightLeg;
    protected final ModelPart frontRightCannon;
    protected final ModelPart frontRightHoof;
    protected final ModelPart haunch;
    protected final ModelPart hindLeftLeg;
    protected final ModelPart hindLeftHock;
    protected final ModelPart hindLeftCannon;
    protected final ModelPart hindLeftHoof;
    protected final ModelPart hindRightLeg;
    protected final ModelPart hindRightHock;
    protected final ModelPart hindRightCannon;
    protected final ModelPart hindRightHoof;
    protected final ModelPart tail;

    public PaleStagModel(ModelPart root) {
        super(RenderType::entityCutoutNoCull);
        this.root = root;
        this.torso = root.getChild("torso");
        this.neck = this.torso.getChild("neck");
        this.head = this.neck.getChild("head");
        this.leftAntler = this.head.getChild("left_antler");
        this.leftAntlerBrow = this.leftAntler.getChild("left_antler_brow");
        this.leftAntlerTineA = this.leftAntler.getChild("left_antler_tine_a");
        this.leftAntlerDripA = this.leftAntlerTineA.getChild("left_antler_drip_a");
        this.leftAntlerBeam = this.leftAntler.getChild("left_antler_beam");
        this.leftAntlerTineB = this.leftAntlerBeam.getChild("left_antler_tine_b");
        this.leftAntlerTineC = this.leftAntlerBeam.getChild("left_antler_tine_c");
        this.leftAntlerTineD = this.leftAntlerBeam.getChild("left_antler_tine_d");
        this.leftAntlerTineE = this.leftAntlerTineD.getChild("left_antler_tine_e");
        this.rightAntler = this.head.getChild("right_antler");
        this.rightAntlerBrow = this.rightAntler.getChild("right_antler_brow");
        this.rightAntlerTineA = this.rightAntler.getChild("right_antler_tine_a");
        this.rightAntlerDripA = this.rightAntlerTineA.getChild("right_antler_drip_a");
        this.rightAntlerBeam = this.rightAntler.getChild("right_antler_beam");
        this.rightAntlerTineB = this.rightAntlerBeam.getChild("right_antler_tine_b");
        this.rightAntlerTineC = this.rightAntlerBeam.getChild("right_antler_tine_c");
        this.rightAntlerTineD = this.rightAntlerBeam.getChild("right_antler_tine_d");
        this.rightAntlerTineE = this.rightAntlerTineD.getChild("right_antler_tine_e");
        this.frontLeftLeg = this.torso.getChild("front_left_leg");
        this.frontLeftCannon = this.frontLeftLeg.getChild("front_left_cannon");
        this.frontLeftHoof = this.frontLeftCannon.getChild("front_left_hoof");
        this.frontRightLeg = this.torso.getChild("front_right_leg");
        this.frontRightCannon = this.frontRightLeg.getChild("front_right_cannon");
        this.frontRightHoof = this.frontRightCannon.getChild("front_right_hoof");
        this.haunch = this.torso.getChild("haunch");
        this.hindLeftLeg = this.haunch.getChild("hind_left_leg");
        this.hindLeftHock = this.hindLeftLeg.getChild("hind_left_hock");
        this.hindLeftCannon = this.hindLeftHock.getChild("hind_left_cannon");
        this.hindLeftHoof = this.hindLeftCannon.getChild("hind_left_hoof");
        this.hindRightLeg = this.haunch.getChild("hind_right_leg");
        this.hindRightHock = this.hindRightLeg.getChild("hind_right_hock");
        this.hindRightCannon = this.hindRightHock.getChild("hind_right_cannon");
        this.hindRightHoof = this.hindRightCannon.getChild("hind_right_hoof");
        this.tail = this.haunch.getChild("tail");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition torsoDef = root.addOrReplaceChild("torso", CubeListBuilder.create().texOffs(0, 0).addBox(-3.0F, -3.0F, -8.0F, 6.0F, 7.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 5.5F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition neckDef = torsoDef.addOrReplaceChild("neck", CubeListBuilder.create().texOffs(28, 0).addBox(-1.5F, -10.0F, -1.5F, 3.0F, 11.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -1.5F, -7.0F, 0.42F, 0.0F, 0.0F));
        PartDefinition headDef = neckDef.addOrReplaceChild("head", CubeListBuilder.create().texOffs(28, 15).addBox(-2.0F, -3.0F, -3.5F, 4.0F, 4.0F, 5.0F, new CubeDeformation(0.0F)).texOffs(8, 25).addBox(-1.5F, -2.0F, -7.5F, 3.0F, 3.0F, 4.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -10.0F, 0.0F, -0.3F, 0.0F, 0.0F));
        PartDefinition leftAntlerDef = headDef.addOrReplaceChild("left_antler", CubeListBuilder.create().texOffs(0, 25).addBox(-0.5F, -7.0F, -0.5F, 1.0F, 7.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(1.3F, -3.0F, -0.5F, -0.35F, 0.25F, 0.45F));
        PartDefinition leftAntlerBrowDef = leftAntlerDef.addOrReplaceChild("left_antler_brow", CubeListBuilder.create().texOffs(54, 25).addBox(-0.5F, -4.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -1.5F, 0.0F, -1.1F, 0.0F, -0.35F));
        PartDefinition leftAntlerTineADef = leftAntlerDef.addOrReplaceChild("left_antler_tine_a", CubeListBuilder.create().texOffs(58, 25).addBox(-0.5F, -4.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -4.5F, 0.0F, -0.9F, 0.0F, 0.3F));
        PartDefinition leftAntlerDripADef = leftAntlerTineADef.addOrReplaceChild("left_antler_drip_a", CubeListBuilder.create().texOffs(32, 33).addBox(0.0F, 0.0F, -0.5F, 0.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -3.2F, -0.5F, 0.9F, 0.0F, 0.0F));
        PartDefinition leftAntlerBeamDef = leftAntlerDef.addOrReplaceChild("left_antler_beam", CubeListBuilder.create().texOffs(22, 25).addBox(-0.5F, -6.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -7.0F, 0.0F, -0.35F, 0.0F, 0.35F));
        PartDefinition leftAntlerTineBDef = leftAntlerBeamDef.addOrReplaceChild("left_antler_tine_b", CubeListBuilder.create().texOffs(0, 33).addBox(-0.5F, -4.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -3.0F, 0.0F, -0.8F, 0.0F, -0.45F));
        PartDefinition leftAntlerTineCDef = leftAntlerBeamDef.addOrReplaceChild("left_antler_tine_c", CubeListBuilder.create().texOffs(4, 33).addBox(-0.5F, -4.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -6.0F, 0.0F, 0.25F, 0.0F, 0.5F));
        PartDefinition leftAntlerTineDDef = leftAntlerBeamDef.addOrReplaceChild("left_antler_tine_d", CubeListBuilder.create().texOffs(46, 25).addBox(-0.5F, -5.0F, -0.5F, 1.0F, 5.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -6.0F, 0.0F, -0.6F, 0.0F, -0.3F));
        PartDefinition leftAntlerTineEDef = leftAntlerTineDDef.addOrReplaceChild("left_antler_tine_e", CubeListBuilder.create().texOffs(24, 33).addBox(-0.5F, -3.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -5.0F, 0.0F, 0.5F, 0.0F, 0.4F));
        PartDefinition rightAntlerDef = headDef.addOrReplaceChild("right_antler", CubeListBuilder.create().texOffs(4, 25).addBox(-0.5F, -7.0F, -0.5F, 1.0F, 7.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-1.3F, -3.0F, -0.5F, -0.23F, -0.175F, -0.38F));
        PartDefinition rightAntlerBrowDef = rightAntlerDef.addOrReplaceChild("right_antler_brow", CubeListBuilder.create().texOffs(8, 33).addBox(-0.5F, -4.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -1.5F, 0.0F, -1.1F, 0.0F, 0.35F));
        PartDefinition rightAntlerTineADef = rightAntlerDef.addOrReplaceChild("right_antler_tine_a", CubeListBuilder.create().texOffs(12, 33).addBox(-0.5F, -4.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -4.5F, 0.0F, -0.9F, 0.0F, -0.3F));
        PartDefinition rightAntlerDripADef = rightAntlerTineADef.addOrReplaceChild("right_antler_drip_a", CubeListBuilder.create().texOffs(34, 33).addBox(0.0F, 0.0F, -0.5F, 0.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -3.2F, -0.5F, 0.9F, 0.0F, 0.0F));
        PartDefinition rightAntlerBeamDef = rightAntlerDef.addOrReplaceChild("right_antler_beam", CubeListBuilder.create().texOffs(26, 25).addBox(-0.5F, -6.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -7.0F, 0.0F, -0.35F, 0.0F, -0.35F));
        PartDefinition rightAntlerTineBDef = rightAntlerBeamDef.addOrReplaceChild("right_antler_tine_b", CubeListBuilder.create().texOffs(16, 33).addBox(-0.5F, -4.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -3.0F, 0.0F, -0.8F, 0.0F, 0.45F));
        PartDefinition rightAntlerTineCDef = rightAntlerBeamDef.addOrReplaceChild("right_antler_tine_c", CubeListBuilder.create().texOffs(20, 33).addBox(-0.5F, -4.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -6.0F, 0.0F, 0.25F, 0.0F, -0.5F));
        PartDefinition rightAntlerTineDDef = rightAntlerBeamDef.addOrReplaceChild("right_antler_tine_d", CubeListBuilder.create().texOffs(50, 25).addBox(-0.5F, -5.0F, -0.5F, 1.0F, 5.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -6.0F, 0.0F, -0.6F, 0.0F, 0.3F));
        PartDefinition rightAntlerTineEDef = rightAntlerTineDDef.addOrReplaceChild("right_antler_tine_e", CubeListBuilder.create().texOffs(28, 33).addBox(-0.5F, -3.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -5.0F, 0.0F, 0.5F, 0.0F, -0.4F));
        PartDefinition frontLeftLegDef = torsoDef.addOrReplaceChild("front_left_leg", CubeListBuilder.create().texOffs(46, 15).addBox(-1.0F, -0.5F, -1.2F, 2.0F, 6.0F, 2.4F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(2.1F, 2.0F, -5.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition frontLeftCannonDef = frontLeftLegDef.addOrReplaceChild("front_left_cannon", CubeListBuilder.create().texOffs(20, 15).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 9.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 5.5F, 0.0F, 0.02F, 0.0F, 0.0F));
        PartDefinition frontLeftHoofDef = frontLeftCannonDef.addOrReplaceChild("front_left_hoof", CubeListBuilder.create().texOffs(36, 33).addBox(-0.5F, 0.0F, -1.2F, 1.0F, 1.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 9.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition frontRightLegDef = torsoDef.addOrReplaceChild("front_right_leg", CubeListBuilder.create().texOffs(55, 15).mirror().addBox(-1.0F, -0.5F, -1.2F, 2.0F, 6.0F, 2.4F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-2.1F, 2.0F, -5.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition frontRightCannonDef = frontRightLegDef.addOrReplaceChild("front_right_cannon", CubeListBuilder.create().texOffs(24, 15).mirror().addBox(-0.5F, 0.0F, -0.5F, 1.0F, 9.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 5.5F, 0.0F, 0.02F, 0.0F, 0.0F));
        PartDefinition frontRightHoofDef = frontRightCannonDef.addOrReplaceChild("front_right_hoof", CubeListBuilder.create().texOffs(42, 33).mirror().addBox(-0.5F, 0.0F, -1.2F, 1.0F, 1.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 9.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition haunchDef = torsoDef.addOrReplaceChild("haunch", CubeListBuilder.create().texOffs(40, 0).addBox(-2.5F, -1.5F, 0.0F, 5.0F, 5.0F, 7.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -1.0F, 0.0F, -0.06F, 0.0F, 0.0F));
        PartDefinition hindLeftLegDef = haunchDef.addOrReplaceChild("hind_left_leg", CubeListBuilder.create().texOffs(0, 15).addBox(-1.0F, -1.0F, -1.5F, 2.0F, 7.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(2.0F, 1.0F, 4.5F, -0.3F, 0.0F, 0.0F));
        PartDefinition hindLeftHockDef = hindLeftLegDef.addOrReplaceChild("hind_left_hock", CubeListBuilder.create().texOffs(30, 25).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 6.0F, 0.3F, 0.85F, 0.0F, 0.0F));
        PartDefinition hindLeftCannonDef = hindLeftHockDef.addOrReplaceChild("hind_left_cannon", CubeListBuilder.create().texOffs(34, 25).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 6.0F, 0.0F, -0.55F, 0.0F, 0.0F));
        PartDefinition hindLeftHoofDef = hindLeftCannonDef.addOrReplaceChild("hind_left_hoof", CubeListBuilder.create().texOffs(48, 33).addBox(-0.5F, 0.0F, -1.2F, 1.0F, 1.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 6.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition hindRightLegDef = haunchDef.addOrReplaceChild("hind_right_leg", CubeListBuilder.create().texOffs(10, 15).mirror().addBox(-1.0F, -1.0F, -1.5F, 2.0F, 7.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-2.0F, 1.0F, 4.5F, -0.3F, 0.0F, 0.0F));
        PartDefinition hindRightHockDef = hindRightLegDef.addOrReplaceChild("hind_right_hock", CubeListBuilder.create().texOffs(38, 25).mirror().addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 6.0F, 0.3F, 0.85F, 0.0F, 0.0F));
        PartDefinition hindRightCannonDef = hindRightHockDef.addOrReplaceChild("hind_right_cannon", CubeListBuilder.create().texOffs(42, 25).mirror().addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 6.0F, 0.0F, -0.55F, 0.0F, 0.0F));
        PartDefinition hindRightHoofDef = hindRightCannonDef.addOrReplaceChild("hind_right_hoof", CubeListBuilder.create().texOffs(54, 33).mirror().addBox(-0.5F, 0.0F, -1.2F, 1.0F, 1.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 6.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition tailDef = haunchDef.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(60, 33).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 3.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -1.0F, 7.0F, 0.5F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    @Override
    public ModelPart root() {
        return root;
    }

    @Override
    public void setupAnim(T entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        root().getAllParts().forEach(ModelPart::resetPose);
        float a = Math.min(1.0F, limbSwingAmount);
        float w = limbSwing * 0.5F;
        // It holds itself dead still and turns only its blank face to follow you: the neck does
        // most of the turning, then the head, further than a neck should allow.
        neck.yRot += netHeadYaw * Mth.DEG_TO_RAD * 0.55F;
        head.yRot += netHeadYaw * Mth.DEG_TO_RAD * 0.45F;
        head.xRot += headPitch * Mth.DEG_TO_RAD * 0.7F;
        // Now and then the head tips over sideways, and stays there a moment.
        float tip = Mth.sin(ageInTicks * 0.017F);
        head.zRot += tip > 0.8F ? (tip - 0.8F) * 4.0F : 0.0F;
        torso.xRot += Mth.sin(ageInTicks * 0.04F) * 0.01F;
        frontLeftLeg.xRot += Mth.cos(w) * 0.9F * a;
        frontRightLeg.xRot += Mth.cos(w + Mth.PI) * 0.9F * a;
        frontLeftCannon.xRot -= Math.max(0.0F, Mth.sin(w)) * 0.9F * a;
        frontRightCannon.xRot -= Math.max(0.0F, -Mth.sin(w)) * 0.9F * a;
        hindLeftLeg.xRot += Mth.cos(w + Mth.PI) * 0.8F * a;
        hindRightLeg.xRot += Mth.cos(w) * 0.8F * a;
        hindLeftHock.xRot += Math.max(0.0F, Mth.sin(w)) * 0.5F * a;
        hindRightHock.xRot += Math.max(0.0F, -Mth.sin(w)) * 0.5F * a;
        torso.y -= Mth.abs(Mth.cos(w)) * 1.2F * a;
        neck.xRot -= Mth.cos(w * 2.0F) * 0.06F * a;
        tail.xRot += a * 0.6F;
        leftAntlerDripA.zRot += Mth.sin(ageInTicks * 0.09F) * 0.15F;
        rightAntlerDripA.zRot += Mth.sin(ageInTicks * 0.08F + 1.3F) * 0.15F;
    }
}
