package com.exonoxic.palimpsest.client.model;

import com.exonoxic.palimpsest.Palimpsest;
import com.exonoxic.palimpsest.entity.PalehandEntity;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.HierarchicalModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.util.Mth;

/**
 * Generated by tools/gen_models.py from the "palehand" spec. Edit the spec, not this file.
 */
@SuppressWarnings("unused")
public class PalehandModel<T extends PalehandEntity> extends HierarchicalModel<T> {
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(Palimpsest.id("palehand"), "main");
    private final ModelPart root;
    protected final ModelPart wrist;
    protected final ModelPart palm;
    protected final ModelPart finger0;
    protected final ModelPart finger0Tip;
    protected final ModelPart finger1;
    protected final ModelPart finger1Tip;
    protected final ModelPart finger2;
    protected final ModelPart finger2Tip;
    protected final ModelPart finger3;
    protected final ModelPart finger3Tip;
    protected final ModelPart thumb;
    protected final ModelPart thumbTip;

    public PalehandModel(ModelPart root) {
        super(RenderType::entityCutoutNoCull);
        this.root = root;
        this.wrist = root.getChild("wrist");
        this.palm = this.wrist.getChild("palm");
        this.finger0 = this.palm.getChild("finger_0");
        this.finger0Tip = this.finger0.getChild("finger_0_tip");
        this.finger1 = this.palm.getChild("finger_1");
        this.finger1Tip = this.finger1.getChild("finger_1_tip");
        this.finger2 = this.palm.getChild("finger_2");
        this.finger2Tip = this.finger2.getChild("finger_2_tip");
        this.finger3 = this.palm.getChild("finger_3");
        this.finger3Tip = this.finger3.getChild("finger_3_tip");
        this.thumb = this.palm.getChild("thumb");
        this.thumbTip = this.thumb.getChild("thumb_tip");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition wristDef = root.addOrReplaceChild("wrist", CubeListBuilder.create().texOffs(0, 0).addBox(-3.0F, -10.0F, -2.0F, 6.0F, 10.0F, 4.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition palmDef = wristDef.addOrReplaceChild("palm", CubeListBuilder.create().texOffs(20, 0).addBox(-4.0F, -8.0F, -2.0F, 8.0F, 8.0F, 4.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -10.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition finger0Def = palmDef.addOrReplaceChild("finger_0", CubeListBuilder.create().texOffs(0, 14).addBox(-1.0F, -5.0F, -1.0F, 2.0F, 5.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-3.0F, -8.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition finger0TipDef = finger0Def.addOrReplaceChild("finger_0_tip", CubeListBuilder.create().texOffs(16, 14).addBox(-1.0F, -4.0F, -1.0F, 2.0F, 4.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -5.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition finger1Def = palmDef.addOrReplaceChild("finger_1", CubeListBuilder.create().texOffs(44, 0).addBox(-1.0F, -6.0F, -1.0F, 2.0F, 6.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-1.0F, -8.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition finger1TipDef = finger1Def.addOrReplaceChild("finger_1_tip", CubeListBuilder.create().texOffs(24, 14).addBox(-1.0F, -4.0F, -1.0F, 2.0F, 4.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -6.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition finger2Def = palmDef.addOrReplaceChild("finger_2", CubeListBuilder.create().texOffs(8, 14).addBox(-1.0F, -5.0F, -1.0F, 2.0F, 5.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(1.0F, -8.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition finger2TipDef = finger2Def.addOrReplaceChild("finger_2_tip", CubeListBuilder.create().texOffs(32, 14).addBox(-1.0F, -4.0F, -1.0F, 2.0F, 4.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -5.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition finger3Def = palmDef.addOrReplaceChild("finger_3", CubeListBuilder.create().texOffs(40, 14).addBox(-1.0F, -4.0F, -1.0F, 2.0F, 4.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(3.0F, -8.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition finger3TipDef = finger3Def.addOrReplaceChild("finger_3_tip", CubeListBuilder.create().texOffs(48, 14).addBox(-1.0F, -4.0F, -1.0F, 2.0F, 4.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -4.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition thumbDef = palmDef.addOrReplaceChild("thumb", CubeListBuilder.create().texOffs(52, 0).addBox(-2.0F, -6.0F, -1.0F, 2.0F, 6.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-4.0F, -2.0F, 0.0F, 0.0F, 0.0F, 0.6F));
        PartDefinition thumbTipDef = thumbDef.addOrReplaceChild("thumb_tip", CubeListBuilder.create().texOffs(56, 14).addBox(-1.0F, -3.0F, -1.0F, 2.0F, 3.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-1.0F, -6.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    @Override
    public ModelPart root() {
        return root;
    }

    @Override
    public void setupAnim(T entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        root().getAllParts().forEach(ModelPart::resetPose);
        finger0.xRot += 0.15F + Mth.sin(ageInTicks * 0.045F + 0.0F) * 0.35F;
        finger0Tip.xRot += 0.25F + Mth.sin(ageInTicks * 0.045F + 0.7F) * 0.4F;
        finger1.xRot += 0.15F + Mth.sin(ageInTicks * 0.045F + 1.0F) * 0.35F;
        finger1Tip.xRot += 0.25F + Mth.sin(ageInTicks * 0.045F + 1.7F) * 0.4F;
        finger2.xRot += 0.15F + Mth.sin(ageInTicks * 0.045F + 2.0F) * 0.35F;
        finger2Tip.xRot += 0.25F + Mth.sin(ageInTicks * 0.045F + 2.7F) * 0.4F;
        finger3.xRot += 0.15F + Mth.sin(ageInTicks * 0.045F + 3.0F) * 0.35F;
        finger3Tip.xRot += 0.25F + Mth.sin(ageInTicks * 0.045F + 3.7F) * 0.4F;
        thumb.zRot += Mth.sin(ageInTicks * 0.03F) * 0.15F;
        wrist.zRot += Mth.sin(ageInTicks * 0.02F) * 0.06F;
    }
}
