package com.exonoxic.palimpsest.client.model;

import com.exonoxic.palimpsest.Palimpsest;
import com.exonoxic.palimpsest.entity.PaleStagEntity;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.HierarchicalModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.util.Mth;

/**
 * Generated by tools/gen_models.py from the "pale_stag" spec. Edit the spec, not this file.
 */
@SuppressWarnings("unused")
public class PaleStagModel<T extends PaleStagEntity> extends HierarchicalModel<T> {
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(Palimpsest.id("pale_stag"), "main");
    private final ModelPart root;
    protected final ModelPart body;
    protected final ModelPart neck;
    protected final ModelPart head;
    protected final ModelPart leftAntler;
    protected final ModelPart leftTineA;
    protected final ModelPart leftTineB;
    protected final ModelPart leftTineC;
    protected final ModelPart rightAntler;
    protected final ModelPart rightTineA;
    protected final ModelPart rightTineB;
    protected final ModelPart rightTineC;
    protected final ModelPart leftEar;
    protected final ModelPart rightEar;
    protected final ModelPart frontLeftLeg;
    protected final ModelPart frontRightLeg;
    protected final ModelPart hindLeftLeg;
    protected final ModelPart hindRightLeg;
    protected final ModelPart tail;

    public PaleStagModel(ModelPart root) {
        super(RenderType::entityCutoutNoCull);
        this.root = root;
        this.body = root.getChild("body");
        this.neck = root.getChild("neck");
        this.head = this.neck.getChild("head");
        this.leftAntler = this.head.getChild("left_antler");
        this.leftTineA = this.leftAntler.getChild("left_tine_a");
        this.leftTineB = this.leftAntler.getChild("left_tine_b");
        this.leftTineC = this.leftAntler.getChild("left_tine_c");
        this.rightAntler = this.head.getChild("right_antler");
        this.rightTineA = this.rightAntler.getChild("right_tine_a");
        this.rightTineB = this.rightAntler.getChild("right_tine_b");
        this.rightTineC = this.rightAntler.getChild("right_tine_c");
        this.leftEar = this.head.getChild("left_ear");
        this.rightEar = this.head.getChild("right_ear");
        this.frontLeftLeg = root.getChild("front_left_leg");
        this.frontRightLeg = root.getChild("front_right_leg");
        this.hindLeftLeg = root.getChild("hind_left_leg");
        this.hindRightLeg = root.getChild("hind_right_leg");
        this.tail = root.getChild("tail");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition bodyDef = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-3.5F, -3.5F, -7.0F, 7.0F, 7.0F, 14.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 9.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition neckDef = root.addOrReplaceChild("neck", CubeListBuilder.create().texOffs(16, 21).addBox(-1.5F, -8.0F, -1.5F, 3.0F, 9.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 7.0F, -6.0F, 0.55F, 0.0F, 0.0F));
        PartDefinition headDef = neckDef.addOrReplaceChild("head", CubeListBuilder.create().texOffs(28, 21).addBox(-2.0F, -3.0F, -5.0F, 4.0F, 4.0F, 6.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -8.0F, 0.0F, -0.55F, 0.0F, 0.0F));
        PartDefinition leftAntlerDef = headDef.addOrReplaceChild("left_antler", CubeListBuilder.create().texOffs(48, 21).addBox(-0.5F, -7.0F, -0.5F, 1.0F, 7.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(1.5F, -3.0F, -1.0F, 0.0F, 0.0F, 0.35F));
        PartDefinition leftTineADef = leftAntlerDef.addOrReplaceChild("left_tine_a", CubeListBuilder.create().texOffs(56, 21).addBox(-0.5F, -4.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -4.0F, 0.0F, -0.4F, 0.0F, 0.8F));
        PartDefinition leftTineBDef = leftAntlerDef.addOrReplaceChild("left_tine_b", CubeListBuilder.create().texOffs(60, 21).addBox(-0.5F, -4.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -7.0F, 0.0F, 0.3F, 0.0F, -0.6F));
        PartDefinition leftTineCDef = leftAntlerDef.addOrReplaceChild("left_tine_c", CubeListBuilder.create().texOffs(14, 35).addBox(-0.5F, -3.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -2.0F, 0.0F, -0.7F, 0.0F, 0.2F));
        PartDefinition rightAntlerDef = headDef.addOrReplaceChild("right_antler", CubeListBuilder.create().texOffs(52, 21).addBox(-0.5F, -7.0F, -0.5F, 1.0F, 7.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-1.5F, -3.0F, -1.0F, 0.0F, 0.0F, -0.35F));
        PartDefinition rightTineADef = rightAntlerDef.addOrReplaceChild("right_tine_a", CubeListBuilder.create().texOffs(0, 35).addBox(-0.5F, -4.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -4.0F, 0.0F, -0.4F, 0.0F, -0.8F));
        PartDefinition rightTineBDef = rightAntlerDef.addOrReplaceChild("right_tine_b", CubeListBuilder.create().texOffs(4, 35).addBox(-0.5F, -4.0F, -0.5F, 1.0F, 4.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -7.0F, 0.0F, 0.3F, 0.0F, 0.6F));
        PartDefinition rightTineCDef = rightAntlerDef.addOrReplaceChild("right_tine_c", CubeListBuilder.create().texOffs(18, 35).addBox(-0.5F, -3.0F, -0.5F, 1.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -2.0F, 0.0F, -0.7F, 0.0F, -0.2F));
        PartDefinition leftEarDef = headDef.addOrReplaceChild("left_ear", CubeListBuilder.create().texOffs(22, 35).addBox(0.0F, -0.5F, -0.5F, 3.0F, 1.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(2.0F, -2.5F, 0.0F, 0.0F, 0.0F, -0.6F));
        PartDefinition rightEarDef = headDef.addOrReplaceChild("right_ear", CubeListBuilder.create().texOffs(32, 35).addBox(-3.0F, -0.5F, -0.5F, 3.0F, 1.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-2.0F, -2.5F, 0.0F, 0.0F, 0.0F, 0.6F));
        PartDefinition frontLeftLegDef = root.addOrReplaceChild("front_left_leg", CubeListBuilder.create().texOffs(42, 0).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 12.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(2.2F, 12.0F, -5.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition frontRightLegDef = root.addOrReplaceChild("front_right_leg", CubeListBuilder.create().texOffs(50, 0).mirror().addBox(-1.0F, 0.0F, -1.0F, 2.0F, 12.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-2.2F, 12.0F, -5.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition hindLeftLegDef = root.addOrReplaceChild("hind_left_leg", CubeListBuilder.create().texOffs(0, 21).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 12.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(2.2F, 12.0F, 5.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition hindRightLegDef = root.addOrReplaceChild("hind_right_leg", CubeListBuilder.create().texOffs(8, 21).mirror().addBox(-1.0F, 0.0F, -1.0F, 2.0F, 12.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-2.2F, 12.0F, 5.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition tailDef = root.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(8, 35).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 6.5F, 7.0F, 0.6F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    @Override
    public ModelPart root() {
        return root;
    }

    @Override
    public void setupAnim(T entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        root().getAllParts().forEach(ModelPart::resetPose);
        neck.yRot += netHeadYaw * Mth.DEG_TO_RAD * 0.5F;
        head.yRot += netHeadYaw * Mth.DEG_TO_RAD * 0.5F;
        head.xRot += headPitch * Mth.DEG_TO_RAD;
        frontLeftLeg.xRot += Mth.cos(limbSwing * 0.6662F) * 1.3F * limbSwingAmount;
        hindRightLeg.xRot += Mth.cos(limbSwing * 0.6662F) * 1.3F * limbSwingAmount;
        frontRightLeg.xRot += Mth.cos(limbSwing * 0.6662F + Mth.PI) * 1.3F * limbSwingAmount;
        hindLeftLeg.xRot += Mth.cos(limbSwing * 0.6662F + Mth.PI) * 1.3F * limbSwingAmount;
        leftEar.zRot += Mth.sin(ageInTicks * 0.12F) * 0.15F;
        rightEar.zRot -= Mth.sin(ageInTicks * 0.12F + 1.0F) * 0.15F;
    }
}
