package com.exonoxic.palimpsest.client.model;

import com.exonoxic.palimpsest.Palimpsest;
import com.exonoxic.palimpsest.entity.boss.RasureEntity;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.HierarchicalModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.util.Mth;

/**
 * Generated by tools/gen_models.py from the "rasure" spec. Edit the spec, not this file.
 */
@SuppressWarnings("unused")
public class RasureModel<T extends RasureEntity> extends HierarchicalModel<T> {
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(Palimpsest.id("rasure"), "main");
    private final ModelPart root;
    protected final ModelPart robe;
    protected final ModelPart body;
    protected final ModelPart head;
    protected final ModelPart bladeArm;
    protected final ModelPart blade;
    protected final ModelPart bladeTip;
    protected final ModelPart leftArm;
    protected final ModelPart fingers;
    protected final ModelPart page0;
    protected final ModelPart page1;
    protected final ModelPart page2;
    protected final ModelPart page3;

    public RasureModel(ModelPart root) {
        super(RenderType::entityCutoutNoCull);
        this.root = root;
        this.robe = root.getChild("robe");
        this.body = root.getChild("body");
        this.head = this.body.getChild("head");
        this.bladeArm = this.body.getChild("blade_arm");
        this.blade = this.bladeArm.getChild("blade");
        this.bladeTip = this.blade.getChild("blade_tip");
        this.leftArm = this.body.getChild("left_arm");
        this.fingers = this.leftArm.getChild("fingers");
        this.page0 = this.body.getChild("page_0");
        this.page1 = this.body.getChild("page_1");
        this.page2 = this.body.getChild("page_2");
        this.page3 = this.body.getChild("page_3");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition robeDef = root.addOrReplaceChild("robe", CubeListBuilder.create().texOffs(12, 0).addBox(-6.0F, -14.0F, -4.0F, 12.0F, 14.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition bodyDef = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(52, 0).addBox(-5.0F, -14.0F, -3.0F, 10.0F, 14.0F, 6.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 10.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition headDef = bodyDef.addOrReplaceChild("head", CubeListBuilder.create().texOffs(84, 0).addBox(-4.0F, -12.0F, -4.0F, 8.0F, 12.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -14.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition bladeArmDef = bodyDef.addOrReplaceChild("blade_arm", CubeListBuilder.create().texOffs(0, 25).mirror().addBox(-1.5F, 0.0F, -1.5F, 3.0F, 14.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-6.0F, -12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition bladeDef = bladeArmDef.addOrReplaceChild("blade", CubeListBuilder.create().texOffs(0, 0).addBox(-0.5F, 0.0F, -4.0F, 1.0F, 20.0F, 5.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 14.0F, 0.0F, 0.2F, 0.0F, 0.0F));
        PartDefinition bladeTipDef = bladeDef.addOrReplaceChild("blade_tip", CubeListBuilder.create().texOffs(12, 25).addBox(-0.5F, 0.0F, -3.0F, 1.0F, 10.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 20.0F, 0.0F, -0.5F, 0.0F, 0.0F));
        PartDefinition leftArmDef = bodyDef.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(116, 0).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 16.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(6.0F, -12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition fingersDef = leftArmDef.addOrReplaceChild("fingers", CubeListBuilder.create().texOffs(20, 25).addBox(-2.0F, 0.0F, -1.0F, 4.0F, 8.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 16.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition page0Def = bodyDef.addOrReplaceChild("page_0", CubeListBuilder.create().texOffs(32, 25).addBox(9.0F, -3.0F, 0.0F, 4.0F, 5.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -22.0F, 0.0F, 0.0F, 0.0F, 0.2F));
        PartDefinition page1Def = bodyDef.addOrReplaceChild("page_1", CubeListBuilder.create().texOffs(40, 25).addBox(9.0F, -3.0F, 0.0F, 4.0F, 5.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -22.0F, 0.0F, 0.0F, 1.5708F, 0.2F));
        PartDefinition page2Def = bodyDef.addOrReplaceChild("page_2", CubeListBuilder.create().texOffs(48, 25).addBox(9.0F, -3.0F, 0.0F, 4.0F, 5.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -22.0F, 0.0F, 0.0F, 3.1416F, 0.2F));
        PartDefinition page3Def = bodyDef.addOrReplaceChild("page_3", CubeListBuilder.create().texOffs(56, 25).addBox(9.0F, -3.0F, 0.0F, 4.0F, 5.0F, 0.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -22.0F, 0.0F, 0.0F, 4.7124F, 0.2F));
        return LayerDefinition.create(mesh, 128, 64);
    }

    @Override
    public ModelPart root() {
        return root;
    }

    @Override
    public void setupAnim(T entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        root().getAllParts().forEach(ModelPart::resetPose);
        head.yRot += netHeadYaw * Mth.DEG_TO_RAD;
        head.xRot += headPitch * Mth.DEG_TO_RAD;
        float bob = Mth.sin(ageInTicks * 0.1F) * 1.5F;
        body.y += bob;
        robe.y += bob * 0.6F;
        robe.xRot += Mth.cos(limbSwing * 0.6F) * 0.12F * limbSwingAmount;
        float spin = ageInTicks * 0.05F;
        page0.yRot += spin;
        page1.yRot += spin;
        page2.yRot += spin;
        page3.yRot += spin;
        int phase = entity.getPhase();
        if (entity.isShielded()) {
            bladeArm.xRot -= 2.6F;
            leftArm.xRot -= 2.6F;
            head.xRot -= 0.5F;
        } else if (attackTime > 0) {
            float s = Mth.sin(Mth.sqrt(attackTime) * Mth.PI);
            bladeArm.xRot -= 2.2F * s;
            bladeArm.yRot += 0.8F * s;
            body.yRot -= 0.4F * s;
        } else {
            bladeArm.xRot += -0.25F + Mth.sin(ageInTicks * 0.06F) * 0.08F;
            leftArm.xRot += -0.15F + Mth.cos(ageInTicks * 0.06F) * 0.08F;
            fingers.xRot += Mth.sin(ageInTicks * 0.2F) * 0.2F;
        }
        if (phase == com.exonoxic.palimpsest.entity.boss.RasureEntity.BLANK_PAGE) head.zRot += 0.4F;
    }
}
