package com.exonoxic.palimpsest.client.model;

import com.exonoxic.palimpsest.Palimpsest;
import com.exonoxic.palimpsest.entity.RubricatorEntity;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.HierarchicalModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.util.Mth;

/**
 * Generated by tools/gen_models.py from the "rubricator" spec. Edit the spec, not this file.
 */
@SuppressWarnings("unused")
public class RubricatorModel<T extends RubricatorEntity> extends HierarchicalModel<T> {
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(Palimpsest.id("rubricator"), "main");
    private final ModelPart root;
    protected final ModelPart head;
    protected final ModelPart hoodTop;
    protected final ModelPart hoodLeft;
    protected final ModelPart hoodRight;
    protected final ModelPart hoodBack;
    protected final ModelPart body;
    protected final ModelPart foldedArms;
    protected final ModelPart quill;
    protected final ModelPart skirt;

    public RubricatorModel(ModelPart root) {
        super(RenderType::entityCutoutNoCull);
        this.root = root;
        this.head = root.getChild("head");
        this.hoodTop = this.head.getChild("hood_top");
        this.hoodLeft = this.head.getChild("hood_left");
        this.hoodRight = this.head.getChild("hood_right");
        this.hoodBack = this.head.getChild("hood_back");
        this.body = root.getChild("body");
        this.foldedArms = this.body.getChild("folded_arms");
        this.quill = this.foldedArms.getChild("quill");
        this.skirt = root.getChild("skirt");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition headDef = root.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 19).addBox(-4.0F, -8.0F, -4.0F, 8.0F, 8.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition hoodTopDef = headDef.addOrReplaceChild("hood_top", CubeListBuilder.create().texOffs(32, 19).addBox(-5.0F, -9.0F, -5.0F, 10.0F, 1.0F, 10.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition hoodLeftDef = headDef.addOrReplaceChild("hood_left", CubeListBuilder.create().texOffs(32, 0).addBox(4.0F, -8.0F, -5.0F, 1.0F, 9.0F, 10.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition hoodRightDef = headDef.addOrReplaceChild("hood_right", CubeListBuilder.create().texOffs(54, 0).mirror().addBox(-5.0F, -8.0F, -5.0F, 1.0F, 9.0F, 10.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition hoodBackDef = headDef.addOrReplaceChild("hood_back", CubeListBuilder.create().texOffs(72, 19).addBox(-4.0F, -8.0F, 4.0F, 8.0F, 9.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition bodyDef = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(76, 0).addBox(-4.0F, 0.0F, -3.0F, 8.0F, 12.0F, 6.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition foldedArmsDef = bodyDef.addOrReplaceChild("folded_arms", CubeListBuilder.create().texOffs(94, 19).addBox(-4.0F, -2.0F, -3.0F, 8.0F, 4.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 4.0F, -3.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition quillDef = foldedArmsDef.addOrReplaceChild("quill", CubeListBuilder.create().texOffs(90, 19).addBox(-0.5F, -8.0F, -0.5F, 1.0F, 9.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(2.0F, -1.0F, -2.0F, 0.3F, 0.0F, -0.35F));
        PartDefinition skirtDef = root.addOrReplaceChild("skirt", CubeListBuilder.create().texOffs(0, 0).addBox(-4.5F, 0.0F, -3.5F, 9.0F, 12.0F, 7.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 128, 64);
    }

    @Override
    public ModelPart root() {
        return root;
    }

    @Override
    public void setupAnim(T entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        root().getAllParts().forEach(ModelPart::resetPose);
        head.yRot += netHeadYaw * Mth.DEG_TO_RAD;
        head.xRot += headPitch * Mth.DEG_TO_RAD;
        float sway = Mth.sin(ageInTicks * 0.05F) * 0.03F;
        body.zRot += sway;
        skirt.zRot += sway * 0.5F;
        skirt.xRot += Mth.cos(limbSwing * 0.6662F) * 0.15F * limbSwingAmount;
        quill.xRot += Mth.sin(ageInTicks * 0.1F) * 0.08F;
    }
}
