# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=47.3.0
forge_version_range=[47.1,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

## Mod
mod_id=palimpsest
mod_name=Palimpsest
mod_license=GPL-3.0-or-later
mod_version=1.0.0
mod_group_id=com.exonoxic.palimpsest
mod_authors=exonoxic
mod_description=This world was written over another. A slow-burning horror and mystery mod: something older is showing through the page.
